In [ ]:
import pandas as pd
df=pd.read_csv('student_data (1).csv')
print(df)

   StudentID          FullName  Data Structure Marks  Algorithm Marks  \
0     PH1001       Alif Rahman                  85.0             85.0
1     PH1002     Fatima Akhter                  92.0             92.0
2     PH1003     Imran Hossain                  88.0             88.0
3     PH1004  Jannatul Ferdous                  78.0             78.0
4     PH1005       Kamal Uddin                   NaN              NaN
5     PH1006       Laila Begum                  75.0             75.0
6     PH1007    Mahmudul Hasan                  80.0             80.0
7     PH1008       Nadia Islam                  81.0             81.0
8     PH1009        Omar Faruq                  72.0             72.0
9     PH1010      Priya Sharma                  89.0             89.0
10    PH1011      Rahim Sheikh                   NaN              NaN
11    PH1012   Sadia Chowdhury                  85.0             85.0
12    PH1013      Tanvir Ahmed                  75.0             75.0
13    PH1014        Urmi Akter                   NaN              NaN
14    PH1015      Wahiduzzaman                  86.0             86.0
15    PH1016      Ziaur Rahman                  94.0             94.0
16    PH1017       Afsana Mimi                  90.0             90.0
17    PH1018       Babul Ahmed                  88.0             88.0
18    PH1019      Faria Rahman                   NaN              NaN
19    PH1020        Nasir Khan                  86.0             86.0

    Python Marks CompletionStatus EnrollmentDate Instructor    Location
0           88.0        Completed     2024-01-15  Mr. Karim       Dhaka
1            NaN      In Progress     2024-01-20  Ms. Salma  Chattogram
2           85.0        Completed     2024-02-10  Mr. Karim       Dhaka
3           82.0        Completed     2024-02-12  Ms. Salma      Sylhet
4           95.0      In Progress     2024-03-05  Mr. Karim  Chattogram
5           78.0        Completed     2024-03-08  Ms. Salma    Rajshahi
6            NaN      In Progress     2024-04-01  Mr. Karim       Dhaka
7           85.0        Completed     2024-04-22  Ms. Salma  Chattogram
8           76.0        Completed     2024-05-16  Mr. David       Dhaka
9           88.0        Completed     2024-05-20  Ms. Salma      Sylhet
10          91.0      In Progress     2024-06-11  Mr. Karim      Khulna
11          87.0        Completed     2024-06-14  Ms. Salma  Chattogram
12          79.0        Completed     2024-07-02  Mr. David       Dhaka
13           NaN      Not Started     2024-07-09  Ms. Salma    Rajshahi
14          84.0        Completed     2024-08-18  Mr. Karim       Dhaka
15           NaN      In Progress     2024-08-21  Ms. Salma  Chattogram
16          93.0        Completed     2025-09-01  Mr. Karim       Dhaka
17          85.0        Completed     2025-09-05  Ms. Salma      Sylhet
18           NaN      Not Started     2025-09-15  Mr. David  Chattogram
19          89.0        Completed     2025-10-02  Ms. Salma       Dhaka

In [4]:
print(type(df))

<class 'pandas.core.frame.DataFrame'>

In [6]:
student_id=df['StudentID']
print(student_id)

print(type(student_id))

0     PH1001
1     PH1002
2     PH1003
3     PH1004
4     PH1005
5     PH1006
6     PH1007
7     PH1008
8     PH1009
9     PH1010
10    PH1011
11    PH1012
12    PH1013
13    PH1014
14    PH1015
15    PH1016
16    PH1017
17    PH1018
18    PH1019
19    PH1020
Name: StudentID, dtype: object
<class 'pandas.core.series.Series'>

 Different file types in Pandas

In [9]:
import pandas as pd
csv_data=pd.read_csv('student_data (1).csv')
print(csv_data)
print(type(csv_data))

   StudentID          FullName  Data Structure Marks  Algorithm Marks  \
0     PH1001       Alif Rahman                  85.0             85.0
1     PH1002     Fatima Akhter                  92.0             92.0
2     PH1003     Imran Hossain                  88.0             88.0
3     PH1004  Jannatul Ferdous                  78.0             78.0
4     PH1005       Kamal Uddin                   NaN              NaN
5     PH1006       Laila Begum                  75.0             75.0
6     PH1007    Mahmudul Hasan                  80.0             80.0
7     PH1008       Nadia Islam                  81.0             81.0
8     PH1009        Omar Faruq                  72.0             72.0
9     PH1010      Priya Sharma                  89.0             89.0
10    PH1011      Rahim Sheikh                   NaN              NaN
11    PH1012   Sadia Chowdhury                  85.0             85.0
12    PH1013      Tanvir Ahmed                  75.0             75.0
13    PH1014        Urmi Akter                   NaN              NaN
14    PH1015      Wahiduzzaman                  86.0             86.0
15    PH1016      Ziaur Rahman                  94.0             94.0
16    PH1017       Afsana Mimi                  90.0             90.0
17    PH1018       Babul Ahmed                  88.0             88.0
18    PH1019      Faria Rahman                   NaN              NaN
19    PH1020        Nasir Khan                  86.0             86.0

    Python Marks CompletionStatus EnrollmentDate Instructor    Location
0           88.0        Completed     2024-01-15  Mr. Karim       Dhaka
1            NaN      In Progress     2024-01-20  Ms. Salma  Chattogram
2           85.0        Completed     2024-02-10  Mr. Karim       Dhaka
3           82.0        Completed     2024-02-12  Ms. Salma      Sylhet
4           95.0      In Progress     2024-03-05  Mr. Karim  Chattogram
5           78.0        Completed     2024-03-08  Ms. Salma    Rajshahi
6            NaN      In Progress     2024-04-01  Mr. Karim       Dhaka
7           85.0        Completed     2024-04-22  Ms. Salma  Chattogram
8           76.0        Completed     2024-05-16  Mr. David       Dhaka
9           88.0        Completed     2024-05-20  Ms. Salma      Sylhet
10          91.0      In Progress     2024-06-11  Mr. Karim      Khulna
11          87.0        Completed     2024-06-14  Ms. Salma  Chattogram
12          79.0        Completed     2024-07-02  Mr. David       Dhaka
13           NaN      Not Started     2024-07-09  Ms. Salma    Rajshahi
14          84.0        Completed     2024-08-18  Mr. Karim       Dhaka
15           NaN      In Progress     2024-08-21  Ms. Salma  Chattogram
16          93.0        Completed     2025-09-01  Mr. Karim       Dhaka
17          85.0        Completed     2025-09-05  Ms. Salma      Sylhet
18           NaN      Not Started     2025-09-15  Mr. David  Chattogram
19          89.0        Completed     2025-10-02  Ms. Salma       Dhaka
<class 'pandas.core.frame.DataFrame'>

In [12]:
#excel file
excel_file=pd.read_excel('phitron_student_marks.xlsx')
print(excel_file)

   StudentID          FullName  Data Structure Marks  Algorithm Marks  \
0     PH1001       Alif Rahman                  85.0             85.0
1     PH1002     Fatima Akhter                  92.0             92.0
2     PH1003     Imran Hossain                  88.0             88.0
3     PH1004  Jannatul Ferdous                  78.0             78.0
4     PH1005       Kamal Uddin                   NaN              NaN
5     PH1006       Laila Begum                  75.0             75.0
6     PH1007    Mahmudul Hasan                  80.0             80.0
7     PH1008       Nadia Islam                  81.0             81.0
8     PH1009        Omar Faruq                  72.0             72.0
9     PH1010      Priya Sharma                  89.0             89.0
10    PH1011      Rahim Sheikh                   NaN              NaN
11    PH1012   Sadia Chowdhury                  85.0             85.0
12    PH1013      Tanvir Ahmed                  75.0             75.0
13    PH1014        Urmi Akter                   NaN              NaN
14    PH1015      Wahiduzzaman                  86.0             86.0
15    PH1016      Ziaur Rahman                  94.0             94.0
16    PH1017       Afsana Mimi                  90.0             90.0
17    PH1018       Babul Ahmed                  88.0             88.0
18    PH1019      Faria Rahman                   NaN              NaN
19    PH1020        Nasir Khan                  86.0             86.0

    Python Marks CompletionStatus EnrollmentDate Instructor    Location
0           88.0        Completed     2024-01-15  Mr. Karim       Dhaka
1            NaN      In Progress     2024-01-20  Ms. Salma  Chattogram
2           85.0        Completed     2024-02-10  Mr. Karim       Dhaka
3           82.0        Completed     2024-02-12  Ms. Salma      Sylhet
4           95.0      In Progress     2024-03-05  Mr. Karim  Chattogram
5           78.0        Completed     2024-03-08  Ms. Salma    Rajshahi
6            NaN      In Progress     2024-04-01  Mr. Karim       Dhaka
7           85.0        Completed     2024-04-22  Ms. Salma  Chattogram
8           76.0        Completed     2024-05-16  Mr. David       Dhaka
9           88.0        Completed     2024-05-20  Ms. Salma      Sylhet
10          91.0      In Progress     2024-06-11  Mr. Karim      Khulna
11          87.0        Completed     2024-06-14  Ms. Salma  Chattogram
12          79.0        Completed     2024-07-02  Mr. David       Dhaka
13           NaN      Not Started     2024-07-09  Ms. Salma    Rajshahi
14          84.0        Completed     2024-08-18  Mr. Karim       Dhaka
15           NaN      In Progress     2024-08-21  Ms. Salma  Chattogram
16          93.0        Completed     2025-09-01  Mr. Karim       Dhaka
17          85.0        Completed     2025-09-05  Ms. Salma      Sylhet
18           NaN      Not Started     2025-09-15  Mr. David  Chattogram
19          89.0        Completed     2025-10-02  Ms. Salma       Dhaka

In [14]:
#parquet file
parquet_file=pd.read_parquet('students.parquet')
print(parquet_file)

print(type(parquet_file))

   StudentID          FullName  Data Structure Marks  Algorithm Marks  \
0     PH1001       Alif Rahman                  85.0             85.0
1     PH1002     Fatima Akhter                  92.0             92.0
2     PH1003     Imran Hossain                  88.0             88.0
3     PH1004  Jannatul Ferdous                  78.0             78.0
4     PH1005       Kamal Uddin                   NaN              NaN
5     PH1006       Laila Begum                  75.0             75.0
6     PH1007    Mahmudul Hasan                  80.0             80.0
7     PH1008       Nadia Islam                  81.0             81.0
8     PH1009        Omar Faruq                  72.0             72.0
9     PH1010      Priya Sharma                  89.0             89.0
10    PH1011      Rahim Sheikh                   NaN              NaN
11    PH1012   Sadia Chowdhury                  85.0             85.0
12    PH1013      Tanvir Ahmed                  75.0             75.0
13    PH1014        Urmi Akter                   NaN              NaN
14    PH1015      Wahiduzzaman                  86.0             86.0
15    PH1016      Ziaur Rahman                  94.0             94.0
16    PH1017       Afsana Mimi                  90.0             90.0
17    PH1018       Babul Ahmed                  88.0             88.0
18    PH1019      Faria Rahman                   NaN              NaN
19    PH1020        Nasir Khan                  86.0             86.0

    Python Marks CompletionStatus EnrollmentDate Instructor    Location
0           88.0        Completed     2024-01-15  Mr. Karim       Dhaka
1            NaN      In Progress     2024-01-20  Ms. Salma  Chattogram
2           85.0        Completed     2024-02-10  Mr. Karim       Dhaka
3           82.0        Completed     2024-02-12  Ms. Salma      Sylhet
4           95.0      In Progress     2024-03-05  Mr. Karim  Chattogram
5           78.0        Completed     2024-03-08  Ms. Salma    Rajshahi
6            NaN      In Progress     2024-04-01  Mr. Karim       Dhaka
7           85.0        Completed     2024-04-22  Ms. Salma  Chattogram
8           76.0        Completed     2024-05-16  Mr. David       Dhaka
9           88.0        Completed     2024-05-20  Ms. Salma      Sylhet
10          91.0      In Progress     2024-06-11  Mr. Karim      Khulna
11          87.0        Completed     2024-06-14  Ms. Salma  Chattogram
12          79.0        Completed     2024-07-02  Mr. David       Dhaka
13           NaN      Not Started     2024-07-09  Ms. Salma    Rajshahi
14          84.0        Completed     2024-08-18  Mr. Karim       Dhaka
15           NaN      In Progress     2024-08-21  Ms. Salma  Chattogram
16          93.0        Completed     2025-09-01  Mr. Karim       Dhaka
17          85.0        Completed     2025-09-05  Ms. Salma      Sylhet
18           NaN      Not Started     2025-09-15  Mr. David  Chattogram
19          89.0        Completed     2025-10-02  Ms. Salma       Dhaka
<class 'pandas.core.frame.DataFrame'>

In [ ]:
#json file
json_file=pd.read_json('data.json')
print(json_file)

  StudentID          FullName  Data Structure Marks  Algorithm Marks  \
0    PH1001       Alif Rahman                    85               85
1    PH1002     Fatima Akhter                    92               92
2    PH1004  Jannatul Ferdous                    78               78

   Python Marks
0            88
1            90
2            82

Pandas Basic Funtionalities

In [17]:
df=pd.read_csv('student_data (1).csv')
print(df)

   StudentID          FullName  Data Structure Marks  Algorithm Marks  \
0     PH1001       Alif Rahman                  85.0             85.0
1     PH1002     Fatima Akhter                  92.0             92.0
2     PH1003     Imran Hossain                  88.0             88.0
3     PH1004  Jannatul Ferdous                  78.0             78.0
4     PH1005       Kamal Uddin                   NaN              NaN
5     PH1006       Laila Begum                  75.0             75.0
6     PH1007    Mahmudul Hasan                  80.0             80.0
7     PH1008       Nadia Islam                  81.0             81.0
8     PH1009        Omar Faruq                  72.0             72.0
9     PH1010      Priya Sharma                  89.0             89.0
10    PH1011      Rahim Sheikh                   NaN              NaN
11    PH1012   Sadia Chowdhury                  85.0             85.0
12    PH1013      Tanvir Ahmed                  75.0             75.0
13    PH1014        Urmi Akter                   NaN              NaN
14    PH1015      Wahiduzzaman                  86.0             86.0
15    PH1016      Ziaur Rahman                  94.0             94.0
16    PH1017       Afsana Mimi                  90.0             90.0
17    PH1018       Babul Ahmed                  88.0             88.0
18    PH1019      Faria Rahman                   NaN              NaN
19    PH1020        Nasir Khan                  86.0             86.0

    Python Marks CompletionStatus EnrollmentDate Instructor    Location
0           88.0        Completed     2024-01-15  Mr. Karim       Dhaka
1            NaN      In Progress     2024-01-20  Ms. Salma  Chattogram
2           85.0        Completed     2024-02-10  Mr. Karim       Dhaka
3           82.0        Completed     2024-02-12  Ms. Salma      Sylhet
4           95.0      In Progress     2024-03-05  Mr. Karim  Chattogram
5           78.0        Completed     2024-03-08  Ms. Salma    Rajshahi
6            NaN      In Progress     2024-04-01  Mr. Karim       Dhaka
7           85.0        Completed     2024-04-22  Ms. Salma  Chattogram
8           76.0        Completed     2024-05-16  Mr. David       Dhaka
9           88.0        Completed     2024-05-20  Ms. Salma      Sylhet
10          91.0      In Progress     2024-06-11  Mr. Karim      Khulna
11          87.0        Completed     2024-06-14  Ms. Salma  Chattogram
12          79.0        Completed     2024-07-02  Mr. David       Dhaka
13           NaN      Not Started     2024-07-09  Ms. Salma    Rajshahi
14          84.0        Completed     2024-08-18  Mr. Karim       Dhaka
15           NaN      In Progress     2024-08-21  Ms. Salma  Chattogram
16          93.0        Completed     2025-09-01  Mr. Karim       Dhaka
17          85.0        Completed     2025-09-05  Ms. Salma      Sylhet
18           NaN      Not Started     2025-09-15  Mr. David  Chattogram
19          89.0        Completed     2025-10-02  Ms. Salma       Dhaka

In [19]:
#firt value using head() method
print(df.head(4))

  StudentID          FullName  Data Structure Marks  Algorithm Marks  \
0    PH1001       Alif Rahman                  85.0             85.0
1    PH1002     Fatima Akhter                  92.0             92.0
2    PH1003     Imran Hossain                  88.0             88.0
3    PH1004  Jannatul Ferdous                  78.0             78.0

   Python Marks CompletionStatus EnrollmentDate Instructor    Location
0          88.0        Completed     2024-01-15  Mr. Karim       Dhaka
1           NaN      In Progress     2024-01-20  Ms. Salma  Chattogram
2          85.0        Completed     2024-02-10  Mr. Karim       Dhaka
3          82.0        Completed     2024-02-12  Ms. Salma      Sylhet

In [20]:
#last value using tail() method
print(df.tail(4))

   StudentID      FullName  Data Structure Marks  Algorithm Marks  \
16    PH1017   Afsana Mimi                  90.0             90.0
17    PH1018   Babul Ahmed                  88.0             88.0
18    PH1019  Faria Rahman                   NaN              NaN
19    PH1020    Nasir Khan                  86.0             86.0

    Python Marks CompletionStatus EnrollmentDate Instructor    Location
16          93.0        Completed     2025-09-01  Mr. Karim       Dhaka
17          85.0        Completed     2025-09-05  Ms. Salma      Sylhet
18           NaN      Not Started     2025-09-15  Mr. David  Chattogram
19          89.0        Completed     2025-10-02  Ms. Salma       Dhaka

In [21]:
#column
import numpy as np
df.columns
col=np.array(df.columns)
print(col)

['StudentID' 'FullName' 'Data Structure Marks' 'Algorithm Marks'
 'Python Marks' 'CompletionStatus' 'EnrollmentDate' 'Instructor'
 'Location']

In [24]:
df.index
ind=np.array(df.index)
print(ind)
print(ind.dtype)

[ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19]
int64

In [25]:
#statistical values
df.describe()

       Data Structure Marks  Algorithm Marks  Python Marks
count             16.000000        16.000000     15.000000
mean              84.000000        84.000000     85.666667
std                6.501282         6.501282      5.394000
min               72.000000        72.000000     76.000000
25%               79.500000        79.500000     83.000000
50%               85.500000        85.500000     85.000000
75%               88.250000        88.250000     88.500000
max               94.000000        94.000000     95.000000

Transforming to df from inbuilt datas

In [29]:
my_list=[['Fariya',24],['Ratul',25],['Fahim',25]]
list_df=pd.DataFrame(my_list,columns=['Name','Age'],index=[1,2,3])
print(list_df)

list_df.to_csv('list_df.csv',index=False)

     Name  Age
1  Fariya   24
2   Ratul   25
3   Fahim   25

In [30]:
my_tuple=[('Fariya',24),('Ratul',25),('Fahim',25)]
tuple_df=pd.DataFrame(my_tuple,columns=['Name','Age'],index=[1,2,3])
tuple_df

     Name  Age
1  Fariya   24
2   Ratul   25
3   Fahim   25

In [31]:
my_dict={
    'Name':['Borsha','Radito','Fariya'],
    'Age':[24,23,28]
    
}

dict_df=pd.DataFrame(my_dict)
dict_df

     Name  Age
0  Borsha   24
1  Radito   23
2  Fariya   28

In [32]:
my_data=[
    {'Name':'Borsha','Age':24,'City':'Cumilla'},
    {'Name':'Radito','Age':23,'City':'Dhaka'},
    {'Name':'Fariya','Age':28,'City':'Chittagong'}
]
data_df=pd.DataFrame(my_data)
print(data_df)

     Name  Age        City
0  Borsha   24     Cumilla
1  Radito   23       Dhaka
2  Fariya   28  Chittagong

In [33]:
print(type(data_df['Name']))
print(type(data_df['Age']))
print(type(data_df['City']))

<class 'pandas.core.series.Series'>
<class 'pandas.core.series.Series'>
<class 'pandas.core.series.Series'>

In [34]:
df

,StudentID,FullName,Data Structure Marks,Algorithm Marks,Python Marks,CompletionStatus,EnrollmentDate,Instructor,Location
0,PH1001,Alif Rahman,85.0,85.0,88.0,Completed,2024-01-15,Mr. Karim,Dhaka
1,PH1002,Fatima Akhter,92.0,92.0,NaN,In Progress,2024-01-20,Ms. Salma,Chattogram
2,PH1003,Imran Hossain,88.0,88.0,85.0,Completed,2024-02-10,Mr. Karim,Dhaka
3,PH1004,Jannatul Ferdous,78.0,78.0,82.0,Completed,2024-02-12,Ms. Salma,Sylhet
4,PH1005,Kamal Uddin,NaN,NaN,95.0,In Progress,2024-03-05,Mr. Karim,Chattogram
5,PH1006,Laila Begum,75.0,75.0,78.0,Completed,2024-03-08,Ms. Salma,Rajshahi
6,PH1007,Mahmudul Hasan,80.0,80.0,NaN,In Progress,2024-04-01,Mr. Karim,Dhaka
7,PH1008,Nadia Islam,81.0,81.0,85.0,Completed,2024-04-22,Ms. Salma,Chattogram
8,PH1009,Omar Faruq,72.0,72.0,76.0,Completed,2024-05-16,Mr. David,Dhaka
9,PH1010,Priya Sharma,89.0,89.0,88.0,Completed,2024-05-20,Ms. Salma,Sylhet
10,PH1011,Rahim Sheikh,NaN,NaN,91.0,In Progress,2024-06-11,Mr. Karim,Khulna
11,PH1012,Sadia Chowdhury,85.0,85.0,87.0,Completed,2024-06-14,Ms. Salma,Chattogram
12,PH1013,Tanvir Ahmed,75.0,75.0,79.0,Completed,2024-07-02,Mr. David,Dhaka
13,PH1014,Urmi Akter,NaN,NaN,NaN,Not Started,2024-07-09,Ms. Salma,Rajshahi
14,PH1015,Wahiduzzaman,86.0,86.0,84.0,Completed,2024-08-18,Mr. Karim,Dhaka
15,PH1016,Ziaur Rahman,94.0,94.0,NaN,In Progress,2024-08-21,Ms. Salma,Chattogram
16,PH1017,Afsana Mimi,90.0,90.0,93.0,Completed,2025-09-01,Mr. Karim,Dhaka
17,PH1018,Babul Ahmed,88.0,88.0,85.0,Completed,2025-09-05,Ms. Salma,Sylhet
18,PH1019,Faria Rahman,NaN,NaN,NaN,Not Started,2025-09-15,Mr. David,Chattogram
19,PH1020,Nasir Khan,86.0,86.0,89.0,Completed,2025-10-02,Ms. Salma,Dhaka

Accessing Data with Index and Column

In [ ]:
df['FullName']
#type(df['FullName'])

pandas.core.series.Series

In [40]:
df.loc[2,'FullName']

'Fariya Islam'

In [41]:
df.loc[[2,4,8]]

,StudentID,FullName,Data Structure Marks,Algorithm Marks,Python Marks,CompletionStatus,EnrollmentDate,Instructor,Location
2,PH1003,Fariya Islam,88.0,88.0,85.0,Completed,2024-02-10,Mr. Karim,Dhaka
4,PH1005,Kamal Uddin,NaN,NaN,95.0,In Progress,2024-03-05,Mr. Karim,Chattogram
8,PH1009,Omar Faruq,72.0,72.0,76.0,Completed,2024-05-16,Mr. David,Dhaka

In [43]:
df.loc[7,'Data Structure Marks']

81.0

In [46]:
#multiple column
df.loc[:,['Data Structure Marks','EnrollmentDate']]

    Data Structure Marks EnrollmentDate
0                   85.0     2024-01-15
1                   92.0     2024-01-20
2                   88.0     2024-02-10
3                   78.0     2024-02-12
4                    NaN     2024-03-05
5                   75.0     2024-03-08
6                   80.0     2024-04-01
7                   81.0     2024-04-22
8                   72.0     2024-05-16
9                   89.0     2024-05-20
10                   NaN     2024-06-11
11                  85.0     2024-06-14
12                  75.0     2024-07-02
13                   NaN     2024-07-09
14                  86.0     2024-08-18
15                  94.0     2024-08-21
16                  90.0     2025-09-01
17                  88.0     2025-09-05
18                   NaN     2025-09-15
19                  86.0     2025-10-02

In [47]:
df.loc[3:7,['CompletionStatus']]

  CompletionStatus
3        Completed
4      In Progress
5        Completed
6      In Progress
7        Completed

Changing Index and Columns and iloc

In [48]:
df_indexed=df.set_index('StudentID')
df_indexed

,FullName,Data Structure Marks,Algorithm Marks,Python Marks,CompletionStatus,EnrollmentDate,Instructor,Location
StudentID,,,,,,,,
PH1001,Alif Rahman,85.0,85.0,88.0,Completed,2024-01-15,Mr. Karim,Dhaka
PH1002,Fatima Akhter,92.0,92.0,NaN,In Progress,2024-01-20,Ms. Salma,Chattogram
PH1003,Fariya Islam,88.0,88.0,85.0,Completed,2024-02-10,Mr. Karim,Dhaka
PH1004,Jannatul Ferdous,78.0,78.0,82.0,Completed,2024-02-12,Ms. Salma,Sylhet
PH1005,Kamal Uddin,NaN,NaN,95.0,In Progress,2024-03-05,Mr. Karim,Chattogram
PH1006,Laila Begum,75.0,75.0,78.0,Completed,2024-03-08,Ms. Salma,Rajshahi
PH1007,Mahmudul Hasan,80.0,80.0,NaN,In Progress,2024-04-01,Mr. Karim,Dhaka
PH1008,Nadia Islam,81.0,81.0,85.0,Completed,2024-04-22,Ms. Salma,Chattogram
PH1009,Omar Faruq,72.0,72.0,76.0,Completed,2024-05-16,Mr. David,Dhaka
PH1010,Priya Sharma,89.0,89.0,88.0,Completed,2024-05-20,Ms. Salma,Sylhet
PH1011,Rahim Sheikh,NaN,NaN,91.0,In Progress,2024-06-11,Mr. Karim,Khulna
PH1012,Sadia Chowdhury,85.0,85.0,87.0,Completed,2024-06-14,Ms. Salma,Chattogram
PH1013,Tanvir Ahmed,75.0,75.0,79.0,Completed,2024-07-02,Mr. David,Dhaka
PH1014,Urmi Akter,NaN,NaN,NaN,Not Started,2024-07-09,Ms. Salma,Rajshahi
PH1015,Wahiduzzaman,86.0,86.0,84.0,Completed,2024-08-18,Mr. Karim,Dhaka
PH1016,Ziaur Rahman,94.0,94.0,NaN,In Progress,2024-08-21,Ms. Salma,Chattogram
PH1017,Afsana Mimi,90.0,90.0,93.0,Completed,2025-09-01,Mr. Karim,Dhaka
PH1018,Babul Ahmed,88.0,88.0,85.0,Completed,2025-09-05,Ms. Salma,Sylhet
PH1019,Faria Rahman,NaN,NaN,NaN,Not Started,2025-09-15,Mr. David,Chattogram
PH1020,Nasir Khan,86.0,86.0,89.0,Completed,2025-10-02,Ms. Salma,Dhaka

In [49]:
df_indexed.iloc[:,0:5]

,FullName,Data Structure Marks,Algorithm Marks,Python Marks,CompletionStatus
StudentID,,,,,
PH1001,Alif Rahman,85.0,85.0,88.0,Completed
PH1002,Fatima Akhter,92.0,92.0,NaN,In Progress
PH1003,Fariya Islam,88.0,88.0,85.0,Completed
PH1004,Jannatul Ferdous,78.0,78.0,82.0,Completed
PH1005,Kamal Uddin,NaN,NaN,95.0,In Progress
PH1006,Laila Begum,75.0,75.0,78.0,Completed
PH1007,Mahmudul Hasan,80.0,80.0,NaN,In Progress
PH1008,Nadia Islam,81.0,81.0,85.0,Completed
PH1009,Omar Faruq,72.0,72.0,76.0,Completed
PH1010,Priya Sharma,89.0,89.0,88.0,Completed
PH1011,Rahim Sheikh,NaN,NaN,91.0,In Progress
PH1012,Sadia Chowdhury,85.0,85.0,87.0,Completed
PH1013,Tanvir Ahmed,75.0,75.0,79.0,Completed
PH1014,Urmi Akter,NaN,NaN,NaN,Not Started
PH1015,Wahiduzzaman,86.0,86.0,84.0,Completed
PH1016,Ziaur Rahman,94.0,94.0,NaN,In Progress
PH1017,Afsana Mimi,90.0,90.0,93.0,Completed
PH1018,Babul Ahmed,88.0,88.0,85.0,Completed
PH1019,Faria Rahman,NaN,NaN,NaN,Not Started
PH1020,Nasir Khan,86.0,86.0,89.0,Completed

In [ ]:
#change full name to full_name and algorithm marks to algo_Maths
df.rename(columns={'FullName':'Full_Name','Algorithm Marks':'algo_Maths'},inplace=True)
df

,StudentID,Full_Name,Data Structure Marks,algo_Maths,Python Marks,CompletionStatus,EnrollmentDate,Instructor,Location
0,PH1001,Alif Rahman,85.0,85.0,88.0,Completed,2024-01-15,Mr. Karim,Dhaka
1,PH1002,Fatima Akhter,92.0,92.0,NaN,In Progress,2024-01-20,Ms. Salma,Chattogram
2,PH1003,Fariya Islam,88.0,88.0,85.0,Completed,2024-02-10,Mr. Karim,Dhaka
3,PH1004,Jannatul Ferdous,78.0,78.0,82.0,Completed,2024-02-12,Ms. Salma,Sylhet
4,PH1005,Kamal Uddin,NaN,NaN,95.0,In Progress,2024-03-05,Mr. Karim,Chattogram
5,PH1006,Laila Begum,75.0,75.0,78.0,Completed,2024-03-08,Ms. Salma,Rajshahi
6,PH1007,Mahmudul Hasan,80.0,80.0,NaN,In Progress,2024-04-01,Mr. Karim,Dhaka
7,PH1008,Nadia Islam,81.0,81.0,85.0,Completed,2024-04-22,Ms. Salma,Chattogram
8,PH1009,Omar Faruq,72.0,72.0,76.0,Completed,2024-05-16,Mr. David,Dhaka
9,PH1010,Priya Sharma,89.0,89.0,88.0,Completed,2024-05-20,Ms. Salma,Sylhet
10,PH1011,Rahim Sheikh,NaN,NaN,91.0,In Progress,2024-06-11,Mr. Karim,Khulna
11,PH1012,Sadia Chowdhury,85.0,85.0,87.0,Completed,2024-06-14,Ms. Salma,Chattogram
12,PH1013,Tanvir Ahmed,75.0,75.0,79.0,Completed,2024-07-02,Mr. David,Dhaka
13,PH1014,Urmi Akter,NaN,NaN,NaN,Not Started,2024-07-09,Ms. Salma,Rajshahi
14,PH1015,Wahiduzzaman,86.0,86.0,84.0,Completed,2024-08-18,Mr. Karim,Dhaka
15,PH1016,Ziaur Rahman,94.0,94.0,NaN,In Progress,2024-08-21,Ms. Salma,Chattogram
16,PH1017,Afsana Mimi,90.0,90.0,93.0,Completed,2025-09-01,Mr. Karim,Dhaka
17,PH1018,Babul Ahmed,88.0,88.0,85.0,Completed,2025-09-05,Ms. Salma,Sylhet
18,PH1019,Faria Rahman,NaN,NaN,NaN,Not Started,2025-09-15,Mr. David,Chattogram
19,PH1020,Nasir Khan,86.0,86.0,89.0,Completed,2025-10-02,Ms. Salma,Dhaka

Dropping rows and columns,Assigning values and Iteration

In [52]:
df

,StudentID,Full_Name,Data Structure Marks,algo_Maths,Python Marks,CompletionStatus,EnrollmentDate,Instructor,Location
0,PH1001,Alif Rahman,85.0,85.0,88.0,Completed,2024-01-15,Mr. Karim,Dhaka
1,PH1002,Fatima Akhter,92.0,92.0,NaN,In Progress,2024-01-20,Ms. Salma,Chattogram
2,PH1003,Fariya Islam,88.0,88.0,85.0,Completed,2024-02-10,Mr. Karim,Dhaka
3,PH1004,Jannatul Ferdous,78.0,78.0,82.0,Completed,2024-02-12,Ms. Salma,Sylhet
4,PH1005,Kamal Uddin,NaN,NaN,95.0,In Progress,2024-03-05,Mr. Karim,Chattogram
5,PH1006,Laila Begum,75.0,75.0,78.0,Completed,2024-03-08,Ms. Salma,Rajshahi
6,PH1007,Mahmudul Hasan,80.0,80.0,NaN,In Progress,2024-04-01,Mr. Karim,Dhaka
7,PH1008,Nadia Islam,81.0,81.0,85.0,Completed,2024-04-22,Ms. Salma,Chattogram
8,PH1009,Omar Faruq,72.0,72.0,76.0,Completed,2024-05-16,Mr. David,Dhaka
9,PH1010,Priya Sharma,89.0,89.0,88.0,Completed,2024-05-20,Ms. Salma,Sylhet
10,PH1011,Rahim Sheikh,NaN,NaN,91.0,In Progress,2024-06-11,Mr. Karim,Khulna
11,PH1012,Sadia Chowdhury,85.0,85.0,87.0,Completed,2024-06-14,Ms. Salma,Chattogram
12,PH1013,Tanvir Ahmed,75.0,75.0,79.0,Completed,2024-07-02,Mr. David,Dhaka
13,PH1014,Urmi Akter,NaN,NaN,NaN,Not Started,2024-07-09,Ms. Salma,Rajshahi
14,PH1015,Wahiduzzaman,86.0,86.0,84.0,Completed,2024-08-18,Mr. Karim,Dhaka
15,PH1016,Ziaur Rahman,94.0,94.0,NaN,In Progress,2024-08-21,Ms. Salma,Chattogram
16,PH1017,Afsana Mimi,90.0,90.0,93.0,Completed,2025-09-01,Mr. Karim,Dhaka
17,PH1018,Babul Ahmed,88.0,88.0,85.0,Completed,2025-09-05,Ms. Salma,Sylhet
18,PH1019,Faria Rahman,NaN,NaN,NaN,Not Started,2025-09-15,Mr. David,Chattogram
19,PH1020,Nasir Khan,86.0,86.0,89.0,Completed,2025-10-02,Ms. Salma,Dhaka

In [ ]:
df.drop(2,inplace=True)   #drop the row with index 2
df

,StudentID,Full_Name,Data Structure Marks,algo_Maths,Python Marks,CompletionStatus,EnrollmentDate,Instructor,Location
1,PH1002,Fatima Akhter,92.0,92.0,NaN,In Progress,2024-01-20,Ms. Salma,Chattogram
3,PH1004,Jannatul Ferdous,78.0,78.0,82.0,Completed,2024-02-12,Ms. Salma,Sylhet
4,PH1005,Kamal Uddin,NaN,NaN,95.0,In Progress,2024-03-05,Mr. Karim,Chattogram
5,PH1006,Laila Begum,75.0,75.0,78.0,Completed,2024-03-08,Ms. Salma,Rajshahi
6,PH1007,Mahmudul Hasan,80.0,80.0,NaN,In Progress,2024-04-01,Mr. Karim,Dhaka
7,PH1008,Nadia Islam,81.0,81.0,85.0,Completed,2024-04-22,Ms. Salma,Chattogram
8,PH1009,Omar Faruq,72.0,72.0,76.0,Completed,2024-05-16,Mr. David,Dhaka
9,PH1010,Priya Sharma,89.0,89.0,88.0,Completed,2024-05-20,Ms. Salma,Sylhet
10,PH1011,Rahim Sheikh,NaN,NaN,91.0,In Progress,2024-06-11,Mr. Karim,Khulna
11,PH1012,Sadia Chowdhury,85.0,85.0,87.0,Completed,2024-06-14,Ms. Salma,Chattogram
12,PH1013,Tanvir Ahmed,75.0,75.0,79.0,Completed,2024-07-02,Mr. David,Dhaka
13,PH1014,Urmi Akter,NaN,NaN,NaN,Not Started,2024-07-09,Ms. Salma,Rajshahi
14,PH1015,Wahiduzzaman,86.0,86.0,84.0,Completed,2024-08-18,Mr. Karim,Dhaka
15,PH1016,Ziaur Rahman,94.0,94.0,NaN,In Progress,2024-08-21,Ms. Salma,Chattogram
16,PH1017,Afsana Mimi,90.0,90.0,93.0,Completed,2025-09-01,Mr. Karim,Dhaka
17,PH1018,Babul Ahmed,88.0,88.0,85.0,Completed,2025-09-05,Ms. Salma,Sylhet
18,PH1019,Faria Rahman,NaN,NaN,NaN,Not Started,2025-09-15,Mr. David,Chattogram
19,PH1020,Nasir Khan,86.0,86.0,89.0,Completed,2025-10-02,Ms. Salma,Dhaka

#column deletion

In [55]:
df.drop('EnrollmentDate',axis=1,inplace=True)
df

,StudentID,Full_Name,Data Structure Marks,algo_Maths,Python Marks,CompletionStatus,Instructor,Location
1,PH1002,Fatima Akhter,92.0,92.0,NaN,In Progress,Ms. Salma,Chattogram
3,PH1004,Jannatul Ferdous,78.0,78.0,82.0,Completed,Ms. Salma,Sylhet
4,PH1005,Kamal Uddin,NaN,NaN,95.0,In Progress,Mr. Karim,Chattogram
5,PH1006,Laila Begum,75.0,75.0,78.0,Completed,Ms. Salma,Rajshahi
6,PH1007,Mahmudul Hasan,80.0,80.0,NaN,In Progress,Mr. Karim,Dhaka
7,PH1008,Nadia Islam,81.0,81.0,85.0,Completed,Ms. Salma,Chattogram
8,PH1009,Omar Faruq,72.0,72.0,76.0,Completed,Mr. David,Dhaka
9,PH1010,Priya Sharma,89.0,89.0,88.0,Completed,Ms. Salma,Sylhet
10,PH1011,Rahim Sheikh,NaN,NaN,91.0,In Progress,Mr. Karim,Khulna
11,PH1012,Sadia Chowdhury,85.0,85.0,87.0,Completed,Ms. Salma,Chattogram
12,PH1013,Tanvir Ahmed,75.0,75.0,79.0,Completed,Mr. David,Dhaka
13,PH1014,Urmi Akter,NaN,NaN,NaN,Not Started,Ms. Salma,Rajshahi
14,PH1015,Wahiduzzaman,86.0,86.0,84.0,Completed,Mr. Karim,Dhaka
15,PH1016,Ziaur Rahman,94.0,94.0,NaN,In Progress,Ms. Salma,Chattogram
16,PH1017,Afsana Mimi,90.0,90.0,93.0,Completed,Mr. Karim,Dhaka
17,PH1018,Babul Ahmed,88.0,88.0,85.0,Completed,Ms. Salma,Sylhet
18,PH1019,Faria Rahman,NaN,NaN,NaN,Not Started,Mr. David,Chattogram
19,PH1020,Nasir Khan,86.0,86.0,89.0,Completed,Ms. Salma,Dhaka

Assigning values

In [56]:
df.loc[1,'Python Marks']=33
df

,StudentID,Full_Name,Data Structure Marks,algo_Maths,Python Marks,CompletionStatus,Instructor,Location
1,PH1002,Fatima Akhter,92.0,92.0,33.0,In Progress,Ms. Salma,Chattogram
3,PH1004,Jannatul Ferdous,78.0,78.0,82.0,Completed,Ms. Salma,Sylhet
4,PH1005,Kamal Uddin,NaN,NaN,95.0,In Progress,Mr. Karim,Chattogram
5,PH1006,Laila Begum,75.0,75.0,78.0,Completed,Ms. Salma,Rajshahi
6,PH1007,Mahmudul Hasan,80.0,80.0,NaN,In Progress,Mr. Karim,Dhaka
7,PH1008,Nadia Islam,81.0,81.0,85.0,Completed,Ms. Salma,Chattogram
8,PH1009,Omar Faruq,72.0,72.0,76.0,Completed,Mr. David,Dhaka
9,PH1010,Priya Sharma,89.0,89.0,88.0,Completed,Ms. Salma,Sylhet
10,PH1011,Rahim Sheikh,NaN,NaN,91.0,In Progress,Mr. Karim,Khulna
11,PH1012,Sadia Chowdhury,85.0,85.0,87.0,Completed,Ms. Salma,Chattogram
12,PH1013,Tanvir Ahmed,75.0,75.0,79.0,Completed,Mr. David,Dhaka
13,PH1014,Urmi Akter,NaN,NaN,NaN,Not Started,Ms. Salma,Rajshahi
14,PH1015,Wahiduzzaman,86.0,86.0,84.0,Completed,Mr. Karim,Dhaka
15,PH1016,Ziaur Rahman,94.0,94.0,NaN,In Progress,Ms. Salma,Chattogram
16,PH1017,Afsana Mimi,90.0,90.0,93.0,Completed,Mr. Karim,Dhaka
17,PH1018,Babul Ahmed,88.0,88.0,85.0,Completed,Ms. Salma,Sylhet
18,PH1019,Faria Rahman,NaN,NaN,NaN,Not Started,Mr. David,Chattogram
19,PH1020,Nasir Khan,86.0,86.0,89.0,Completed,Ms. Salma,Dhaka

In [57]:
#change CompletionStatus of index 1 to Completed
df.loc[1,'CompletionStatus']='completed'
df.head()

,StudentID,Full_Name,Data Structure Marks,algo_Maths,Python Marks,CompletionStatus,Instructor,Location
1,PH1002,Fatima Akhter,92.0,92.0,33.0,completed,Ms. Salma,Chattogram
3,PH1004,Jannatul Ferdous,78.0,78.0,82.0,Completed,Ms. Salma,Sylhet
4,PH1005,Kamal Uddin,NaN,NaN,95.0,In Progress,Mr. Karim,Chattogram
5,PH1006,Laila Begum,75.0,75.0,78.0,Completed,Ms. Salma,Rajshahi
6,PH1007,Mahmudul Hasan,80.0,80.0,NaN,In Progress,Mr. Karim,Dhaka

In [59]:
#change CompletionStatus of index 1 to 6  not Completed
df.loc[1:6,'CompletionStatus']='not completed'
df.head(6)

,StudentID,Full_Name,Data Structure Marks,algo_Maths,Python Marks,CompletionStatus,Instructor,Location
1,PH1002,Fatima Akhter,92.0,92.0,33.0,not completed,Ms. Salma,Chattogram
3,PH1004,Jannatul Ferdous,78.0,78.0,82.0,not completed,Ms. Salma,Sylhet
4,PH1005,Kamal Uddin,NaN,NaN,95.0,not completed,Mr. Karim,Chattogram
5,PH1006,Laila Begum,75.0,75.0,78.0,not completed,Ms. Salma,Rajshahi
6,PH1007,Mahmudul Hasan,80.0,80.0,NaN,not completed,Mr. Karim,Dhaka
7,PH1008,Nadia Islam,81.0,81.0,85.0,Completed,Ms. Salma,Chattogram

Iteration

In [61]:
for i,series in df.iterrows():
    print(i,series)

1 StudentID                      PH1002
Full_Name               Fatima Akhter
Data Structure Marks             92.0
algo_Maths                       92.0
Python Marks                     33.0
CompletionStatus        not completed
Instructor                  Ms. Salma
Location                   Chattogram
Name: 1, dtype: object
3 StudentID                         PH1004
Full_Name               Jannatul Ferdous
Data Structure Marks                78.0
algo_Maths                          78.0
Python Marks                        82.0
CompletionStatus           not completed
Instructor                     Ms. Salma
Location                          Sylhet
Name: 3, dtype: object
4 StudentID                      PH1005
Full_Name                 Kamal Uddin
Data Structure Marks              NaN
algo_Maths                        NaN
Python Marks                     95.0
CompletionStatus        not completed
Instructor                  Mr. Karim
Location                   Chattogram
Name: 4, dtype: object
5 StudentID                      PH1006
Full_Name                 Laila Begum
Data Structure Marks             75.0
algo_Maths                       75.0
Python Marks                     78.0
CompletionStatus        not completed
Instructor                  Ms. Salma
Location                     Rajshahi
Name: 5, dtype: object
6 StudentID                       PH1007
Full_Name               Mahmudul Hasan
Data Structure Marks              80.0
algo_Maths                        80.0
Python Marks                       NaN
CompletionStatus         not completed
Instructor                   Mr. Karim
Location                         Dhaka
Name: 6, dtype: object
7 StudentID                    PH1008
Full_Name               Nadia Islam
Data Structure Marks           81.0
algo_Maths                     81.0
Python Marks                   85.0
CompletionStatus          Completed
Instructor                Ms. Salma
Location                 Chattogram
Name: 7, dtype: object
8 StudentID                   PH1009
Full_Name               Omar Faruq
Data Structure Marks          72.0
algo_Maths                    72.0
Python Marks                  76.0
CompletionStatus         Completed
Instructor               Mr. David
Location                     Dhaka
Name: 8, dtype: object
9 StudentID                     PH1010
Full_Name               Priya Sharma
Data Structure Marks            89.0
algo_Maths                      89.0
Python Marks                    88.0
CompletionStatus           Completed
Instructor                 Ms. Salma
Location                      Sylhet
Name: 9, dtype: object
10 StudentID                     PH1011
Full_Name               Rahim Sheikh
Data Structure Marks             NaN
algo_Maths                       NaN
Python Marks                    91.0
CompletionStatus         In Progress
Instructor                 Mr. Karim
Location                      Khulna
Name: 10, dtype: object
11 StudentID                        PH1012
Full_Name               Sadia Chowdhury
Data Structure Marks               85.0
algo_Maths                         85.0
Python Marks                       87.0
CompletionStatus              Completed
Instructor                    Ms. Salma
Location                     Chattogram
Name: 11, dtype: object
12 StudentID                     PH1013
Full_Name               Tanvir Ahmed
Data Structure Marks            75.0
algo_Maths                      75.0
Python Marks                    79.0
CompletionStatus           Completed
Instructor                 Mr. David
Location                       Dhaka
Name: 12, dtype: object
13 StudentID                    PH1014
Full_Name                Urmi Akter
Data Structure Marks            NaN
algo_Maths                      NaN
Python Marks                    NaN
CompletionStatus        Not Started
Instructor                Ms. Salma
Location                   Rajshahi
Name: 13, dtype: object
14 StudentID                     PH1015
Full_Name               Wahiduzzaman
Data Structure Marks            86.0
algo_Maths                      86.0
Python Marks                    84.0
CompletionStatus           Completed
Instructor                 Mr. Karim
Location                       Dhaka
Name: 14, dtype: object
15 StudentID                     PH1016
Full_Name               Ziaur Rahman
Data Structure Marks            94.0
algo_Maths                      94.0
Python Marks                     NaN
CompletionStatus         In Progress
Instructor                 Ms. Salma
Location                  Chattogram
Name: 15, dtype: object
16 StudentID                    PH1017
Full_Name               Afsana Mimi
Data Structure Marks           90.0
algo_Maths                     90.0
Python Marks                   93.0
CompletionStatus          Completed
Instructor                Mr. Karim
Location                      Dhaka
Name: 16, dtype: object
17 StudentID                    PH1018
Full_Name               Babul Ahmed
Data Structure Marks           88.0
algo_Maths                     88.0
Python Marks                   85.0
CompletionStatus          Completed
Instructor                Ms. Salma
Location                     Sylhet
Name: 17, dtype: object
18 StudentID                     PH1019
Full_Name               Faria Rahman
Data Structure Marks             NaN
algo_Maths                       NaN
Python Marks                     NaN
CompletionStatus         Not Started
Instructor                 Mr. David
Location                  Chattogram
Name: 18, dtype: object
19 StudentID                   PH1020
Full_Name               Nasir Khan
Data Structure Marks          86.0
algo_Maths                    86.0
Python Marks                  89.0
CompletionStatus         Completed
Instructor               Ms. Salma
Location                     Dhaka
Name: 19, dtype: object

#iteration using itertuples

In [68]:
for i  in df.itertuples(index=True):
    print(i,series)

Pandas(Index=1, StudentID='PH1002', Full_Name='Fatima Akhter', _3=92.0, algo_Maths=92.0, _5=33.0, CompletionStatus='not completed', Instructor='Ms. Salma', Location='Chattogram') StudentID                   PH1020
Full_Name               Nasir Khan
Data Structure Marks          86.0
algo_Maths                    86.0
Python Marks                  89.0
CompletionStatus         Completed
Instructor               Ms. Salma
Location                     Dhaka
Name: 19, dtype: object
Pandas(Index=3, StudentID='PH1004', Full_Name='Jannatul Ferdous', _3=78.0, algo_Maths=78.0, _5=82.0, CompletionStatus='not completed', Instructor='Ms. Salma', Location='Sylhet') StudentID                   PH1020
Full_Name               Nasir Khan
Data Structure Marks          86.0
algo_Maths                    86.0
Python Marks                  89.0
CompletionStatus         Completed
Instructor               Ms. Salma
Location                     Dhaka
Name: 19, dtype: object
Pandas(Index=4, StudentID='PH1005', Full_Name='Kamal Uddin', _3=nan, algo_Maths=nan, _5=95.0, CompletionStatus='not completed', Instructor='Mr. Karim', Location='Chattogram') StudentID                   PH1020
Full_Name               Nasir Khan
Data Structure Marks          86.0
algo_Maths                    86.0
Python Marks                  89.0
CompletionStatus         Completed
Instructor               Ms. Salma
Location                     Dhaka
Name: 19, dtype: object
Pandas(Index=5, StudentID='PH1006', Full_Name='Laila Begum', _3=75.0, algo_Maths=75.0, _5=78.0, CompletionStatus='not completed', Instructor='Ms. Salma', Location='Rajshahi') StudentID                   PH1020
Full_Name               Nasir Khan
Data Structure Marks          86.0
algo_Maths                    86.0
Python Marks                  89.0
CompletionStatus         Completed
Instructor               Ms. Salma
Location                     Dhaka
Name: 19, dtype: object
Pandas(Index=6, StudentID='PH1007', Full_Name='Mahmudul Hasan', _3=80.0, algo_Maths=80.0, _5=nan, CompletionStatus='not completed', Instructor='Mr. Karim', Location='Dhaka') StudentID                   PH1020
Full_Name               Nasir Khan
Data Structure Marks          86.0
algo_Maths                    86.0
Python Marks                  89.0
CompletionStatus         Completed
Instructor               Ms. Salma
Location                     Dhaka
Name: 19, dtype: object
Pandas(Index=7, StudentID='PH1008', Full_Name='Nadia Islam', _3=81.0, algo_Maths=81.0, _5=85.0, CompletionStatus='Completed', Instructor='Ms. Salma', Location='Chattogram') StudentID                   PH1020
Full_Name               Nasir Khan
Data Structure Marks          86.0
algo_Maths                    86.0
Python Marks                  89.0
CompletionStatus         Completed
Instructor               Ms. Salma
Location                     Dhaka
Name: 19, dtype: object
Pandas(Index=8, StudentID='PH1009', Full_Name='Omar Faruq', _3=72.0, algo_Maths=72.0, _5=76.0, CompletionStatus='Completed', Instructor='Mr. David', Location='Dhaka') StudentID                   PH1020
Full_Name               Nasir Khan
Data Structure Marks          86.0
algo_Maths                    86.0
Python Marks                  89.0
CompletionStatus         Completed
Instructor               Ms. Salma
Location                     Dhaka
Name: 19, dtype: object
Pandas(Index=9, StudentID='PH1010', Full_Name='Priya Sharma', _3=89.0, algo_Maths=89.0, _5=88.0, CompletionStatus='Completed', Instructor='Ms. Salma', Location='Sylhet') StudentID                   PH1020
Full_Name               Nasir Khan
Data Structure Marks          86.0
algo_Maths                    86.0
Python Marks                  89.0
CompletionStatus         Completed
Instructor               Ms. Salma
Location                     Dhaka
Name: 19, dtype: object
Pandas(Index=10, StudentID='PH1011', Full_Name='Rahim Sheikh', _3=nan, algo_Maths=nan, _5=91.0, CompletionStatus='In Progress', Instructor='Mr. Karim', Location='Khulna') StudentID                   PH1020
Full_Name               Nasir Khan
Data Structure Marks          86.0
algo_Maths                    86.0
Python Marks                  89.0
CompletionStatus         Completed
Instructor               Ms. Salma
Location                     Dhaka
Name: 19, dtype: object
Pandas(Index=11, StudentID='PH1012', Full_Name='Sadia Chowdhury', _3=85.0, algo_Maths=85.0, _5=87.0, CompletionStatus='Completed', Instructor='Ms. Salma', Location='Chattogram') StudentID                   PH1020
Full_Name               Nasir Khan
Data Structure Marks          86.0
algo_Maths                    86.0
Python Marks                  89.0
CompletionStatus         Completed
Instructor               Ms. Salma
Location                     Dhaka
Name: 19, dtype: object
Pandas(Index=12, StudentID='PH1013', Full_Name='Tanvir Ahmed', _3=75.0, algo_Maths=75.0, _5=79.0, CompletionStatus='Completed', Instructor='Mr. David', Location='Dhaka') StudentID                   PH1020
Full_Name               Nasir Khan
Data Structure Marks          86.0
algo_Maths                    86.0
Python Marks                  89.0
CompletionStatus         Completed
Instructor               Ms. Salma
Location                     Dhaka
Name: 19, dtype: object
Pandas(Index=13, StudentID='PH1014', Full_Name='Urmi Akter', _3=nan, algo_Maths=nan, _5=nan, CompletionStatus='Not Started', Instructor='Ms. Salma', Location='Rajshahi') StudentID                   PH1020
Full_Name               Nasir Khan
Data Structure Marks          86.0
algo_Maths                    86.0
Python Marks                  89.0
CompletionStatus         Completed
Instructor               Ms. Salma
Location                     Dhaka
Name: 19, dtype: object
Pandas(Index=14, StudentID='PH1015', Full_Name='Wahiduzzaman', _3=86.0, algo_Maths=86.0, _5=84.0, CompletionStatus='Completed', Instructor='Mr. Karim', Location='Dhaka') StudentID                   PH1020
Full_Name               Nasir Khan
Data Structure Marks          86.0
algo_Maths                    86.0
Python Marks                  89.0
CompletionStatus         Completed
Instructor               Ms. Salma
Location                     Dhaka
Name: 19, dtype: object
Pandas(Index=15, StudentID='PH1016', Full_Name='Ziaur Rahman', _3=94.0, algo_Maths=94.0, _5=nan, CompletionStatus='In Progress', Instructor='Ms. Salma', Location='Chattogram') StudentID                   PH1020
Full_Name               Nasir Khan
Data Structure Marks          86.0
algo_Maths                    86.0
Python Marks                  89.0
CompletionStatus         Completed
Instructor               Ms. Salma
Location                     Dhaka
Name: 19, dtype: object
Pandas(Index=16, StudentID='PH1017', Full_Name='Afsana Mimi', _3=90.0, algo_Maths=90.0, _5=93.0, CompletionStatus='Completed', Instructor='Mr. Karim', Location='Dhaka') StudentID                   PH1020
Full_Name               Nasir Khan
Data Structure Marks          86.0
algo_Maths                    86.0
Python Marks                  89.0
CompletionStatus         Completed
Instructor               Ms. Salma
Location                     Dhaka
Name: 19, dtype: object
Pandas(Index=17, StudentID='PH1018', Full_Name='Babul Ahmed', _3=88.0, algo_Maths=88.0, _5=85.0, CompletionStatus='Completed', Instructor='Ms. Salma', Location='Sylhet') StudentID                   PH1020
Full_Name               Nasir Khan
Data Structure Marks          86.0
algo_Maths                    86.0
Python Marks                  89.0
CompletionStatus         Completed
Instructor               Ms. Salma
Location                     Dhaka
Name: 19, dtype: object
Pandas(Index=18, StudentID='PH1019', Full_Name='Faria Rahman', _3=nan, algo_Maths=nan, _5=nan, CompletionStatus='Not Started', Instructor='Mr. David', Location='Chattogram') StudentID                   PH1020
Full_Name               Nasir Khan
Data Structure Marks          86.0
algo_Maths                    86.0
Python Marks                  89.0
CompletionStatus         Completed
Instructor               Ms. Salma
Location                     Dhaka
Name: 19, dtype: object
Pandas(Index=19, StudentID='PH1020', Full_Name='Nasir Khan', _3=86.0, algo_Maths=86.0, _5=89.0, CompletionStatus='Completed', Instructor='Ms. Salma', Location='Dhaka') StudentID                   PH1020
Full_Name               Nasir Khan
Data Structure Marks          86.0
algo_Maths                    86.0
Python Marks                  89.0
CompletionStatus         Completed
Instructor               Ms. Salma
Location                     Dhaka
Name: 19, dtype: object

Sorting

In [69]:
df

,StudentID,Full_Name,Data Structure Marks,algo_Maths,Python Marks,CompletionStatus,Instructor,Location
1,PH1002,Fatima Akhter,92.0,92.0,33.0,not completed,Ms. Salma,Chattogram
3,PH1004,Jannatul Ferdous,78.0,78.0,82.0,not completed,Ms. Salma,Sylhet
4,PH1005,Kamal Uddin,NaN,NaN,95.0,not completed,Mr. Karim,Chattogram
5,PH1006,Laila Begum,75.0,75.0,78.0,not completed,Ms. Salma,Rajshahi
6,PH1007,Mahmudul Hasan,80.0,80.0,NaN,not completed,Mr. Karim,Dhaka
7,PH1008,Nadia Islam,81.0,81.0,85.0,Completed,Ms. Salma,Chattogram
8,PH1009,Omar Faruq,72.0,72.0,76.0,Completed,Mr. David,Dhaka
9,PH1010,Priya Sharma,89.0,89.0,88.0,Completed,Ms. Salma,Sylhet
10,PH1011,Rahim Sheikh,NaN,NaN,91.0,In Progress,Mr. Karim,Khulna
11,PH1012,Sadia Chowdhury,85.0,85.0,87.0,Completed,Ms. Salma,Chattogram
12,PH1013,Tanvir Ahmed,75.0,75.0,79.0,Completed,Mr. David,Dhaka
13,PH1014,Urmi Akter,NaN,NaN,NaN,Not Started,Ms. Salma,Rajshahi
14,PH1015,Wahiduzzaman,86.0,86.0,84.0,Completed,Mr. Karim,Dhaka
15,PH1016,Ziaur Rahman,94.0,94.0,NaN,In Progress,Ms. Salma,Chattogram
16,PH1017,Afsana Mimi,90.0,90.0,93.0,Completed,Mr. Karim,Dhaka
17,PH1018,Babul Ahmed,88.0,88.0,85.0,Completed,Ms. Salma,Sylhet
18,PH1019,Faria Rahman,NaN,NaN,NaN,Not Started,Mr. David,Chattogram
19,PH1020,Nasir Khan,86.0,86.0,89.0,Completed,Ms. Salma,Dhaka

In [71]:
copy=df.sort_values('Data Structure Marks')
copy

,StudentID,Full_Name,Data Structure Marks,algo_Maths,Python Marks,CompletionStatus,Instructor,Location
8,PH1009,Omar Faruq,72.0,72.0,76.0,Completed,Mr. David,Dhaka
5,PH1006,Laila Begum,75.0,75.0,78.0,not completed,Ms. Salma,Rajshahi
12,PH1013,Tanvir Ahmed,75.0,75.0,79.0,Completed,Mr. David,Dhaka
3,PH1004,Jannatul Ferdous,78.0,78.0,82.0,not completed,Ms. Salma,Sylhet
6,PH1007,Mahmudul Hasan,80.0,80.0,NaN,not completed,Mr. Karim,Dhaka
7,PH1008,Nadia Islam,81.0,81.0,85.0,Completed,Ms. Salma,Chattogram
11,PH1012,Sadia Chowdhury,85.0,85.0,87.0,Completed,Ms. Salma,Chattogram
14,PH1015,Wahiduzzaman,86.0,86.0,84.0,Completed,Mr. Karim,Dhaka
19,PH1020,Nasir Khan,86.0,86.0,89.0,Completed,Ms. Salma,Dhaka
17,PH1018,Babul Ahmed,88.0,88.0,85.0,Completed,Ms. Salma,Sylhet
9,PH1010,Priya Sharma,89.0,89.0,88.0,Completed,Ms. Salma,Sylhet
16,PH1017,Afsana Mimi,90.0,90.0,93.0,Completed,Mr. Karim,Dhaka
1,PH1002,Fatima Akhter,92.0,92.0,33.0,not completed,Ms. Salma,Chattogram
15,PH1016,Ziaur Rahman,94.0,94.0,NaN,In Progress,Ms. Salma,Chattogram
4,PH1005,Kamal Uddin,NaN,NaN,95.0,not completed,Mr. Karim,Chattogram
10,PH1011,Rahim Sheikh,NaN,NaN,91.0,In Progress,Mr. Karim,Khulna
13,PH1014,Urmi Akter,NaN,NaN,NaN,Not Started,Ms. Salma,Rajshahi
18,PH1019,Faria Rahman,NaN,NaN,NaN,Not Started,Mr. David,Chattogram

In [75]:
copy=df.sort_values(by='Python Marks',ascending=True)
copy

,StudentID,Full_Name,Data Structure Marks,algo_Maths,Python Marks,CompletionStatus,Instructor,Location
1,PH1002,Fatima Akhter,92.0,92.0,33.0,not completed,Ms. Salma,Chattogram
8,PH1009,Omar Faruq,72.0,72.0,76.0,Completed,Mr. David,Dhaka
5,PH1006,Laila Begum,75.0,75.0,78.0,not completed,Ms. Salma,Rajshahi
12,PH1013,Tanvir Ahmed,75.0,75.0,79.0,Completed,Mr. David,Dhaka
3,PH1004,Jannatul Ferdous,78.0,78.0,82.0,not completed,Ms. Salma,Sylhet
14,PH1015,Wahiduzzaman,86.0,86.0,84.0,Completed,Mr. Karim,Dhaka
7,PH1008,Nadia Islam,81.0,81.0,85.0,Completed,Ms. Salma,Chattogram
17,PH1018,Babul Ahmed,88.0,88.0,85.0,Completed,Ms. Salma,Sylhet
11,PH1012,Sadia Chowdhury,85.0,85.0,87.0,Completed,Ms. Salma,Chattogram
9,PH1010,Priya Sharma,89.0,89.0,88.0,Completed,Ms. Salma,Sylhet
19,PH1020,Nasir Khan,86.0,86.0,89.0,Completed,Ms. Salma,Dhaka
10,PH1011,Rahim Sheikh,NaN,NaN,91.0,In Progress,Mr. Karim,Khulna
16,PH1017,Afsana Mimi,90.0,90.0,93.0,Completed,Mr. Karim,Dhaka
4,PH1005,Kamal Uddin,NaN,NaN,95.0,not completed,Mr. Karim,Chattogram
6,PH1007,Mahmudul Hasan,80.0,80.0,NaN,not completed,Mr. Karim,Dhaka
13,PH1014,Urmi Akter,NaN,NaN,NaN,Not Started,Ms. Salma,Rajshahi
15,PH1016,Ziaur Rahman,94.0,94.0,NaN,In Progress,Ms. Salma,Chattogram
18,PH1019,Faria Rahman,NaN,NaN,NaN,Not Started,Mr. David,Chattogram

In [83]:
sorted_df=df.sort_values(['Python Marks','Data Structure Marks'],ascending=False)
copy

,StudentID,Full_Name,Data Structure Marks,algo_Maths,Python Marks,CompletionStatus,Instructor,Location
1,PH1002,Fatima Akhter,92.0,92.0,33.0,not completed,Ms. Salma,Chattogram
8,PH1009,Omar Faruq,72.0,72.0,76.0,Completed,Mr. David,Dhaka
5,PH1006,Laila Begum,75.0,75.0,78.0,not completed,Ms. Salma,Rajshahi
12,PH1013,Tanvir Ahmed,75.0,75.0,79.0,Completed,Mr. David,Dhaka
3,PH1004,Jannatul Ferdous,78.0,78.0,82.0,not completed,Ms. Salma,Sylhet
14,PH1015,Wahiduzzaman,86.0,86.0,84.0,Completed,Mr. Karim,Dhaka
7,PH1008,Nadia Islam,81.0,81.0,85.0,Completed,Ms. Salma,Chattogram
17,PH1018,Babul Ahmed,88.0,88.0,85.0,Completed,Ms. Salma,Sylhet
11,PH1012,Sadia Chowdhury,85.0,85.0,87.0,Completed,Ms. Salma,Chattogram
9,PH1010,Priya Sharma,89.0,89.0,88.0,Completed,Ms. Salma,Sylhet
19,PH1020,Nasir Khan,86.0,86.0,89.0,Completed,Ms. Salma,Dhaka
10,PH1011,Rahim Sheikh,NaN,NaN,91.0,In Progress,Mr. Karim,Khulna
16,PH1017,Afsana Mimi,90.0,90.0,93.0,Completed,Mr. Karim,Dhaka
4,PH1005,Kamal Uddin,NaN,NaN,95.0,not completed,Mr. Karim,Chattogram
6,PH1007,Mahmudul Hasan,80.0,80.0,NaN,not completed,Mr. Karim,Dhaka
13,PH1014,Urmi Akter,NaN,NaN,NaN,Not Started,Ms. Salma,Rajshahi
15,PH1016,Ziaur Rahman,94.0,94.0,NaN,In Progress,Ms. Salma,Chattogram
18,PH1019,Faria Rahman,NaN,NaN,NaN,Not Started,Mr. David,Chattogram

filtering data with condition

In [84]:
Not_completed=df.loc[df['CompletionStatus']=='not completed']
Not_completed

,StudentID,Full_Name,Data Structure Marks,algo_Maths,Python Marks,CompletionStatus,Instructor,Location
1,PH1002,Fatima Akhter,92.0,92.0,33.0,not completed,Ms. Salma,Chattogram
3,PH1004,Jannatul Ferdous,78.0,78.0,82.0,not completed,Ms. Salma,Sylhet
4,PH1005,Kamal Uddin,NaN,NaN,95.0,not completed,Mr. Karim,Chattogram
5,PH1006,Laila Begum,75.0,75.0,78.0,not completed,Ms. Salma,Rajshahi
6,PH1007,Mahmudul Hasan,80.0,80.0,NaN,not completed,Mr. Karim,Dhaka

In [86]:
df

,StudentID,Full_Name,Data Structure Marks,algo_Maths,Python Marks,CompletionStatus,Instructor,Location
1,PH1002,Fatima Akhter,92.0,92.0,33.0,not completed,Ms. Salma,Chattogram
3,PH1004,Jannatul Ferdous,78.0,78.0,82.0,not completed,Ms. Salma,Sylhet
4,PH1005,Kamal Uddin,NaN,NaN,95.0,not completed,Mr. Karim,Chattogram
5,PH1006,Laila Begum,75.0,75.0,78.0,not completed,Ms. Salma,Rajshahi
6,PH1007,Mahmudul Hasan,80.0,80.0,NaN,not completed,Mr. Karim,Dhaka
7,PH1008,Nadia Islam,81.0,81.0,85.0,Completed,Ms. Salma,Chattogram
8,PH1009,Omar Faruq,72.0,72.0,76.0,Completed,Mr. David,Dhaka
9,PH1010,Priya Sharma,89.0,89.0,88.0,Completed,Ms. Salma,Sylhet
10,PH1011,Rahim Sheikh,NaN,NaN,91.0,In Progress,Mr. Karim,Khulna
11,PH1012,Sadia Chowdhury,85.0,85.0,87.0,Completed,Ms. Salma,Chattogram
12,PH1013,Tanvir Ahmed,75.0,75.0,79.0,Completed,Mr. David,Dhaka
13,PH1014,Urmi Akter,NaN,NaN,NaN,Not Started,Ms. Salma,Rajshahi
14,PH1015,Wahiduzzaman,86.0,86.0,84.0,Completed,Mr. Karim,Dhaka
15,PH1016,Ziaur Rahman,94.0,94.0,NaN,In Progress,Ms. Salma,Chattogram
16,PH1017,Afsana Mimi,90.0,90.0,93.0,Completed,Mr. Karim,Dhaka
17,PH1018,Babul Ahmed,88.0,88.0,85.0,Completed,Ms. Salma,Sylhet
18,PH1019,Faria Rahman,NaN,NaN,NaN,Not Started,Mr. David,Chattogram
19,PH1020,Nasir Khan,86.0,86.0,89.0,Completed,Ms. Salma,Dhaka

In [104]:
completed=df.loc[df['CompletionStatus']=='Completed']
completed

,StudentID,Full_Name,Data Structure Marks,algo_Maths,Python Marks,CompletionStatus,Instructor,Location
7,PH1008,Nadia Islam,81.0,81.0,85.0,Completed,Ms. Salma,Chattogram
8,PH1009,Omar Faruq,72.0,72.0,76.0,Completed,Mr. David,Dhaka
9,PH1010,Priya Sharma,89.0,89.0,88.0,Completed,Ms. Salma,Sylhet
11,PH1012,Sadia Chowdhury,85.0,85.0,87.0,Completed,Ms. Salma,Chattogram
12,PH1013,Tanvir Ahmed,75.0,75.0,79.0,Completed,Mr. David,Dhaka
14,PH1015,Wahiduzzaman,86.0,86.0,84.0,Completed,Mr. Karim,Dhaka
16,PH1017,Afsana Mimi,90.0,90.0,93.0,Completed,Mr. Karim,Dhaka
17,PH1018,Babul Ahmed,88.0,88.0,85.0,Completed,Ms. Salma,Sylhet
19,PH1020,Nasir Khan,86.0,86.0,89.0,Completed,Ms. Salma,Dhaka

In [105]:
##completed and ds marks is greater or equal 90
final = df.loc[(df['CompletionStatus'] == 'Completed') & (df['Data Structure Marks'] >= 90)]
final

,StudentID,Full_Name,Data Structure Marks,algo_Maths,Python Marks,CompletionStatus,Instructor,Location
16,PH1017,Afsana Mimi,90.0,90.0,93.0,Completed,Mr. Karim,Dhaka

In [106]:
df

,StudentID,Full_Name,Data Structure Marks,algo_Maths,Python Marks,CompletionStatus,Instructor,Location
1,PH1002,Fatima Akhter,92.0,92.0,33.0,not completed,Ms. Salma,Chattogram
3,PH1004,Jannatul Ferdous,78.0,78.0,82.0,not completed,Ms. Salma,Sylhet
4,PH1005,Kamal Uddin,NaN,NaN,95.0,not completed,Mr. Karim,Chattogram
5,PH1006,Laila Begum,75.0,75.0,78.0,not completed,Ms. Salma,Rajshahi
6,PH1007,Mahmudul Hasan,80.0,80.0,NaN,not completed,Mr. Karim,Dhaka
7,PH1008,Nadia Islam,81.0,81.0,85.0,Completed,Ms. Salma,Chattogram
8,PH1009,Omar Faruq,72.0,72.0,76.0,Completed,Mr. David,Dhaka
9,PH1010,Priya Sharma,89.0,89.0,88.0,Completed,Ms. Salma,Sylhet
10,PH1011,Rahim Sheikh,NaN,NaN,91.0,In Progress,Mr. Karim,Khulna
11,PH1012,Sadia Chowdhury,85.0,85.0,87.0,Completed,Ms. Salma,Chattogram
12,PH1013,Tanvir Ahmed,75.0,75.0,79.0,Completed,Mr. David,Dhaka
13,PH1014,Urmi Akter,NaN,NaN,NaN,Not Started,Ms. Salma,Rajshahi
14,PH1015,Wahiduzzaman,86.0,86.0,84.0,Completed,Mr. Karim,Dhaka
15,PH1016,Ziaur Rahman,94.0,94.0,NaN,In Progress,Ms. Salma,Chattogram
16,PH1017,Afsana Mimi,90.0,90.0,93.0,Completed,Mr. Karim,Dhaka
17,PH1018,Babul Ahmed,88.0,88.0,85.0,Completed,Ms. Salma,Sylhet
18,PH1019,Faria Rahman,NaN,NaN,NaN,Not Started,Mr. David,Chattogram
19,PH1020,Nasir Khan,86.0,86.0,89.0,Completed,Ms. Salma,Dhaka