In [1]:
import pandas as pd
import numpy as np

In [4]:
#numpy array
arr=np.array([[1,2],[3,4]])
arr

array([[1, 2],
       [3, 4]])

In [7]:
df=pd.DataFrame(arr,columns=["A","B"])
print(df)

   A  B
0  1  2
1  3  4

series 1D labeled array

#series

In [11]:
s =pd.Series([10,20,30],index=["a","b","c"])
s

a    10
b    20
c    30
dtype: int64

In [12]:
print(s['a'])

10

In [21]:
#How to efficiently multiply all elements of a Pandas Series by a constant value?
import pandas as pd

s = pd.Series([10, 20, 30])

for i in s.index:
    s[i] = s[i] * 10
    print(s[i])

100
200
300

#Solution (Vectorization)

In [16]:
import pandas as pd

s = pd.Series([10, 20, 30])

s=s*10
print(s)

0    100
1    200
2    300
dtype: int64

In [22]:
df=pd.DataFrame(
   {
       "Name":["A","B"],
       "Age":[20,21]

   }
)
df

  Name  Age
0    A   20
1    B   21

In [25]:
print(type(df["Name"]))

<class 'pandas.core.series.Series'>

Indexing is level for rows

In [27]:
df.index

RangeIndex(start=0, stop=2, step=1)

#two dataframe  adding

In [29]:
df1=pd.Series([1,2],index=["a","b"])
df2=pd.Series([3,6],index=["a","b"])
print(df1+df2)

a    4
b    8
dtype: int64

In [34]:
df = pd.read_csv("sample_data/StudentsPerformance.csv")
df

,gender,race/ethnicity,parental level of education,lunch,test preparation course,math score,reading score,writing score
0,female,group B,bachelor's degree,standard,none,72,72,74
1,female,group C,some college,standard,completed,69,90,88
2,female,group B,master's degree,standard,none,90,95,93
3,male,group A,associate's degree,free/reduced,none,47,57,44
4,male,group C,some college,standard,none,76,78,75
...,...,...,...,...,...,...,...,...
995,female,group E,master's degree,standard,completed,88,99,95
996,male,group C,high school,free/reduced,none,62,55,55
997,female,group C,high school,free/reduced,completed,59,71,65
998,female,group D,some college,standard,completed,68,78,77
999,female,group D,some college,free/reduced,none,77,86,86

#loc and iloc

loc vs iloc

iloc ->position based

loc ->level based

In [35]:
df=pd.DataFrame(
   {
       "Name":["A","B"],
       "Age":[20,21]

   } ,
   index=["X","Y"]
)
df

  Name  Age
X    A   20
Y    B   21

In [36]:
#access Name
df["Name"]

X    A
Y    B
Name: Name, dtype: object

In [39]:
df.iloc[0]

Name     A
Age     20
Name: X, dtype: object

In [43]:

df.iloc[0:2]

  Name  Age
X    A   20
Y    B   21

In [46]:
#IF Only access A
df.iloc[0:1]

  Name  Age
X    A   20

In [48]:
df.iloc[0:1]

  Name  Age
X    A   20

In [49]:
#get multiple row
df.loc[["X","Y"]]

  Name  Age
X    A   20
Y    B   21

In [50]:
#conditional filtering
df.loc[df["Age"]>18]

  Name  Age
X    A   20
Y    B   21

Data manipulation

In [52]:
df=pd.DataFrame(
    {
        "Name":["A","B"],
        "Age":[20,21]
    }
)

#add new columns
df["Marks"]=[80,90]

df

  Name  Age  Marks
0    A   20     80
1    B   21     90

In [56]:
#drop columns
df2=df.drop("Marks",axis=1)
df2

  Name  Age
0    A   20
1    B   21

#filtering

In [57]:
df=pd.DataFrame(
    {
        "Name":["A","B","C"],
        "Age":[18,21,25]
    }
)
df

  Name  Age
0   A,   18
1    B   21
2    C   25

In [59]:
filtered_df=df[df["Age"]>18]
filtered_df

  Name  Age
1    B   21
2    C   25

##sorting

In [63]:
df=pd.DataFrame(
    {
        "Name":["A","B","C"],
        "Age":[25,21,18]
    }
)

#age
sorted_df=df.sort_values(by="Age")
sorted_df

  Name  Age
2    C   18
1    B   21
0    A   25

In [67]:
data={
    "Name":["Alice" ,"Bob","Charlie","David","Eva"],
    "Age":[20,21,19,22,20],
    "Marks":[85,67,90,45,88]
}
df=pd.DataFrame(data)
df

      Name  Age  Marks
0    Alice   20     85
1      Bob   21     67
2  Charlie   19     90
3    David   22     45
4      Eva   20     88

In [74]:
#add a grade columns
def assign_grade(Marks):
  if Marks>=80:
    return "A"
  elif Marks>=60:
    return "B"
  else :
    return "C"

df["Grade"]=df["Marks"].apply(assign_grade)
print(df.head())

      Name  Age  Marks Grade
0    Alice   20     85     A
1      Bob   21     67     B
2  Charlie   19     90     A
3    David   22     45     C
4      Eva   20     88     A

#Advance

In [75]:
sales_data = {
    "Order_ID": [1, 2, 3, 4, 5, 6, 7, 8],
    "Customer_ID": [101, 102, 101, 103, 104, 102, 105, 101],
    "Product": ["Laptop", "Phone", "Tablet", "Laptop", "Phone", "Tablet", "Laptop", "Phone"],
    "Category": ["Electronics", "Electronics", "Electronics", "Electronics", "Electronics", "Electronics", "Electronics", "Electronics"],
    "Price": [800, 500, 300, 850, 520, 310, 780, 510],
    "Quantity": [1, 2, 1, 1, 1, 3, 1, 2],
    "Date": ["2024-01-05", "2024-01-10", "2024-02-15", "2024-02-20", "2024-03-05", "2024-03-15", "2024-04-01", "2024-04-10"]
}
df = pd.DataFrame(sales_data)
df

   Order_ID  Customer_ID Product     Category  Price  Quantity        Date
0         1          101  Laptop  Electronics    800         1  2024-01-05
1         2          102   Phone  Electronics    500         2  2024-01-10
2         3          101  Tablet  Electronics    300         1  2024-02-15
3         4          103  Laptop  Electronics    850         1  2024-02-20
4         5          104   Phone  Electronics    520         1  2024-03-05
5         6          102  Tablet  Electronics    310         3  2024-03-15
6         7          105  Laptop  Electronics    780         1  2024-04-01
7         8          101   Phone  Electronics    510         2  2024-04-10

In [76]:
df.info

<bound method DataFrame.info of    Order_ID  Customer_ID Product     Category  Price  Quantity        Date
0         1          101  Laptop  Electronics    800         1  2024-01-05
1         2          102   Phone  Electronics    500         2  2024-01-10
2         3          101  Tablet  Electronics    300         1  2024-02-15
3         4          103  Laptop  Electronics    850         1  2024-02-20
4         5          104   Phone  Electronics    520         1  2024-03-05
5         6          102  Tablet  Electronics    310         3  2024-03-15
6         7          105  Laptop  Electronics    780         1  2024-04-01
7         8          101   Phone  Electronics    510         2  2024-04-10>

In [78]:
df["Date"]=pd.to_datetime(df["Date"])

In [79]:
df.dtypes

Order_ID                int64
Customer_ID             int64
Product                object
Category               object
Price                   int64
Quantity                int64
Date           datetime64[ns]
dtype: object