#Filtering Based on String

In [1]:
import pandas as pd

data={
    "Name": ["Alice", "Bob", "Charlie", "David", "Eve", "Frank", "Grace", "Hannah","Sakib"],
    "City": ["New York", "Los Angeles", "Newark", "Boston", "New Delhi", "Chicago", "New Orleans", "Houston","H Los Ang"],
    "Department": ["HR", "IT", "Finance", "IT", "HR", "Marketing", "Finance", "HR", "HR"],
    "Salary": [50000, 60000, 55000, 70000, 52000, 58000, 62000, 51000,70000]
}

df1=pd.DataFrame(data)

In [2]:
df1

      Name         City Department  Salary
0    Alice     New York         HR   50000
1      Bob  Los Angeles         IT   60000
2  Charlie       Newark    Finance   55000
3    David       Boston         IT   70000
4      Eve    New Delhi         HR   52000
5    Frank      Chicago  Marketing   58000
6    Grace  New Orleans    Finance   62000
7   Hannah      Houston         HR   51000
8    Sakib    H Los Ang         HR   70000

In [3]:
df1.loc[df1['City'].str.contains("New")]

      Name         City Department  Salary
0    Alice     New York         HR   50000
2  Charlie       Newark    Finance   55000
4      Eve    New Delhi         HR   52000
6    Grace  New Orleans    Finance   62000

In [4]:
df1.loc[df1['City'].str.contains("new",case=False)]

      Name         City Department  Salary
0    Alice     New York         HR   50000
2  Charlie       Newark    Finance   55000
4      Eve    New Delhi         HR   52000
6    Grace  New Orleans    Finance   62000

In [5]:
df1.loc[df1["Department"].str.contains("HR",case=False)]

     Name       City Department  Salary
0   Alice   New York         HR   50000
4     Eve  New Delhi         HR   52000
7  Hannah    Houston         HR   51000
8   Sakib  H Los Ang         HR   70000

In [6]:
#starts with Los
df1.loc[df1["City"].str.contains("Los",case=False)]

    Name         City Department  Salary
1    Bob  Los Angeles         IT   60000
8  Sakib    H Los Ang         HR   70000

In [7]:
#end with rk
df1.loc[df1["City"].str.contains(r"rk$")]

      Name      City Department  Salary
0    Alice  New York         HR   50000
2  Charlie    Newark    Finance   55000

In [8]:
#Department starts with a vowel
df1.loc[df1["Department"].str.contains(r"^[aeiou]",case=False)]

    Name         City Department  Salary
1    Bob  Los Angeles         IT   60000
3  David       Boston         IT   70000

In [9]:
#Name starts with a vowel
df1.loc[df1["Name"].str.contains(r"^[aeiou]",case=False)]

    Name       City Department  Salary
0  Alice   New York         HR   50000
4    Eve  New Delhi         HR   52000

#Adding New column

In [10]:
import pandas as pd
df2 = pd.read_csv('student_data.csv')
df2

,Unnamed: 0.3,Unnamed: 0.2,Unnamed: 0.1,Unnamed: 0,StudentID,FullName,Data Structure Marks,Algorithm Marks,Python Marks,CompletionStatus,EnrollmentDate,Instructor,Location,Country,University,Total Mark,DSA GPA,DSA PASS,pass in Python,Last name
0,0,0,0,0,PH1001,Alif Rahman,85.0,85.0,88.0,Completed,2024-01-15,Mr. Karim,Dhaka,Bangladesh,CSTU,258.0,A,Pass,Fail,Alif
1,1,1,1,1,PH1002,Fatima Akhter,92.0,92.0,NaN,In Progress,2024-01-20,Ms. Salma,Chattogram,Bangladesh,CSTU,NaN,A+,Pass,Fail,Fatima
2,2,2,2,2,PH1003,Imran Hossain,88.0,88.0,85.0,Completed,2024-02-10,Mr. Karim,Dhaka,Bangladesh,CSTU,261.0,A,Pass,Fail,Imran
3,3,3,3,3,PH1004,Jannatul Ferdous,78.0,78.0,82.0,Completed,2024-02-12,Ms. Salma,Sylhet,Bangladesh,CSTU,238.0,A,Pass,Fail,Jannatul
4,4,4,4,4,PH1005,Kamal Uddin,NaN,NaN,95.0,In Progress,2024-03-05,Mr. Karim,Chattogram,Bangladesh,CSTU,NaN,A,Pass,Fail,Kamal
5,5,5,5,5,PH1006,Laila Begum,75.0,75.0,78.0,Completed,2024-03-08,Ms. Salma,Rajshahi,Bangladesh,CSTU,228.0,A,Pass,Pass,Laila
6,6,6,6,6,PH1007,Mahmudul Hasan,80.0,80.0,NaN,In Progress,2024-04-01,Mr. Karim,Dhaka,Bangladesh,CSTU,NaN,A,Pass,Fail,Mahmudul
7,7,7,7,7,PH1008,Nadia Islam,81.0,81.0,85.0,Completed,2024-04-22,Ms. Salma,Chattogram,Bangladesh,CSTU,247.0,A,Pass,Fail,Nadia
8,8,8,8,8,PH1009,Omar Faruq,72.0,72.0,76.0,Completed,2024-05-16,Mr. David,Dhaka,Bangladesh,CSTU,220.0,A,Pass,Pass,Omar
9,9,9,9,9,PH1010,Priya Sharma,89.0,89.0,88.0,Completed,2024-05-20,Ms. Salma,Sylhet,Bangladesh,CSTU,266.0,A,Pass,Fail,Priya
10,10,10,10,10,PH1011,Rahim Sheikh,NaN,NaN,91.0,In Progress,2024-06-11,Mr. Karim,Khulna,Bangladesh,CSTU,NaN,A,Pass,Fail,Rahim
11,11,11,11,11,PH1012,Sadia Chowdhury,85.0,85.0,87.0,Completed,2024-06-14,Ms. Salma,Chattogram,Bangladesh,CSTU,257.0,A,Pass,Fail,Sadia
12,12,12,12,12,PH1013,Tanvir Ahmed,75.0,75.0,79.0,Completed,2024-07-02,Mr. David,Dhaka,Bangladesh,CSTU,229.0,A,Pass,Pass,Tanvir
13,13,13,13,13,PH1014,Urmi Akter,NaN,NaN,NaN,Not Started,2024-07-09,Ms. Salma,Rajshahi,Bangladesh,CSTU,NaN,A,Pass,Fail,Urmi
14,14,14,14,14,PH1015,Wahiduzzaman,86.0,86.0,84.0,Completed,2024-08-18,Mr. Karim,Dhaka,Bangladesh,CSTU,256.0,A,Pass,Fail,Wahiduzzaman
15,15,15,15,15,PH1016,Ziaur Rahman,94.0,94.0,NaN,In Progress,2024-08-21,Ms. Salma,Chattogram,Bangladesh,CSTU,NaN,A+,Pass,Fail,Ziaur
16,16,16,16,16,PH1017,Afsana Mimi,90.0,90.0,93.0,Completed,2025-09-01,Mr. Karim,Dhaka,Bangladesh,CSTU,273.0,A,Pass,Fail,Afsana
17,17,17,17,17,PH1018,Babul Ahmed,88.0,88.0,85.0,Completed,2025-09-05,Ms. Salma,Sylhet,Bangladesh,CSTU,261.0,A,Pass,Fail,Babul
18,18,18,18,18,PH1019,Faria Rahman,NaN,NaN,NaN,Not Started,2025-09-15,Mr. David,Chattogram,Bangladesh,CSTU,NaN,A,Pass,Fail,Faria
19,19,19,19,19,PH1020,Nasir Khan,86.0,86.0,89.0,Completed,2025-10-02,Ms. Salma,Dhaka,Bangladesh,CSTU,261.0,A,Pass,Fail,Nasir

In [11]:
#adding a colunm with constant value
df2['Country']='Bangladesh'
df2

,Unnamed: 0.3,Unnamed: 0.2,Unnamed: 0.1,Unnamed: 0,StudentID,FullName,Data Structure Marks,Algorithm Marks,Python Marks,CompletionStatus,EnrollmentDate,Instructor,Location,Country,University,Total Mark,DSA GPA,DSA PASS,pass in Python,Last name
0,0,0,0,0,PH1001,Alif Rahman,85.0,85.0,88.0,Completed,2024-01-15,Mr. Karim,Dhaka,Bangladesh,CSTU,258.0,A,Pass,Fail,Alif
1,1,1,1,1,PH1002,Fatima Akhter,92.0,92.0,NaN,In Progress,2024-01-20,Ms. Salma,Chattogram,Bangladesh,CSTU,NaN,A+,Pass,Fail,Fatima
2,2,2,2,2,PH1003,Imran Hossain,88.0,88.0,85.0,Completed,2024-02-10,Mr. Karim,Dhaka,Bangladesh,CSTU,261.0,A,Pass,Fail,Imran
3,3,3,3,3,PH1004,Jannatul Ferdous,78.0,78.0,82.0,Completed,2024-02-12,Ms. Salma,Sylhet,Bangladesh,CSTU,238.0,A,Pass,Fail,Jannatul
4,4,4,4,4,PH1005,Kamal Uddin,NaN,NaN,95.0,In Progress,2024-03-05,Mr. Karim,Chattogram,Bangladesh,CSTU,NaN,A,Pass,Fail,Kamal
5,5,5,5,5,PH1006,Laila Begum,75.0,75.0,78.0,Completed,2024-03-08,Ms. Salma,Rajshahi,Bangladesh,CSTU,228.0,A,Pass,Pass,Laila
6,6,6,6,6,PH1007,Mahmudul Hasan,80.0,80.0,NaN,In Progress,2024-04-01,Mr. Karim,Dhaka,Bangladesh,CSTU,NaN,A,Pass,Fail,Mahmudul
7,7,7,7,7,PH1008,Nadia Islam,81.0,81.0,85.0,Completed,2024-04-22,Ms. Salma,Chattogram,Bangladesh,CSTU,247.0,A,Pass,Fail,Nadia
8,8,8,8,8,PH1009,Omar Faruq,72.0,72.0,76.0,Completed,2024-05-16,Mr. David,Dhaka,Bangladesh,CSTU,220.0,A,Pass,Pass,Omar
9,9,9,9,9,PH1010,Priya Sharma,89.0,89.0,88.0,Completed,2024-05-20,Ms. Salma,Sylhet,Bangladesh,CSTU,266.0,A,Pass,Fail,Priya
10,10,10,10,10,PH1011,Rahim Sheikh,NaN,NaN,91.0,In Progress,2024-06-11,Mr. Karim,Khulna,Bangladesh,CSTU,NaN,A,Pass,Fail,Rahim
11,11,11,11,11,PH1012,Sadia Chowdhury,85.0,85.0,87.0,Completed,2024-06-14,Ms. Salma,Chattogram,Bangladesh,CSTU,257.0,A,Pass,Fail,Sadia
12,12,12,12,12,PH1013,Tanvir Ahmed,75.0,75.0,79.0,Completed,2024-07-02,Mr. David,Dhaka,Bangladesh,CSTU,229.0,A,Pass,Pass,Tanvir
13,13,13,13,13,PH1014,Urmi Akter,NaN,NaN,NaN,Not Started,2024-07-09,Ms. Salma,Rajshahi,Bangladesh,CSTU,NaN,A,Pass,Fail,Urmi
14,14,14,14,14,PH1015,Wahiduzzaman,86.0,86.0,84.0,Completed,2024-08-18,Mr. Karim,Dhaka,Bangladesh,CSTU,256.0,A,Pass,Fail,Wahiduzzaman
15,15,15,15,15,PH1016,Ziaur Rahman,94.0,94.0,NaN,In Progress,2024-08-21,Ms. Salma,Chattogram,Bangladesh,CSTU,NaN,A+,Pass,Fail,Ziaur
16,16,16,16,16,PH1017,Afsana Mimi,90.0,90.0,93.0,Completed,2025-09-01,Mr. Karim,Dhaka,Bangladesh,CSTU,273.0,A,Pass,Fail,Afsana
17,17,17,17,17,PH1018,Babul Ahmed,88.0,88.0,85.0,Completed,2025-09-05,Ms. Salma,Sylhet,Bangladesh,CSTU,261.0,A,Pass,Fail,Babul
18,18,18,18,18,PH1019,Faria Rahman,NaN,NaN,NaN,Not Started,2025-09-15,Mr. David,Chattogram,Bangladesh,CSTU,NaN,A,Pass,Fail,Faria
19,19,19,19,19,PH1020,Nasir Khan,86.0,86.0,89.0,Completed,2025-10-02,Ms. Salma,Dhaka,Bangladesh,CSTU,261.0,A,Pass,Fail,Nasir

In [12]:
#adding University
df2["University"]="CSTU"
df2

,Unnamed: 0.3,Unnamed: 0.2,Unnamed: 0.1,Unnamed: 0,StudentID,FullName,Data Structure Marks,Algorithm Marks,Python Marks,CompletionStatus,EnrollmentDate,Instructor,Location,Country,University,Total Mark,DSA GPA,DSA PASS,pass in Python,Last name
0,0,0,0,0,PH1001,Alif Rahman,85.0,85.0,88.0,Completed,2024-01-15,Mr. Karim,Dhaka,Bangladesh,CSTU,258.0,A,Pass,Fail,Alif
1,1,1,1,1,PH1002,Fatima Akhter,92.0,92.0,NaN,In Progress,2024-01-20,Ms. Salma,Chattogram,Bangladesh,CSTU,NaN,A+,Pass,Fail,Fatima
2,2,2,2,2,PH1003,Imran Hossain,88.0,88.0,85.0,Completed,2024-02-10,Mr. Karim,Dhaka,Bangladesh,CSTU,261.0,A,Pass,Fail,Imran
3,3,3,3,3,PH1004,Jannatul Ferdous,78.0,78.0,82.0,Completed,2024-02-12,Ms. Salma,Sylhet,Bangladesh,CSTU,238.0,A,Pass,Fail,Jannatul
4,4,4,4,4,PH1005,Kamal Uddin,NaN,NaN,95.0,In Progress,2024-03-05,Mr. Karim,Chattogram,Bangladesh,CSTU,NaN,A,Pass,Fail,Kamal
5,5,5,5,5,PH1006,Laila Begum,75.0,75.0,78.0,Completed,2024-03-08,Ms. Salma,Rajshahi,Bangladesh,CSTU,228.0,A,Pass,Pass,Laila
6,6,6,6,6,PH1007,Mahmudul Hasan,80.0,80.0,NaN,In Progress,2024-04-01,Mr. Karim,Dhaka,Bangladesh,CSTU,NaN,A,Pass,Fail,Mahmudul
7,7,7,7,7,PH1008,Nadia Islam,81.0,81.0,85.0,Completed,2024-04-22,Ms. Salma,Chattogram,Bangladesh,CSTU,247.0,A,Pass,Fail,Nadia
8,8,8,8,8,PH1009,Omar Faruq,72.0,72.0,76.0,Completed,2024-05-16,Mr. David,Dhaka,Bangladesh,CSTU,220.0,A,Pass,Pass,Omar
9,9,9,9,9,PH1010,Priya Sharma,89.0,89.0,88.0,Completed,2024-05-20,Ms. Salma,Sylhet,Bangladesh,CSTU,266.0,A,Pass,Fail,Priya
10,10,10,10,10,PH1011,Rahim Sheikh,NaN,NaN,91.0,In Progress,2024-06-11,Mr. Karim,Khulna,Bangladesh,CSTU,NaN,A,Pass,Fail,Rahim
11,11,11,11,11,PH1012,Sadia Chowdhury,85.0,85.0,87.0,Completed,2024-06-14,Ms. Salma,Chattogram,Bangladesh,CSTU,257.0,A,Pass,Fail,Sadia
12,12,12,12,12,PH1013,Tanvir Ahmed,75.0,75.0,79.0,Completed,2024-07-02,Mr. David,Dhaka,Bangladesh,CSTU,229.0,A,Pass,Pass,Tanvir
13,13,13,13,13,PH1014,Urmi Akter,NaN,NaN,NaN,Not Started,2024-07-09,Ms. Salma,Rajshahi,Bangladesh,CSTU,NaN,A,Pass,Fail,Urmi
14,14,14,14,14,PH1015,Wahiduzzaman,86.0,86.0,84.0,Completed,2024-08-18,Mr. Karim,Dhaka,Bangladesh,CSTU,256.0,A,Pass,Fail,Wahiduzzaman
15,15,15,15,15,PH1016,Ziaur Rahman,94.0,94.0,NaN,In Progress,2024-08-21,Ms. Salma,Chattogram,Bangladesh,CSTU,NaN,A+,Pass,Fail,Ziaur
16,16,16,16,16,PH1017,Afsana Mimi,90.0,90.0,93.0,Completed,2025-09-01,Mr. Karim,Dhaka,Bangladesh,CSTU,273.0,A,Pass,Fail,Afsana
17,17,17,17,17,PH1018,Babul Ahmed,88.0,88.0,85.0,Completed,2025-09-05,Ms. Salma,Sylhet,Bangladesh,CSTU,261.0,A,Pass,Fail,Babul
18,18,18,18,18,PH1019,Faria Rahman,NaN,NaN,NaN,Not Started,2025-09-15,Mr. David,Chattogram,Bangladesh,CSTU,NaN,A,Pass,Fail,Faria
19,19,19,19,19,PH1020,Nasir Khan,86.0,86.0,89.0,Completed,2025-10-02,Ms. Salma,Dhaka,Bangladesh,CSTU,261.0,A,Pass,Fail,Nasir

In [13]:
#adding Data Structure Marks,Algorithm Marks and Python Marks that name total mark

df2["Total Mark"]=df2["Data Structure Marks"]+df2["Algorithm Marks"]+df2["Python Marks"]
df2

,Unnamed: 0.3,Unnamed: 0.2,Unnamed: 0.1,Unnamed: 0,StudentID,FullName,Data Structure Marks,Algorithm Marks,Python Marks,CompletionStatus,EnrollmentDate,Instructor,Location,Country,University,Total Mark,DSA GPA,DSA PASS,pass in Python,Last name
0,0,0,0,0,PH1001,Alif Rahman,85.0,85.0,88.0,Completed,2024-01-15,Mr. Karim,Dhaka,Bangladesh,CSTU,258.0,A,Pass,Fail,Alif
1,1,1,1,1,PH1002,Fatima Akhter,92.0,92.0,NaN,In Progress,2024-01-20,Ms. Salma,Chattogram,Bangladesh,CSTU,NaN,A+,Pass,Fail,Fatima
2,2,2,2,2,PH1003,Imran Hossain,88.0,88.0,85.0,Completed,2024-02-10,Mr. Karim,Dhaka,Bangladesh,CSTU,261.0,A,Pass,Fail,Imran
3,3,3,3,3,PH1004,Jannatul Ferdous,78.0,78.0,82.0,Completed,2024-02-12,Ms. Salma,Sylhet,Bangladesh,CSTU,238.0,A,Pass,Fail,Jannatul
4,4,4,4,4,PH1005,Kamal Uddin,NaN,NaN,95.0,In Progress,2024-03-05,Mr. Karim,Chattogram,Bangladesh,CSTU,NaN,A,Pass,Fail,Kamal
5,5,5,5,5,PH1006,Laila Begum,75.0,75.0,78.0,Completed,2024-03-08,Ms. Salma,Rajshahi,Bangladesh,CSTU,228.0,A,Pass,Pass,Laila
6,6,6,6,6,PH1007,Mahmudul Hasan,80.0,80.0,NaN,In Progress,2024-04-01,Mr. Karim,Dhaka,Bangladesh,CSTU,NaN,A,Pass,Fail,Mahmudul
7,7,7,7,7,PH1008,Nadia Islam,81.0,81.0,85.0,Completed,2024-04-22,Ms. Salma,Chattogram,Bangladesh,CSTU,247.0,A,Pass,Fail,Nadia
8,8,8,8,8,PH1009,Omar Faruq,72.0,72.0,76.0,Completed,2024-05-16,Mr. David,Dhaka,Bangladesh,CSTU,220.0,A,Pass,Pass,Omar
9,9,9,9,9,PH1010,Priya Sharma,89.0,89.0,88.0,Completed,2024-05-20,Ms. Salma,Sylhet,Bangladesh,CSTU,266.0,A,Pass,Fail,Priya
10,10,10,10,10,PH1011,Rahim Sheikh,NaN,NaN,91.0,In Progress,2024-06-11,Mr. Karim,Khulna,Bangladesh,CSTU,NaN,A,Pass,Fail,Rahim
11,11,11,11,11,PH1012,Sadia Chowdhury,85.0,85.0,87.0,Completed,2024-06-14,Ms. Salma,Chattogram,Bangladesh,CSTU,257.0,A,Pass,Fail,Sadia
12,12,12,12,12,PH1013,Tanvir Ahmed,75.0,75.0,79.0,Completed,2024-07-02,Mr. David,Dhaka,Bangladesh,CSTU,229.0,A,Pass,Pass,Tanvir
13,13,13,13,13,PH1014,Urmi Akter,NaN,NaN,NaN,Not Started,2024-07-09,Ms. Salma,Rajshahi,Bangladesh,CSTU,NaN,A,Pass,Fail,Urmi
14,14,14,14,14,PH1015,Wahiduzzaman,86.0,86.0,84.0,Completed,2024-08-18,Mr. Karim,Dhaka,Bangladesh,CSTU,256.0,A,Pass,Fail,Wahiduzzaman
15,15,15,15,15,PH1016,Ziaur Rahman,94.0,94.0,NaN,In Progress,2024-08-21,Ms. Salma,Chattogram,Bangladesh,CSTU,NaN,A+,Pass,Fail,Ziaur
16,16,16,16,16,PH1017,Afsana Mimi,90.0,90.0,93.0,Completed,2025-09-01,Mr. Karim,Dhaka,Bangladesh,CSTU,273.0,A,Pass,Fail,Afsana
17,17,17,17,17,PH1018,Babul Ahmed,88.0,88.0,85.0,Completed,2025-09-05,Ms. Salma,Sylhet,Bangladesh,CSTU,261.0,A,Pass,Fail,Babul
18,18,18,18,18,PH1019,Faria Rahman,NaN,NaN,NaN,Not Started,2025-09-15,Mr. David,Chattogram,Bangladesh,CSTU,NaN,A,Pass,Fail,Faria
19,19,19,19,19,PH1020,Nasir Khan,86.0,86.0,89.0,Completed,2025-10-02,Ms. Salma,Dhaka,Bangladesh,CSTU,261.0,A,Pass,Fail,Nasir

In [14]:
#if  Data Structure Marks large 90 get A+ or A
import numpy as  np
df2["DSA GPA"]=np.where(df2["Data Structure Marks"]>90,'A+','A')
df2

,Unnamed: 0.3,Unnamed: 0.2,Unnamed: 0.1,Unnamed: 0,StudentID,FullName,Data Structure Marks,Algorithm Marks,Python Marks,CompletionStatus,EnrollmentDate,Instructor,Location,Country,University,Total Mark,DSA GPA,DSA PASS,pass in Python,Last name
0,0,0,0,0,PH1001,Alif Rahman,85.0,85.0,88.0,Completed,2024-01-15,Mr. Karim,Dhaka,Bangladesh,CSTU,258.0,A,Pass,Fail,Alif
1,1,1,1,1,PH1002,Fatima Akhter,92.0,92.0,NaN,In Progress,2024-01-20,Ms. Salma,Chattogram,Bangladesh,CSTU,NaN,A+,Pass,Fail,Fatima
2,2,2,2,2,PH1003,Imran Hossain,88.0,88.0,85.0,Completed,2024-02-10,Mr. Karim,Dhaka,Bangladesh,CSTU,261.0,A,Pass,Fail,Imran
3,3,3,3,3,PH1004,Jannatul Ferdous,78.0,78.0,82.0,Completed,2024-02-12,Ms. Salma,Sylhet,Bangladesh,CSTU,238.0,A,Pass,Fail,Jannatul
4,4,4,4,4,PH1005,Kamal Uddin,NaN,NaN,95.0,In Progress,2024-03-05,Mr. Karim,Chattogram,Bangladesh,CSTU,NaN,A,Pass,Fail,Kamal
5,5,5,5,5,PH1006,Laila Begum,75.0,75.0,78.0,Completed,2024-03-08,Ms. Salma,Rajshahi,Bangladesh,CSTU,228.0,A,Pass,Pass,Laila
6,6,6,6,6,PH1007,Mahmudul Hasan,80.0,80.0,NaN,In Progress,2024-04-01,Mr. Karim,Dhaka,Bangladesh,CSTU,NaN,A,Pass,Fail,Mahmudul
7,7,7,7,7,PH1008,Nadia Islam,81.0,81.0,85.0,Completed,2024-04-22,Ms. Salma,Chattogram,Bangladesh,CSTU,247.0,A,Pass,Fail,Nadia
8,8,8,8,8,PH1009,Omar Faruq,72.0,72.0,76.0,Completed,2024-05-16,Mr. David,Dhaka,Bangladesh,CSTU,220.0,A,Pass,Pass,Omar
9,9,9,9,9,PH1010,Priya Sharma,89.0,89.0,88.0,Completed,2024-05-20,Ms. Salma,Sylhet,Bangladesh,CSTU,266.0,A,Pass,Fail,Priya
10,10,10,10,10,PH1011,Rahim Sheikh,NaN,NaN,91.0,In Progress,2024-06-11,Mr. Karim,Khulna,Bangladesh,CSTU,NaN,A,Pass,Fail,Rahim
11,11,11,11,11,PH1012,Sadia Chowdhury,85.0,85.0,87.0,Completed,2024-06-14,Ms. Salma,Chattogram,Bangladesh,CSTU,257.0,A,Pass,Fail,Sadia
12,12,12,12,12,PH1013,Tanvir Ahmed,75.0,75.0,79.0,Completed,2024-07-02,Mr. David,Dhaka,Bangladesh,CSTU,229.0,A,Pass,Pass,Tanvir
13,13,13,13,13,PH1014,Urmi Akter,NaN,NaN,NaN,Not Started,2024-07-09,Ms. Salma,Rajshahi,Bangladesh,CSTU,NaN,A,Pass,Fail,Urmi
14,14,14,14,14,PH1015,Wahiduzzaman,86.0,86.0,84.0,Completed,2024-08-18,Mr. Karim,Dhaka,Bangladesh,CSTU,256.0,A,Pass,Fail,Wahiduzzaman
15,15,15,15,15,PH1016,Ziaur Rahman,94.0,94.0,NaN,In Progress,2024-08-21,Ms. Salma,Chattogram,Bangladesh,CSTU,NaN,A+,Pass,Fail,Ziaur
16,16,16,16,16,PH1017,Afsana Mimi,90.0,90.0,93.0,Completed,2025-09-01,Mr. Karim,Dhaka,Bangladesh,CSTU,273.0,A,Pass,Fail,Afsana
17,17,17,17,17,PH1018,Babul Ahmed,88.0,88.0,85.0,Completed,2025-09-05,Ms. Salma,Sylhet,Bangladesh,CSTU,261.0,A,Pass,Fail,Babul
18,18,18,18,18,PH1019,Faria Rahman,NaN,NaN,NaN,Not Started,2025-09-15,Mr. David,Chattogram,Bangladesh,CSTU,NaN,A,Pass,Fail,Faria
19,19,19,19,19,PH1020,Nasir Khan,86.0,86.0,89.0,Completed,2025-10-02,Ms. Salma,Dhaka,Bangladesh,CSTU,261.0,A,Pass,Fail,Nasir

In [15]:
#DSA pass if mark large than 70
df2["DSA PASS"]=np.where(df2["Data Structure Marks"]<70,'Fail','Pass')
df2

,Unnamed: 0.3,Unnamed: 0.2,Unnamed: 0.1,Unnamed: 0,StudentID,FullName,Data Structure Marks,Algorithm Marks,Python Marks,CompletionStatus,EnrollmentDate,Instructor,Location,Country,University,Total Mark,DSA GPA,DSA PASS,pass in Python,Last name
0,0,0,0,0,PH1001,Alif Rahman,85.0,85.0,88.0,Completed,2024-01-15,Mr. Karim,Dhaka,Bangladesh,CSTU,258.0,A,Pass,Fail,Alif
1,1,1,1,1,PH1002,Fatima Akhter,92.0,92.0,NaN,In Progress,2024-01-20,Ms. Salma,Chattogram,Bangladesh,CSTU,NaN,A+,Pass,Fail,Fatima
2,2,2,2,2,PH1003,Imran Hossain,88.0,88.0,85.0,Completed,2024-02-10,Mr. Karim,Dhaka,Bangladesh,CSTU,261.0,A,Pass,Fail,Imran
3,3,3,3,3,PH1004,Jannatul Ferdous,78.0,78.0,82.0,Completed,2024-02-12,Ms. Salma,Sylhet,Bangladesh,CSTU,238.0,A,Pass,Fail,Jannatul
4,4,4,4,4,PH1005,Kamal Uddin,NaN,NaN,95.0,In Progress,2024-03-05,Mr. Karim,Chattogram,Bangladesh,CSTU,NaN,A,Pass,Fail,Kamal
5,5,5,5,5,PH1006,Laila Begum,75.0,75.0,78.0,Completed,2024-03-08,Ms. Salma,Rajshahi,Bangladesh,CSTU,228.0,A,Pass,Pass,Laila
6,6,6,6,6,PH1007,Mahmudul Hasan,80.0,80.0,NaN,In Progress,2024-04-01,Mr. Karim,Dhaka,Bangladesh,CSTU,NaN,A,Pass,Fail,Mahmudul
7,7,7,7,7,PH1008,Nadia Islam,81.0,81.0,85.0,Completed,2024-04-22,Ms. Salma,Chattogram,Bangladesh,CSTU,247.0,A,Pass,Fail,Nadia
8,8,8,8,8,PH1009,Omar Faruq,72.0,72.0,76.0,Completed,2024-05-16,Mr. David,Dhaka,Bangladesh,CSTU,220.0,A,Pass,Pass,Omar
9,9,9,9,9,PH1010,Priya Sharma,89.0,89.0,88.0,Completed,2024-05-20,Ms. Salma,Sylhet,Bangladesh,CSTU,266.0,A,Pass,Fail,Priya
10,10,10,10,10,PH1011,Rahim Sheikh,NaN,NaN,91.0,In Progress,2024-06-11,Mr. Karim,Khulna,Bangladesh,CSTU,NaN,A,Pass,Fail,Rahim
11,11,11,11,11,PH1012,Sadia Chowdhury,85.0,85.0,87.0,Completed,2024-06-14,Ms. Salma,Chattogram,Bangladesh,CSTU,257.0,A,Pass,Fail,Sadia
12,12,12,12,12,PH1013,Tanvir Ahmed,75.0,75.0,79.0,Completed,2024-07-02,Mr. David,Dhaka,Bangladesh,CSTU,229.0,A,Pass,Pass,Tanvir
13,13,13,13,13,PH1014,Urmi Akter,NaN,NaN,NaN,Not Started,2024-07-09,Ms. Salma,Rajshahi,Bangladesh,CSTU,NaN,A,Pass,Fail,Urmi
14,14,14,14,14,PH1015,Wahiduzzaman,86.0,86.0,84.0,Completed,2024-08-18,Mr. Karim,Dhaka,Bangladesh,CSTU,256.0,A,Pass,Fail,Wahiduzzaman
15,15,15,15,15,PH1016,Ziaur Rahman,94.0,94.0,NaN,In Progress,2024-08-21,Ms. Salma,Chattogram,Bangladesh,CSTU,NaN,A+,Pass,Fail,Ziaur
16,16,16,16,16,PH1017,Afsana Mimi,90.0,90.0,93.0,Completed,2025-09-01,Mr. Karim,Dhaka,Bangladesh,CSTU,273.0,A,Pass,Fail,Afsana
17,17,17,17,17,PH1018,Babul Ahmed,88.0,88.0,85.0,Completed,2025-09-05,Ms. Salma,Sylhet,Bangladesh,CSTU,261.0,A,Pass,Fail,Babul
18,18,18,18,18,PH1019,Faria Rahman,NaN,NaN,NaN,Not Started,2025-09-15,Mr. David,Chattogram,Bangladesh,CSTU,NaN,A,Pass,Fail,Faria
19,19,19,19,19,PH1020,Nasir Khan,86.0,86.0,89.0,Completed,2025-10-02,Ms. Salma,Dhaka,Bangladesh,CSTU,261.0,A,Pass,Fail,Nasir

In [16]:
# pass Python course  if Python Marks large than 70
df2["pass in Python"]=np.where(df2["Python Marks"]<80,'Pass','Fail')
df2['Python Marks']

0     88.0
1      NaN
2     85.0
3     82.0
4     95.0
5     78.0
6      NaN
7     85.0
8     76.0
9     88.0
10    91.0
11    87.0
12    79.0
13     NaN
14    84.0
15     NaN
16    93.0
17    85.0
18     NaN
19    89.0
Name: Python Marks, dtype: float64

In [17]:
df2["Last name"]=df2["FullName"].str.split(' ').str[0]
df2

,Unnamed: 0.3,Unnamed: 0.2,Unnamed: 0.1,Unnamed: 0,StudentID,FullName,Data Structure Marks,Algorithm Marks,Python Marks,CompletionStatus,EnrollmentDate,Instructor,Location,Country,University,Total Mark,DSA GPA,DSA PASS,pass in Python,Last name
0,0,0,0,0,PH1001,Alif Rahman,85.0,85.0,88.0,Completed,2024-01-15,Mr. Karim,Dhaka,Bangladesh,CSTU,258.0,A,Pass,Fail,Alif
1,1,1,1,1,PH1002,Fatima Akhter,92.0,92.0,NaN,In Progress,2024-01-20,Ms. Salma,Chattogram,Bangladesh,CSTU,NaN,A+,Pass,Fail,Fatima
2,2,2,2,2,PH1003,Imran Hossain,88.0,88.0,85.0,Completed,2024-02-10,Mr. Karim,Dhaka,Bangladesh,CSTU,261.0,A,Pass,Fail,Imran
3,3,3,3,3,PH1004,Jannatul Ferdous,78.0,78.0,82.0,Completed,2024-02-12,Ms. Salma,Sylhet,Bangladesh,CSTU,238.0,A,Pass,Fail,Jannatul
4,4,4,4,4,PH1005,Kamal Uddin,NaN,NaN,95.0,In Progress,2024-03-05,Mr. Karim,Chattogram,Bangladesh,CSTU,NaN,A,Pass,Fail,Kamal
5,5,5,5,5,PH1006,Laila Begum,75.0,75.0,78.0,Completed,2024-03-08,Ms. Salma,Rajshahi,Bangladesh,CSTU,228.0,A,Pass,Pass,Laila
6,6,6,6,6,PH1007,Mahmudul Hasan,80.0,80.0,NaN,In Progress,2024-04-01,Mr. Karim,Dhaka,Bangladesh,CSTU,NaN,A,Pass,Fail,Mahmudul
7,7,7,7,7,PH1008,Nadia Islam,81.0,81.0,85.0,Completed,2024-04-22,Ms. Salma,Chattogram,Bangladesh,CSTU,247.0,A,Pass,Fail,Nadia
8,8,8,8,8,PH1009,Omar Faruq,72.0,72.0,76.0,Completed,2024-05-16,Mr. David,Dhaka,Bangladesh,CSTU,220.0,A,Pass,Pass,Omar
9,9,9,9,9,PH1010,Priya Sharma,89.0,89.0,88.0,Completed,2024-05-20,Ms. Salma,Sylhet,Bangladesh,CSTU,266.0,A,Pass,Fail,Priya
10,10,10,10,10,PH1011,Rahim Sheikh,NaN,NaN,91.0,In Progress,2024-06-11,Mr. Karim,Khulna,Bangladesh,CSTU,NaN,A,Pass,Fail,Rahim
11,11,11,11,11,PH1012,Sadia Chowdhury,85.0,85.0,87.0,Completed,2024-06-14,Ms. Salma,Chattogram,Bangladesh,CSTU,257.0,A,Pass,Fail,Sadia
12,12,12,12,12,PH1013,Tanvir Ahmed,75.0,75.0,79.0,Completed,2024-07-02,Mr. David,Dhaka,Bangladesh,CSTU,229.0,A,Pass,Pass,Tanvir
13,13,13,13,13,PH1014,Urmi Akter,NaN,NaN,NaN,Not Started,2024-07-09,Ms. Salma,Rajshahi,Bangladesh,CSTU,NaN,A,Pass,Fail,Urmi
14,14,14,14,14,PH1015,Wahiduzzaman,86.0,86.0,84.0,Completed,2024-08-18,Mr. Karim,Dhaka,Bangladesh,CSTU,256.0,A,Pass,Fail,Wahiduzzaman
15,15,15,15,15,PH1016,Ziaur Rahman,94.0,94.0,NaN,In Progress,2024-08-21,Ms. Salma,Chattogram,Bangladesh,CSTU,NaN,A+,Pass,Fail,Ziaur
16,16,16,16,16,PH1017,Afsana Mimi,90.0,90.0,93.0,Completed,2025-09-01,Mr. Karim,Dhaka,Bangladesh,CSTU,273.0,A,Pass,Fail,Afsana
17,17,17,17,17,PH1018,Babul Ahmed,88.0,88.0,85.0,Completed,2025-09-05,Ms. Salma,Sylhet,Bangladesh,CSTU,261.0,A,Pass,Fail,Babul
18,18,18,18,18,PH1019,Faria Rahman,NaN,NaN,NaN,Not Started,2025-09-15,Mr. David,Chattogram,Bangladesh,CSTU,NaN,A,Pass,Fail,Faria
19,19,19,19,19,PH1020,Nasir Khan,86.0,86.0,89.0,Completed,2025-10-02,Ms. Salma,Dhaka,Bangladesh,CSTU,261.0,A,Pass,Fail,Nasir

In [18]:
df2

,Unnamed: 0.3,Unnamed: 0.2,Unnamed: 0.1,Unnamed: 0,StudentID,FullName,Data Structure Marks,Algorithm Marks,Python Marks,CompletionStatus,EnrollmentDate,Instructor,Location,Country,University,Total Mark,DSA GPA,DSA PASS,pass in Python,Last name
0,0,0,0,0,PH1001,Alif Rahman,85.0,85.0,88.0,Completed,2024-01-15,Mr. Karim,Dhaka,Bangladesh,CSTU,258.0,A,Pass,Fail,Alif
1,1,1,1,1,PH1002,Fatima Akhter,92.0,92.0,NaN,In Progress,2024-01-20,Ms. Salma,Chattogram,Bangladesh,CSTU,NaN,A+,Pass,Fail,Fatima
2,2,2,2,2,PH1003,Imran Hossain,88.0,88.0,85.0,Completed,2024-02-10,Mr. Karim,Dhaka,Bangladesh,CSTU,261.0,A,Pass,Fail,Imran
3,3,3,3,3,PH1004,Jannatul Ferdous,78.0,78.0,82.0,Completed,2024-02-12,Ms. Salma,Sylhet,Bangladesh,CSTU,238.0,A,Pass,Fail,Jannatul
4,4,4,4,4,PH1005,Kamal Uddin,NaN,NaN,95.0,In Progress,2024-03-05,Mr. Karim,Chattogram,Bangladesh,CSTU,NaN,A,Pass,Fail,Kamal
5,5,5,5,5,PH1006,Laila Begum,75.0,75.0,78.0,Completed,2024-03-08,Ms. Salma,Rajshahi,Bangladesh,CSTU,228.0,A,Pass,Pass,Laila
6,6,6,6,6,PH1007,Mahmudul Hasan,80.0,80.0,NaN,In Progress,2024-04-01,Mr. Karim,Dhaka,Bangladesh,CSTU,NaN,A,Pass,Fail,Mahmudul
7,7,7,7,7,PH1008,Nadia Islam,81.0,81.0,85.0,Completed,2024-04-22,Ms. Salma,Chattogram,Bangladesh,CSTU,247.0,A,Pass,Fail,Nadia
8,8,8,8,8,PH1009,Omar Faruq,72.0,72.0,76.0,Completed,2024-05-16,Mr. David,Dhaka,Bangladesh,CSTU,220.0,A,Pass,Pass,Omar
9,9,9,9,9,PH1010,Priya Sharma,89.0,89.0,88.0,Completed,2024-05-20,Ms. Salma,Sylhet,Bangladesh,CSTU,266.0,A,Pass,Fail,Priya
10,10,10,10,10,PH1011,Rahim Sheikh,NaN,NaN,91.0,In Progress,2024-06-11,Mr. Karim,Khulna,Bangladesh,CSTU,NaN,A,Pass,Fail,Rahim
11,11,11,11,11,PH1012,Sadia Chowdhury,85.0,85.0,87.0,Completed,2024-06-14,Ms. Salma,Chattogram,Bangladesh,CSTU,257.0,A,Pass,Fail,Sadia
12,12,12,12,12,PH1013,Tanvir Ahmed,75.0,75.0,79.0,Completed,2024-07-02,Mr. David,Dhaka,Bangladesh,CSTU,229.0,A,Pass,Pass,Tanvir
13,13,13,13,13,PH1014,Urmi Akter,NaN,NaN,NaN,Not Started,2024-07-09,Ms. Salma,Rajshahi,Bangladesh,CSTU,NaN,A,Pass,Fail,Urmi
14,14,14,14,14,PH1015,Wahiduzzaman,86.0,86.0,84.0,Completed,2024-08-18,Mr. Karim,Dhaka,Bangladesh,CSTU,256.0,A,Pass,Fail,Wahiduzzaman
15,15,15,15,15,PH1016,Ziaur Rahman,94.0,94.0,NaN,In Progress,2024-08-21,Ms. Salma,Chattogram,Bangladesh,CSTU,NaN,A+,Pass,Fail,Ziaur
16,16,16,16,16,PH1017,Afsana Mimi,90.0,90.0,93.0,Completed,2025-09-01,Mr. Karim,Dhaka,Bangladesh,CSTU,273.0,A,Pass,Fail,Afsana
17,17,17,17,17,PH1018,Babul Ahmed,88.0,88.0,85.0,Completed,2025-09-05,Ms. Salma,Sylhet,Bangladesh,CSTU,261.0,A,Pass,Fail,Babul
18,18,18,18,18,PH1019,Faria Rahman,NaN,NaN,NaN,Not Started,2025-09-15,Mr. David,Chattogram,Bangladesh,CSTU,NaN,A,Pass,Fail,Faria
19,19,19,19,19,PH1020,Nasir Khan,86.0,86.0,89.0,Completed,2025-10-02,Ms. Salma,Dhaka,Bangladesh,CSTU,261.0,A,Pass,Fail,Nasir

In [19]:
df2=pd.read_csv('student_data.csv')
df2

,Unnamed: 0.3,Unnamed: 0.2,Unnamed: 0.1,Unnamed: 0,StudentID,FullName,Data Structure Marks,Algorithm Marks,Python Marks,CompletionStatus,EnrollmentDate,Instructor,Location,Country,University,Total Mark,DSA GPA,DSA PASS,pass in Python,Last name
0,0,0,0,0,PH1001,Alif Rahman,85.0,85.0,88.0,Completed,2024-01-15,Mr. Karim,Dhaka,Bangladesh,CSTU,258.0,A,Pass,Fail,Alif
1,1,1,1,1,PH1002,Fatima Akhter,92.0,92.0,NaN,In Progress,2024-01-20,Ms. Salma,Chattogram,Bangladesh,CSTU,NaN,A+,Pass,Fail,Fatima
2,2,2,2,2,PH1003,Imran Hossain,88.0,88.0,85.0,Completed,2024-02-10,Mr. Karim,Dhaka,Bangladesh,CSTU,261.0,A,Pass,Fail,Imran
3,3,3,3,3,PH1004,Jannatul Ferdous,78.0,78.0,82.0,Completed,2024-02-12,Ms. Salma,Sylhet,Bangladesh,CSTU,238.0,A,Pass,Fail,Jannatul
4,4,4,4,4,PH1005,Kamal Uddin,NaN,NaN,95.0,In Progress,2024-03-05,Mr. Karim,Chattogram,Bangladesh,CSTU,NaN,A,Pass,Fail,Kamal
5,5,5,5,5,PH1006,Laila Begum,75.0,75.0,78.0,Completed,2024-03-08,Ms. Salma,Rajshahi,Bangladesh,CSTU,228.0,A,Pass,Pass,Laila
6,6,6,6,6,PH1007,Mahmudul Hasan,80.0,80.0,NaN,In Progress,2024-04-01,Mr. Karim,Dhaka,Bangladesh,CSTU,NaN,A,Pass,Fail,Mahmudul
7,7,7,7,7,PH1008,Nadia Islam,81.0,81.0,85.0,Completed,2024-04-22,Ms. Salma,Chattogram,Bangladesh,CSTU,247.0,A,Pass,Fail,Nadia
8,8,8,8,8,PH1009,Omar Faruq,72.0,72.0,76.0,Completed,2024-05-16,Mr. David,Dhaka,Bangladesh,CSTU,220.0,A,Pass,Pass,Omar
9,9,9,9,9,PH1010,Priya Sharma,89.0,89.0,88.0,Completed,2024-05-20,Ms. Salma,Sylhet,Bangladesh,CSTU,266.0,A,Pass,Fail,Priya
10,10,10,10,10,PH1011,Rahim Sheikh,NaN,NaN,91.0,In Progress,2024-06-11,Mr. Karim,Khulna,Bangladesh,CSTU,NaN,A,Pass,Fail,Rahim
11,11,11,11,11,PH1012,Sadia Chowdhury,85.0,85.0,87.0,Completed,2024-06-14,Ms. Salma,Chattogram,Bangladesh,CSTU,257.0,A,Pass,Fail,Sadia
12,12,12,12,12,PH1013,Tanvir Ahmed,75.0,75.0,79.0,Completed,2024-07-02,Mr. David,Dhaka,Bangladesh,CSTU,229.0,A,Pass,Pass,Tanvir
13,13,13,13,13,PH1014,Urmi Akter,NaN,NaN,NaN,Not Started,2024-07-09,Ms. Salma,Rajshahi,Bangladesh,CSTU,NaN,A,Pass,Fail,Urmi
14,14,14,14,14,PH1015,Wahiduzzaman,86.0,86.0,84.0,Completed,2024-08-18,Mr. Karim,Dhaka,Bangladesh,CSTU,256.0,A,Pass,Fail,Wahiduzzaman
15,15,15,15,15,PH1016,Ziaur Rahman,94.0,94.0,NaN,In Progress,2024-08-21,Ms. Salma,Chattogram,Bangladesh,CSTU,NaN,A+,Pass,Fail,Ziaur
16,16,16,16,16,PH1017,Afsana Mimi,90.0,90.0,93.0,Completed,2025-09-01,Mr. Karim,Dhaka,Bangladesh,CSTU,273.0,A,Pass,Fail,Afsana
17,17,17,17,17,PH1018,Babul Ahmed,88.0,88.0,85.0,Completed,2025-09-05,Ms. Salma,Sylhet,Bangladesh,CSTU,261.0,A,Pass,Fail,Babul
18,18,18,18,18,PH1019,Faria Rahman,NaN,NaN,NaN,Not Started,2025-09-15,Mr. David,Chattogram,Bangladesh,CSTU,NaN,A,Pass,Fail,Faria
19,19,19,19,19,PH1020,Nasir Khan,86.0,86.0,89.0,Completed,2025-10-02,Ms. Salma,Dhaka,Bangladesh,CSTU,261.0,A,Pass,Fail,Nasir

In [20]:
df2.to_csv('student_data.csv')
df2

,Unnamed: 0.3,Unnamed: 0.2,Unnamed: 0.1,Unnamed: 0,StudentID,FullName,Data Structure Marks,Algorithm Marks,Python Marks,CompletionStatus,EnrollmentDate,Instructor,Location,Country,University,Total Mark,DSA GPA,DSA PASS,pass in Python,Last name
0,0,0,0,0,PH1001,Alif Rahman,85.0,85.0,88.0,Completed,2024-01-15,Mr. Karim,Dhaka,Bangladesh,CSTU,258.0,A,Pass,Fail,Alif
1,1,1,1,1,PH1002,Fatima Akhter,92.0,92.0,NaN,In Progress,2024-01-20,Ms. Salma,Chattogram,Bangladesh,CSTU,NaN,A+,Pass,Fail,Fatima
2,2,2,2,2,PH1003,Imran Hossain,88.0,88.0,85.0,Completed,2024-02-10,Mr. Karim,Dhaka,Bangladesh,CSTU,261.0,A,Pass,Fail,Imran
3,3,3,3,3,PH1004,Jannatul Ferdous,78.0,78.0,82.0,Completed,2024-02-12,Ms. Salma,Sylhet,Bangladesh,CSTU,238.0,A,Pass,Fail,Jannatul
4,4,4,4,4,PH1005,Kamal Uddin,NaN,NaN,95.0,In Progress,2024-03-05,Mr. Karim,Chattogram,Bangladesh,CSTU,NaN,A,Pass,Fail,Kamal
5,5,5,5,5,PH1006,Laila Begum,75.0,75.0,78.0,Completed,2024-03-08,Ms. Salma,Rajshahi,Bangladesh,CSTU,228.0,A,Pass,Pass,Laila
6,6,6,6,6,PH1007,Mahmudul Hasan,80.0,80.0,NaN,In Progress,2024-04-01,Mr. Karim,Dhaka,Bangladesh,CSTU,NaN,A,Pass,Fail,Mahmudul
7,7,7,7,7,PH1008,Nadia Islam,81.0,81.0,85.0,Completed,2024-04-22,Ms. Salma,Chattogram,Bangladesh,CSTU,247.0,A,Pass,Fail,Nadia
8,8,8,8,8,PH1009,Omar Faruq,72.0,72.0,76.0,Completed,2024-05-16,Mr. David,Dhaka,Bangladesh,CSTU,220.0,A,Pass,Pass,Omar
9,9,9,9,9,PH1010,Priya Sharma,89.0,89.0,88.0,Completed,2024-05-20,Ms. Salma,Sylhet,Bangladesh,CSTU,266.0,A,Pass,Fail,Priya
10,10,10,10,10,PH1011,Rahim Sheikh,NaN,NaN,91.0,In Progress,2024-06-11,Mr. Karim,Khulna,Bangladesh,CSTU,NaN,A,Pass,Fail,Rahim
11,11,11,11,11,PH1012,Sadia Chowdhury,85.0,85.0,87.0,Completed,2024-06-14,Ms. Salma,Chattogram,Bangladesh,CSTU,257.0,A,Pass,Fail,Sadia
12,12,12,12,12,PH1013,Tanvir Ahmed,75.0,75.0,79.0,Completed,2024-07-02,Mr. David,Dhaka,Bangladesh,CSTU,229.0,A,Pass,Pass,Tanvir
13,13,13,13,13,PH1014,Urmi Akter,NaN,NaN,NaN,Not Started,2024-07-09,Ms. Salma,Rajshahi,Bangladesh,CSTU,NaN,A,Pass,Fail,Urmi
14,14,14,14,14,PH1015,Wahiduzzaman,86.0,86.0,84.0,Completed,2024-08-18,Mr. Karim,Dhaka,Bangladesh,CSTU,256.0,A,Pass,Fail,Wahiduzzaman
15,15,15,15,15,PH1016,Ziaur Rahman,94.0,94.0,NaN,In Progress,2024-08-21,Ms. Salma,Chattogram,Bangladesh,CSTU,NaN,A+,Pass,Fail,Ziaur
16,16,16,16,16,PH1017,Afsana Mimi,90.0,90.0,93.0,Completed,2025-09-01,Mr. Karim,Dhaka,Bangladesh,CSTU,273.0,A,Pass,Fail,Afsana
17,17,17,17,17,PH1018,Babul Ahmed,88.0,88.0,85.0,Completed,2025-09-05,Ms. Salma,Sylhet,Bangladesh,CSTU,261.0,A,Pass,Fail,Babul
18,18,18,18,18,PH1019,Faria Rahman,NaN,NaN,NaN,Not Started,2025-09-15,Mr. David,Chattogram,Bangladesh,CSTU,NaN,A,Pass,Fail,Faria
19,19,19,19,19,PH1020,Nasir Khan,86.0,86.0,89.0,Completed,2025-10-02,Ms. Salma,Dhaka,Bangladesh,CSTU,261.0,A,Pass,Fail,Nasir

In [21]:
import pandas as pd
data={
    "Name":["Alice" ,"Bob","Chalie","Alice","Devid","Bob"],
    "City":["New York","Los Angeles","Newark","Boston","New Delhi","Chicago"],
    "score":[85,90,78,92,88,95]         
}
df3=pd.DataFrame(data)
df3

     Name         City  score
0   Alice     New York     85
1     Bob  Los Angeles     90
2  Chalie       Newark     78
3   Alice       Boston     92
4   Devid    New Delhi     88
5     Bob      Chicago     95

In [22]:
df2["Data Structure Marks"].unique()

array([85., 92., 88., 78., nan, 75., 80., 81., 72., 89., 86., 94., 90.])

In [23]:
length=len(df2["Data Structure Marks"].unique())

In [24]:
df2.nunique()

Unnamed: 0.3            20
Unnamed: 0.2            20
Unnamed: 0.1            20
Unnamed: 0              20
StudentID               20
FullName                20
Data Structure Marks    12
Algorithm Marks         12
Python Marks            12
CompletionStatus         3
EnrollmentDate          20
Instructor               3
Location                 5
Country                  1
University               1
Total Mark              11
DSA GPA                  2
DSA PASS                 1
pass in Python           2
Last name               20
dtype: int64

In [25]:
df2.isnull()

,Unnamed: 0.3,Unnamed: 0.2,Unnamed: 0.1,Unnamed: 0,StudentID,FullName,Data Structure Marks,Algorithm Marks,Python Marks,CompletionStatus,EnrollmentDate,Instructor,Location,Country,University,Total Mark,DSA GPA,DSA PASS,pass in Python,Last name
0,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False
1,False,False,False,False,False,False,False,False,True,False,False,False,False,False,False,True,False,False,False,False
2,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False
3,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False
4,False,False,False,False,False,False,True,True,False,False,False,False,False,False,False,True,False,False,False,False
5,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False
6,False,False,False,False,False,False,False,False,True,False,False,False,False,False,False,True,False,False,False,False
7,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False
8,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False
9,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False
10,False,False,False,False,False,False,True,True,False,False,False,False,False,False,False,True,False,False,False,False
11,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False
12,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False
13,False,False,False,False,False,False,True,True,True,False,False,False,False,False,False,True,False,False,False,False
14,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False
15,False,False,False,False,False,False,False,False,True,False,False,False,False,False,False,True,False,False,False,False
16,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False
17,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False
18,False,False,False,False,False,False,True,True,True,False,False,False,False,False,False,True,False,False,False,False
19,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False

In [26]:
df2['Data Structure Marks'].isnull()

0     False
1     False
2     False
3     False
4      True
5     False
6     False
7     False
8     False
9     False
10     True
11    False
12    False
13     True
14    False
15    False
16    False
17    False
18     True
19    False
Name: Data Structure Marks, dtype: bool

In [27]:
df2['Data Structure Marks'].notnull()

0      True
1      True
2      True
3      True
4     False
5      True
6      True
7      True
8      True
9      True
10    False
11     True
12     True
13    False
14     True
15     True
16     True
17     True
18    False
19     True
Name: Data Structure Marks, dtype: bool

In [28]:
df2['Data Structure Marks'].hasnans

True

In [29]:
df2['StudentID'].hasnans

False

#Handling Duplicates Values

In [30]:
import pandas as pd
data={
    "Name":["Alice","Bob","Charlie","Alice","David","Bob"],
    "City":["New York","London","Paris","New York","Tokyo","London"],
    "Score":[85,90,78,70,95,90]
}
df4=pd.DataFrame(data)
df4

      Name      City  Score
0    Alice  New York     85
1      Bob    London     90
2  Charlie     Paris     78
3    Alice  New York     70
4    David     Tokyo     95
5      Bob    London     90

In [31]:
df4.duplicated().sum()

np.int64(1)

In [32]:
df4.drop_duplicates() #that is copy

      Name      City  Score
0    Alice  New York     85
1      Bob    London     90
2  Charlie     Paris     78
3    Alice  New York     70
4    David     Tokyo     95

In [33]:
df4.drop_duplicates(inplace=True)

In [34]:
df4

      Name      City  Score
0    Alice  New York     85
1      Bob    London     90
2  Charlie     Paris     78
3    Alice  New York     70
4    David     Tokyo     95

In [35]:
#delete duplicates according to City
df4.drop_duplicates(subset='City',keep='last')

      Name      City  Score
1      Bob    London     90
2  Charlie     Paris     78
3    Alice  New York     70
4    David     Tokyo     95

In [36]:
df2

,Unnamed: 0.3,Unnamed: 0.2,Unnamed: 0.1,Unnamed: 0,StudentID,FullName,Data Structure Marks,Algorithm Marks,Python Marks,CompletionStatus,EnrollmentDate,Instructor,Location,Country,University,Total Mark,DSA GPA,DSA PASS,pass in Python,Last name
0,0,0,0,0,PH1001,Alif Rahman,85.0,85.0,88.0,Completed,2024-01-15,Mr. Karim,Dhaka,Bangladesh,CSTU,258.0,A,Pass,Fail,Alif
1,1,1,1,1,PH1002,Fatima Akhter,92.0,92.0,NaN,In Progress,2024-01-20,Ms. Salma,Chattogram,Bangladesh,CSTU,NaN,A+,Pass,Fail,Fatima
2,2,2,2,2,PH1003,Imran Hossain,88.0,88.0,85.0,Completed,2024-02-10,Mr. Karim,Dhaka,Bangladesh,CSTU,261.0,A,Pass,Fail,Imran
3,3,3,3,3,PH1004,Jannatul Ferdous,78.0,78.0,82.0,Completed,2024-02-12,Ms. Salma,Sylhet,Bangladesh,CSTU,238.0,A,Pass,Fail,Jannatul
4,4,4,4,4,PH1005,Kamal Uddin,NaN,NaN,95.0,In Progress,2024-03-05,Mr. Karim,Chattogram,Bangladesh,CSTU,NaN,A,Pass,Fail,Kamal
5,5,5,5,5,PH1006,Laila Begum,75.0,75.0,78.0,Completed,2024-03-08,Ms. Salma,Rajshahi,Bangladesh,CSTU,228.0,A,Pass,Pass,Laila
6,6,6,6,6,PH1007,Mahmudul Hasan,80.0,80.0,NaN,In Progress,2024-04-01,Mr. Karim,Dhaka,Bangladesh,CSTU,NaN,A,Pass,Fail,Mahmudul
7,7,7,7,7,PH1008,Nadia Islam,81.0,81.0,85.0,Completed,2024-04-22,Ms. Salma,Chattogram,Bangladesh,CSTU,247.0,A,Pass,Fail,Nadia
8,8,8,8,8,PH1009,Omar Faruq,72.0,72.0,76.0,Completed,2024-05-16,Mr. David,Dhaka,Bangladesh,CSTU,220.0,A,Pass,Pass,Omar
9,9,9,9,9,PH1010,Priya Sharma,89.0,89.0,88.0,Completed,2024-05-20,Ms. Salma,Sylhet,Bangladesh,CSTU,266.0,A,Pass,Fail,Priya
10,10,10,10,10,PH1011,Rahim Sheikh,NaN,NaN,91.0,In Progress,2024-06-11,Mr. Karim,Khulna,Bangladesh,CSTU,NaN,A,Pass,Fail,Rahim
11,11,11,11,11,PH1012,Sadia Chowdhury,85.0,85.0,87.0,Completed,2024-06-14,Ms. Salma,Chattogram,Bangladesh,CSTU,257.0,A,Pass,Fail,Sadia
12,12,12,12,12,PH1013,Tanvir Ahmed,75.0,75.0,79.0,Completed,2024-07-02,Mr. David,Dhaka,Bangladesh,CSTU,229.0,A,Pass,Pass,Tanvir
13,13,13,13,13,PH1014,Urmi Akter,NaN,NaN,NaN,Not Started,2024-07-09,Ms. Salma,Rajshahi,Bangladesh,CSTU,NaN,A,Pass,Fail,Urmi
14,14,14,14,14,PH1015,Wahiduzzaman,86.0,86.0,84.0,Completed,2024-08-18,Mr. Karim,Dhaka,Bangladesh,CSTU,256.0,A,Pass,Fail,Wahiduzzaman
15,15,15,15,15,PH1016,Ziaur Rahman,94.0,94.0,NaN,In Progress,2024-08-21,Ms. Salma,Chattogram,Bangladesh,CSTU,NaN,A+,Pass,Fail,Ziaur
16,16,16,16,16,PH1017,Afsana Mimi,90.0,90.0,93.0,Completed,2025-09-01,Mr. Karim,Dhaka,Bangladesh,CSTU,273.0,A,Pass,Fail,Afsana
17,17,17,17,17,PH1018,Babul Ahmed,88.0,88.0,85.0,Completed,2025-09-05,Ms. Salma,Sylhet,Bangladesh,CSTU,261.0,A,Pass,Fail,Babul
18,18,18,18,18,PH1019,Faria Rahman,NaN,NaN,NaN,Not Started,2025-09-15,Mr. David,Chattogram,Bangladesh,CSTU,NaN,A,Pass,Fail,Faria
19,19,19,19,19,PH1020,Nasir Khan,86.0,86.0,89.0,Completed,2025-10-02,Ms. Salma,Dhaka,Bangladesh,CSTU,261.0,A,Pass,Fail,Nasir

In [37]:
import pandas as pd
import numpy as np

# This adds a new row at the next available index with all null values
df2.loc[len(df2)] = np.nan
df2

,Unnamed: 0.3,Unnamed: 0.2,Unnamed: 0.1,Unnamed: 0,StudentID,FullName,Data Structure Marks,Algorithm Marks,Python Marks,CompletionStatus,EnrollmentDate,Instructor,Location,Country,University,Total Mark,DSA GPA,DSA PASS,pass in Python,Last name
0,0.0,0.0,0.0,0.0,PH1001,Alif Rahman,85.0,85.0,88.0,Completed,2024-01-15,Mr. Karim,Dhaka,Bangladesh,CSTU,258.0,A,Pass,Fail,Alif
1,1.0,1.0,1.0,1.0,PH1002,Fatima Akhter,92.0,92.0,NaN,In Progress,2024-01-20,Ms. Salma,Chattogram,Bangladesh,CSTU,NaN,A+,Pass,Fail,Fatima
2,2.0,2.0,2.0,2.0,PH1003,Imran Hossain,88.0,88.0,85.0,Completed,2024-02-10,Mr. Karim,Dhaka,Bangladesh,CSTU,261.0,A,Pass,Fail,Imran
3,3.0,3.0,3.0,3.0,PH1004,Jannatul Ferdous,78.0,78.0,82.0,Completed,2024-02-12,Ms. Salma,Sylhet,Bangladesh,CSTU,238.0,A,Pass,Fail,Jannatul
4,4.0,4.0,4.0,4.0,PH1005,Kamal Uddin,NaN,NaN,95.0,In Progress,2024-03-05,Mr. Karim,Chattogram,Bangladesh,CSTU,NaN,A,Pass,Fail,Kamal
5,5.0,5.0,5.0,5.0,PH1006,Laila Begum,75.0,75.0,78.0,Completed,2024-03-08,Ms. Salma,Rajshahi,Bangladesh,CSTU,228.0,A,Pass,Pass,Laila
6,6.0,6.0,6.0,6.0,PH1007,Mahmudul Hasan,80.0,80.0,NaN,In Progress,2024-04-01,Mr. Karim,Dhaka,Bangladesh,CSTU,NaN,A,Pass,Fail,Mahmudul
7,7.0,7.0,7.0,7.0,PH1008,Nadia Islam,81.0,81.0,85.0,Completed,2024-04-22,Ms. Salma,Chattogram,Bangladesh,CSTU,247.0,A,Pass,Fail,Nadia
8,8.0,8.0,8.0,8.0,PH1009,Omar Faruq,72.0,72.0,76.0,Completed,2024-05-16,Mr. David,Dhaka,Bangladesh,CSTU,220.0,A,Pass,Pass,Omar
9,9.0,9.0,9.0,9.0,PH1010,Priya Sharma,89.0,89.0,88.0,Completed,2024-05-20,Ms. Salma,Sylhet,Bangladesh,CSTU,266.0,A,Pass,Fail,Priya
10,10.0,10.0,10.0,10.0,PH1011,Rahim Sheikh,NaN,NaN,91.0,In Progress,2024-06-11,Mr. Karim,Khulna,Bangladesh,CSTU,NaN,A,Pass,Fail,Rahim
11,11.0,11.0,11.0,11.0,PH1012,Sadia Chowdhury,85.0,85.0,87.0,Completed,2024-06-14,Ms. Salma,Chattogram,Bangladesh,CSTU,257.0,A,Pass,Fail,Sadia
12,12.0,12.0,12.0,12.0,PH1013,Tanvir Ahmed,75.0,75.0,79.0,Completed,2024-07-02,Mr. David,Dhaka,Bangladesh,CSTU,229.0,A,Pass,Pass,Tanvir
13,13.0,13.0,13.0,13.0,PH1014,Urmi Akter,NaN,NaN,NaN,Not Started,2024-07-09,Ms. Salma,Rajshahi,Bangladesh,CSTU,NaN,A,Pass,Fail,Urmi
14,14.0,14.0,14.0,14.0,PH1015,Wahiduzzaman,86.0,86.0,84.0,Completed,2024-08-18,Mr. Karim,Dhaka,Bangladesh,CSTU,256.0,A,Pass,Fail,Wahiduzzaman
15,15.0,15.0,15.0,15.0,PH1016,Ziaur Rahman,94.0,94.0,NaN,In Progress,2024-08-21,Ms. Salma,Chattogram,Bangladesh,CSTU,NaN,A+,Pass,Fail,Ziaur
16,16.0,16.0,16.0,16.0,PH1017,Afsana Mimi,90.0,90.0,93.0,Completed,2025-09-01,Mr. Karim,Dhaka,Bangladesh,CSTU,273.0,A,Pass,Fail,Afsana
17,17.0,17.0,17.0,17.0,PH1018,Babul Ahmed,88.0,88.0,85.0,Completed,2025-09-05,Ms. Salma,Sylhet,Bangladesh,CSTU,261.0,A,Pass,Fail,Babul
18,18.0,18.0,18.0,18.0,PH1019,Faria Rahman,NaN,NaN,NaN,Not Started,2025-09-15,Mr. David,Chattogram,Bangladesh,CSTU,NaN,A,Pass,Fail,Faria
19,19.0,19.0,19.0,19.0,PH1020,Nasir Khan,86.0,86.0,89.0,Completed,2025-10-02,Ms. Salma,Dhaka,Bangladesh,CSTU,261.0,A,Pass,Fail,Nasir
20,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

# Handling Null Values

In [38]:
import pandas as pd
df=pd.read_csv('student_data.csv')
df

,Unnamed: 0.4,Unnamed: 0.3,Unnamed: 0.2,Unnamed: 0.1,Unnamed: 0,StudentID,FullName,Data Structure Marks,Algorithm Marks,Python Marks,...,EnrollmentDate,Instructor,Location,Country,University,Total Mark,DSA GPA,DSA PASS,pass in Python,Last name
0,0,0,0,0,0,PH1001,Alif Rahman,85.0,85.0,88.0,...,2024-01-15,Mr. Karim,Dhaka,Bangladesh,CSTU,258.0,A,Pass,Fail,Alif
1,1,1,1,1,1,PH1002,Fatima Akhter,92.0,92.0,NaN,...,2024-01-20,Ms. Salma,Chattogram,Bangladesh,CSTU,NaN,A+,Pass,Fail,Fatima
2,2,2,2,2,2,PH1003,Imran Hossain,88.0,88.0,85.0,...,2024-02-10,Mr. Karim,Dhaka,Bangladesh,CSTU,261.0,A,Pass,Fail,Imran
3,3,3,3,3,3,PH1004,Jannatul Ferdous,78.0,78.0,82.0,...,2024-02-12,Ms. Salma,Sylhet,Bangladesh,CSTU,238.0,A,Pass,Fail,Jannatul
4,4,4,4,4,4,PH1005,Kamal Uddin,NaN,NaN,95.0,...,2024-03-05,Mr. Karim,Chattogram,Bangladesh,CSTU,NaN,A,Pass,Fail,Kamal
5,5,5,5,5,5,PH1006,Laila Begum,75.0,75.0,78.0,...,2024-03-08,Ms. Salma,Rajshahi,Bangladesh,CSTU,228.0,A,Pass,Pass,Laila
6,6,6,6,6,6,PH1007,Mahmudul Hasan,80.0,80.0,NaN,...,2024-04-01,Mr. Karim,Dhaka,Bangladesh,CSTU,NaN,A,Pass,Fail,Mahmudul
7,7,7,7,7,7,PH1008,Nadia Islam,81.0,81.0,85.0,...,2024-04-22,Ms. Salma,Chattogram,Bangladesh,CSTU,247.0,A,Pass,Fail,Nadia
8,8,8,8,8,8,PH1009,Omar Faruq,72.0,72.0,76.0,...,2024-05-16,Mr. David,Dhaka,Bangladesh,CSTU,220.0,A,Pass,Pass,Omar
9,9,9,9,9,9,PH1010,Priya Sharma,89.0,89.0,88.0,...,2024-05-20,Ms. Salma,Sylhet,Bangladesh,CSTU,266.0,A,Pass,Fail,Priya
10,10,10,10,10,10,PH1011,Rahim Sheikh,NaN,NaN,91.0,...,2024-06-11,Mr. Karim,Khulna,Bangladesh,CSTU,NaN,A,Pass,Fail,Rahim
11,11,11,11,11,11,PH1012,Sadia Chowdhury,85.0,85.0,87.0,...,2024-06-14,Ms. Salma,Chattogram,Bangladesh,CSTU,257.0,A,Pass,Fail,Sadia
12,12,12,12,12,12,PH1013,Tanvir Ahmed,75.0,75.0,79.0,...,2024-07-02,Mr. David,Dhaka,Bangladesh,CSTU,229.0,A,Pass,Pass,Tanvir
13,13,13,13,13,13,PH1014,Urmi Akter,NaN,NaN,NaN,...,2024-07-09,Ms. Salma,Rajshahi,Bangladesh,CSTU,NaN,A,Pass,Fail,Urmi
14,14,14,14,14,14,PH1015,Wahiduzzaman,86.0,86.0,84.0,...,2024-08-18,Mr. Karim,Dhaka,Bangladesh,CSTU,256.0,A,Pass,Fail,Wahiduzzaman
15,15,15,15,15,15,PH1016,Ziaur Rahman,94.0,94.0,NaN,...,2024-08-21,Ms. Salma,Chattogram,Bangladesh,CSTU,NaN,A+,Pass,Fail,Ziaur
16,16,16,16,16,16,PH1017,Afsana Mimi,90.0,90.0,93.0,...,2025-09-01,Mr. Karim,Dhaka,Bangladesh,CSTU,273.0,A,Pass,Fail,Afsana
17,17,17,17,17,17,PH1018,Babul Ahmed,88.0,88.0,85.0,...,2025-09-05,Ms. Salma,Sylhet,Bangladesh,CSTU,261.0,A,Pass,Fail,Babul
18,18,18,18,18,18,PH1019,Faria Rahman,NaN,NaN,NaN,...,2025-09-15,Mr. David,Chattogram,Bangladesh,CSTU,NaN,A,Pass,Fail,Faria
19,19,19,19,19,19,PH1020,Nasir Khan,86.0,86.0,89.0,...,2025-10-02,Ms. Salma,Dhaka,Bangladesh,CSTU,261.0,A,Pass,Fail,Nasir

In [39]:
df.dropna()

,Unnamed: 0.4,Unnamed: 0.3,Unnamed: 0.2,Unnamed: 0.1,Unnamed: 0,StudentID,FullName,Data Structure Marks,Algorithm Marks,Python Marks,...,EnrollmentDate,Instructor,Location,Country,University,Total Mark,DSA GPA,DSA PASS,pass in Python,Last name
0,0,0,0,0,0,PH1001,Alif Rahman,85.0,85.0,88.0,...,2024-01-15,Mr. Karim,Dhaka,Bangladesh,CSTU,258.0,A,Pass,Fail,Alif
2,2,2,2,2,2,PH1003,Imran Hossain,88.0,88.0,85.0,...,2024-02-10,Mr. Karim,Dhaka,Bangladesh,CSTU,261.0,A,Pass,Fail,Imran
3,3,3,3,3,3,PH1004,Jannatul Ferdous,78.0,78.0,82.0,...,2024-02-12,Ms. Salma,Sylhet,Bangladesh,CSTU,238.0,A,Pass,Fail,Jannatul
5,5,5,5,5,5,PH1006,Laila Begum,75.0,75.0,78.0,...,2024-03-08,Ms. Salma,Rajshahi,Bangladesh,CSTU,228.0,A,Pass,Pass,Laila
7,7,7,7,7,7,PH1008,Nadia Islam,81.0,81.0,85.0,...,2024-04-22,Ms. Salma,Chattogram,Bangladesh,CSTU,247.0,A,Pass,Fail,Nadia
8,8,8,8,8,8,PH1009,Omar Faruq,72.0,72.0,76.0,...,2024-05-16,Mr. David,Dhaka,Bangladesh,CSTU,220.0,A,Pass,Pass,Omar
9,9,9,9,9,9,PH1010,Priya Sharma,89.0,89.0,88.0,...,2024-05-20,Ms. Salma,Sylhet,Bangladesh,CSTU,266.0,A,Pass,Fail,Priya
11,11,11,11,11,11,PH1012,Sadia Chowdhury,85.0,85.0,87.0,...,2024-06-14,Ms. Salma,Chattogram,Bangladesh,CSTU,257.0,A,Pass,Fail,Sadia
12,12,12,12,12,12,PH1013,Tanvir Ahmed,75.0,75.0,79.0,...,2024-07-02,Mr. David,Dhaka,Bangladesh,CSTU,229.0,A,Pass,Pass,Tanvir
14,14,14,14,14,14,PH1015,Wahiduzzaman,86.0,86.0,84.0,...,2024-08-18,Mr. Karim,Dhaka,Bangladesh,CSTU,256.0,A,Pass,Fail,Wahiduzzaman
16,16,16,16,16,16,PH1017,Afsana Mimi,90.0,90.0,93.0,...,2025-09-01,Mr. Karim,Dhaka,Bangladesh,CSTU,273.0,A,Pass,Fail,Afsana
17,17,17,17,17,17,PH1018,Babul Ahmed,88.0,88.0,85.0,...,2025-09-05,Ms. Salma,Sylhet,Bangladesh,CSTU,261.0,A,Pass,Fail,Babul
19,19,19,19,19,19,PH1020,Nasir Khan,86.0,86.0,89.0,...,2025-10-02,Ms. Salma,Dhaka,Bangladesh,CSTU,261.0,A,Pass,Fail,Nasir

In [40]:
df

,Unnamed: 0.4,Unnamed: 0.3,Unnamed: 0.2,Unnamed: 0.1,Unnamed: 0,StudentID,FullName,Data Structure Marks,Algorithm Marks,Python Marks,...,EnrollmentDate,Instructor,Location,Country,University,Total Mark,DSA GPA,DSA PASS,pass in Python,Last name
0,0,0,0,0,0,PH1001,Alif Rahman,85.0,85.0,88.0,...,2024-01-15,Mr. Karim,Dhaka,Bangladesh,CSTU,258.0,A,Pass,Fail,Alif
1,1,1,1,1,1,PH1002,Fatima Akhter,92.0,92.0,NaN,...,2024-01-20,Ms. Salma,Chattogram,Bangladesh,CSTU,NaN,A+,Pass,Fail,Fatima
2,2,2,2,2,2,PH1003,Imran Hossain,88.0,88.0,85.0,...,2024-02-10,Mr. Karim,Dhaka,Bangladesh,CSTU,261.0,A,Pass,Fail,Imran
3,3,3,3,3,3,PH1004,Jannatul Ferdous,78.0,78.0,82.0,...,2024-02-12,Ms. Salma,Sylhet,Bangladesh,CSTU,238.0,A,Pass,Fail,Jannatul
4,4,4,4,4,4,PH1005,Kamal Uddin,NaN,NaN,95.0,...,2024-03-05,Mr. Karim,Chattogram,Bangladesh,CSTU,NaN,A,Pass,Fail,Kamal
5,5,5,5,5,5,PH1006,Laila Begum,75.0,75.0,78.0,...,2024-03-08,Ms. Salma,Rajshahi,Bangladesh,CSTU,228.0,A,Pass,Pass,Laila
6,6,6,6,6,6,PH1007,Mahmudul Hasan,80.0,80.0,NaN,...,2024-04-01,Mr. Karim,Dhaka,Bangladesh,CSTU,NaN,A,Pass,Fail,Mahmudul
7,7,7,7,7,7,PH1008,Nadia Islam,81.0,81.0,85.0,...,2024-04-22,Ms. Salma,Chattogram,Bangladesh,CSTU,247.0,A,Pass,Fail,Nadia
8,8,8,8,8,8,PH1009,Omar Faruq,72.0,72.0,76.0,...,2024-05-16,Mr. David,Dhaka,Bangladesh,CSTU,220.0,A,Pass,Pass,Omar
9,9,9,9,9,9,PH1010,Priya Sharma,89.0,89.0,88.0,...,2024-05-20,Ms. Salma,Sylhet,Bangladesh,CSTU,266.0,A,Pass,Fail,Priya
10,10,10,10,10,10,PH1011,Rahim Sheikh,NaN,NaN,91.0,...,2024-06-11,Mr. Karim,Khulna,Bangladesh,CSTU,NaN,A,Pass,Fail,Rahim
11,11,11,11,11,11,PH1012,Sadia Chowdhury,85.0,85.0,87.0,...,2024-06-14,Ms. Salma,Chattogram,Bangladesh,CSTU,257.0,A,Pass,Fail,Sadia
12,12,12,12,12,12,PH1013,Tanvir Ahmed,75.0,75.0,79.0,...,2024-07-02,Mr. David,Dhaka,Bangladesh,CSTU,229.0,A,Pass,Pass,Tanvir
13,13,13,13,13,13,PH1014,Urmi Akter,NaN,NaN,NaN,...,2024-07-09,Ms. Salma,Rajshahi,Bangladesh,CSTU,NaN,A,Pass,Fail,Urmi
14,14,14,14,14,14,PH1015,Wahiduzzaman,86.0,86.0,84.0,...,2024-08-18,Mr. Karim,Dhaka,Bangladesh,CSTU,256.0,A,Pass,Fail,Wahiduzzaman
15,15,15,15,15,15,PH1016,Ziaur Rahman,94.0,94.0,NaN,...,2024-08-21,Ms. Salma,Chattogram,Bangladesh,CSTU,NaN,A+,Pass,Fail,Ziaur
16,16,16,16,16,16,PH1017,Afsana Mimi,90.0,90.0,93.0,...,2025-09-01,Mr. Karim,Dhaka,Bangladesh,CSTU,273.0,A,Pass,Fail,Afsana
17,17,17,17,17,17,PH1018,Babul Ahmed,88.0,88.0,85.0,...,2025-09-05,Ms. Salma,Sylhet,Bangladesh,CSTU,261.0,A,Pass,Fail,Babul
18,18,18,18,18,18,PH1019,Faria Rahman,NaN,NaN,NaN,...,2025-09-15,Mr. David,Chattogram,Bangladesh,CSTU,NaN,A,Pass,Fail,Faria
19,19,19,19,19,19,PH1020,Nasir Khan,86.0,86.0,89.0,...,2025-10-02,Ms. Salma,Dhaka,Bangladesh,CSTU,261.0,A,Pass,Fail,Nasir

In [41]:
df.dropna(how="all",inplace=True)
df

,Unnamed: 0.4,Unnamed: 0.3,Unnamed: 0.2,Unnamed: 0.1,Unnamed: 0,StudentID,FullName,Data Structure Marks,Algorithm Marks,Python Marks,...,EnrollmentDate,Instructor,Location,Country,University,Total Mark,DSA GPA,DSA PASS,pass in Python,Last name
0,0,0,0,0,0,PH1001,Alif Rahman,85.0,85.0,88.0,...,2024-01-15,Mr. Karim,Dhaka,Bangladesh,CSTU,258.0,A,Pass,Fail,Alif
1,1,1,1,1,1,PH1002,Fatima Akhter,92.0,92.0,NaN,...,2024-01-20,Ms. Salma,Chattogram,Bangladesh,CSTU,NaN,A+,Pass,Fail,Fatima
2,2,2,2,2,2,PH1003,Imran Hossain,88.0,88.0,85.0,...,2024-02-10,Mr. Karim,Dhaka,Bangladesh,CSTU,261.0,A,Pass,Fail,Imran
3,3,3,3,3,3,PH1004,Jannatul Ferdous,78.0,78.0,82.0,...,2024-02-12,Ms. Salma,Sylhet,Bangladesh,CSTU,238.0,A,Pass,Fail,Jannatul
4,4,4,4,4,4,PH1005,Kamal Uddin,NaN,NaN,95.0,...,2024-03-05,Mr. Karim,Chattogram,Bangladesh,CSTU,NaN,A,Pass,Fail,Kamal
5,5,5,5,5,5,PH1006,Laila Begum,75.0,75.0,78.0,...,2024-03-08,Ms. Salma,Rajshahi,Bangladesh,CSTU,228.0,A,Pass,Pass,Laila
6,6,6,6,6,6,PH1007,Mahmudul Hasan,80.0,80.0,NaN,...,2024-04-01,Mr. Karim,Dhaka,Bangladesh,CSTU,NaN,A,Pass,Fail,Mahmudul
7,7,7,7,7,7,PH1008,Nadia Islam,81.0,81.0,85.0,...,2024-04-22,Ms. Salma,Chattogram,Bangladesh,CSTU,247.0,A,Pass,Fail,Nadia
8,8,8,8,8,8,PH1009,Omar Faruq,72.0,72.0,76.0,...,2024-05-16,Mr. David,Dhaka,Bangladesh,CSTU,220.0,A,Pass,Pass,Omar
9,9,9,9,9,9,PH1010,Priya Sharma,89.0,89.0,88.0,...,2024-05-20,Ms. Salma,Sylhet,Bangladesh,CSTU,266.0,A,Pass,Fail,Priya
10,10,10,10,10,10,PH1011,Rahim Sheikh,NaN,NaN,91.0,...,2024-06-11,Mr. Karim,Khulna,Bangladesh,CSTU,NaN,A,Pass,Fail,Rahim
11,11,11,11,11,11,PH1012,Sadia Chowdhury,85.0,85.0,87.0,...,2024-06-14,Ms. Salma,Chattogram,Bangladesh,CSTU,257.0,A,Pass,Fail,Sadia
12,12,12,12,12,12,PH1013,Tanvir Ahmed,75.0,75.0,79.0,...,2024-07-02,Mr. David,Dhaka,Bangladesh,CSTU,229.0,A,Pass,Pass,Tanvir
13,13,13,13,13,13,PH1014,Urmi Akter,NaN,NaN,NaN,...,2024-07-09,Ms. Salma,Rajshahi,Bangladesh,CSTU,NaN,A,Pass,Fail,Urmi
14,14,14,14,14,14,PH1015,Wahiduzzaman,86.0,86.0,84.0,...,2024-08-18,Mr. Karim,Dhaka,Bangladesh,CSTU,256.0,A,Pass,Fail,Wahiduzzaman
15,15,15,15,15,15,PH1016,Ziaur Rahman,94.0,94.0,NaN,...,2024-08-21,Ms. Salma,Chattogram,Bangladesh,CSTU,NaN,A+,Pass,Fail,Ziaur
16,16,16,16,16,16,PH1017,Afsana Mimi,90.0,90.0,93.0,...,2025-09-01,Mr. Karim,Dhaka,Bangladesh,CSTU,273.0,A,Pass,Fail,Afsana
17,17,17,17,17,17,PH1018,Babul Ahmed,88.0,88.0,85.0,...,2025-09-05,Ms. Salma,Sylhet,Bangladesh,CSTU,261.0,A,Pass,Fail,Babul
18,18,18,18,18,18,PH1019,Faria Rahman,NaN,NaN,NaN,...,2025-09-15,Mr. David,Chattogram,Bangladesh,CSTU,NaN,A,Pass,Fail,Faria
19,19,19,19,19,19,PH1020,Nasir Khan,86.0,86.0,89.0,...,2025-10-02,Ms. Salma,Dhaka,Bangladesh,CSTU,261.0,A,Pass,Fail,Nasir

In [42]:
#delete all row which python mark is Zero
df.dropna(subset=['Python Marks'])

,Unnamed: 0.4,Unnamed: 0.3,Unnamed: 0.2,Unnamed: 0.1,Unnamed: 0,StudentID,FullName,Data Structure Marks,Algorithm Marks,Python Marks,...,EnrollmentDate,Instructor,Location,Country,University,Total Mark,DSA GPA,DSA PASS,pass in Python,Last name
0,0,0,0,0,0,PH1001,Alif Rahman,85.0,85.0,88.0,...,2024-01-15,Mr. Karim,Dhaka,Bangladesh,CSTU,258.0,A,Pass,Fail,Alif
2,2,2,2,2,2,PH1003,Imran Hossain,88.0,88.0,85.0,...,2024-02-10,Mr. Karim,Dhaka,Bangladesh,CSTU,261.0,A,Pass,Fail,Imran
3,3,3,3,3,3,PH1004,Jannatul Ferdous,78.0,78.0,82.0,...,2024-02-12,Ms. Salma,Sylhet,Bangladesh,CSTU,238.0,A,Pass,Fail,Jannatul
4,4,4,4,4,4,PH1005,Kamal Uddin,NaN,NaN,95.0,...,2024-03-05,Mr. Karim,Chattogram,Bangladesh,CSTU,NaN,A,Pass,Fail,Kamal
5,5,5,5,5,5,PH1006,Laila Begum,75.0,75.0,78.0,...,2024-03-08,Ms. Salma,Rajshahi,Bangladesh,CSTU,228.0,A,Pass,Pass,Laila
7,7,7,7,7,7,PH1008,Nadia Islam,81.0,81.0,85.0,...,2024-04-22,Ms. Salma,Chattogram,Bangladesh,CSTU,247.0,A,Pass,Fail,Nadia
8,8,8,8,8,8,PH1009,Omar Faruq,72.0,72.0,76.0,...,2024-05-16,Mr. David,Dhaka,Bangladesh,CSTU,220.0,A,Pass,Pass,Omar
9,9,9,9,9,9,PH1010,Priya Sharma,89.0,89.0,88.0,...,2024-05-20,Ms. Salma,Sylhet,Bangladesh,CSTU,266.0,A,Pass,Fail,Priya
10,10,10,10,10,10,PH1011,Rahim Sheikh,NaN,NaN,91.0,...,2024-06-11,Mr. Karim,Khulna,Bangladesh,CSTU,NaN,A,Pass,Fail,Rahim
11,11,11,11,11,11,PH1012,Sadia Chowdhury,85.0,85.0,87.0,...,2024-06-14,Ms. Salma,Chattogram,Bangladesh,CSTU,257.0,A,Pass,Fail,Sadia
12,12,12,12,12,12,PH1013,Tanvir Ahmed,75.0,75.0,79.0,...,2024-07-02,Mr. David,Dhaka,Bangladesh,CSTU,229.0,A,Pass,Pass,Tanvir
14,14,14,14,14,14,PH1015,Wahiduzzaman,86.0,86.0,84.0,...,2024-08-18,Mr. Karim,Dhaka,Bangladesh,CSTU,256.0,A,Pass,Fail,Wahiduzzaman
16,16,16,16,16,16,PH1017,Afsana Mimi,90.0,90.0,93.0,...,2025-09-01,Mr. Karim,Dhaka,Bangladesh,CSTU,273.0,A,Pass,Fail,Afsana
17,17,17,17,17,17,PH1018,Babul Ahmed,88.0,88.0,85.0,...,2025-09-05,Ms. Salma,Sylhet,Bangladesh,CSTU,261.0,A,Pass,Fail,Babul
19,19,19,19,19,19,PH1020,Nasir Khan,86.0,86.0,89.0,...,2025-10-02,Ms. Salma,Dhaka,Bangladesh,CSTU,261.0,A,Pass,Fail,Nasir

In [43]:
df.dropna(subset=['Python Marks','Data Structure Marks'])

,Unnamed: 0.4,Unnamed: 0.3,Unnamed: 0.2,Unnamed: 0.1,Unnamed: 0,StudentID,FullName,Data Structure Marks,Algorithm Marks,Python Marks,...,EnrollmentDate,Instructor,Location,Country,University,Total Mark,DSA GPA,DSA PASS,pass in Python,Last name
0,0,0,0,0,0,PH1001,Alif Rahman,85.0,85.0,88.0,...,2024-01-15,Mr. Karim,Dhaka,Bangladesh,CSTU,258.0,A,Pass,Fail,Alif
2,2,2,2,2,2,PH1003,Imran Hossain,88.0,88.0,85.0,...,2024-02-10,Mr. Karim,Dhaka,Bangladesh,CSTU,261.0,A,Pass,Fail,Imran
3,3,3,3,3,3,PH1004,Jannatul Ferdous,78.0,78.0,82.0,...,2024-02-12,Ms. Salma,Sylhet,Bangladesh,CSTU,238.0,A,Pass,Fail,Jannatul
5,5,5,5,5,5,PH1006,Laila Begum,75.0,75.0,78.0,...,2024-03-08,Ms. Salma,Rajshahi,Bangladesh,CSTU,228.0,A,Pass,Pass,Laila
7,7,7,7,7,7,PH1008,Nadia Islam,81.0,81.0,85.0,...,2024-04-22,Ms. Salma,Chattogram,Bangladesh,CSTU,247.0,A,Pass,Fail,Nadia
8,8,8,8,8,8,PH1009,Omar Faruq,72.0,72.0,76.0,...,2024-05-16,Mr. David,Dhaka,Bangladesh,CSTU,220.0,A,Pass,Pass,Omar
9,9,9,9,9,9,PH1010,Priya Sharma,89.0,89.0,88.0,...,2024-05-20,Ms. Salma,Sylhet,Bangladesh,CSTU,266.0,A,Pass,Fail,Priya
11,11,11,11,11,11,PH1012,Sadia Chowdhury,85.0,85.0,87.0,...,2024-06-14,Ms. Salma,Chattogram,Bangladesh,CSTU,257.0,A,Pass,Fail,Sadia
12,12,12,12,12,12,PH1013,Tanvir Ahmed,75.0,75.0,79.0,...,2024-07-02,Mr. David,Dhaka,Bangladesh,CSTU,229.0,A,Pass,Pass,Tanvir
14,14,14,14,14,14,PH1015,Wahiduzzaman,86.0,86.0,84.0,...,2024-08-18,Mr. Karim,Dhaka,Bangladesh,CSTU,256.0,A,Pass,Fail,Wahiduzzaman
16,16,16,16,16,16,PH1017,Afsana Mimi,90.0,90.0,93.0,...,2025-09-01,Mr. Karim,Dhaka,Bangladesh,CSTU,273.0,A,Pass,Fail,Afsana
17,17,17,17,17,17,PH1018,Babul Ahmed,88.0,88.0,85.0,...,2025-09-05,Ms. Salma,Sylhet,Bangladesh,CSTU,261.0,A,Pass,Fail,Babul
19,19,19,19,19,19,PH1020,Nasir Khan,86.0,86.0,89.0,...,2025-10-02,Ms. Salma,Dhaka,Bangladesh,CSTU,261.0,A,Pass,Fail,Nasir

In [44]:
df.fillna(26)

,Unnamed: 0.4,Unnamed: 0.3,Unnamed: 0.2,Unnamed: 0.1,Unnamed: 0,StudentID,FullName,Data Structure Marks,Algorithm Marks,Python Marks,...,EnrollmentDate,Instructor,Location,Country,University,Total Mark,DSA GPA,DSA PASS,pass in Python,Last name
0,0,0,0,0,0,PH1001,Alif Rahman,85.0,85.0,88.0,...,2024-01-15,Mr. Karim,Dhaka,Bangladesh,CSTU,258.0,A,Pass,Fail,Alif
1,1,1,1,1,1,PH1002,Fatima Akhter,92.0,92.0,26.0,...,2024-01-20,Ms. Salma,Chattogram,Bangladesh,CSTU,26.0,A+,Pass,Fail,Fatima
2,2,2,2,2,2,PH1003,Imran Hossain,88.0,88.0,85.0,...,2024-02-10,Mr. Karim,Dhaka,Bangladesh,CSTU,261.0,A,Pass,Fail,Imran
3,3,3,3,3,3,PH1004,Jannatul Ferdous,78.0,78.0,82.0,...,2024-02-12,Ms. Salma,Sylhet,Bangladesh,CSTU,238.0,A,Pass,Fail,Jannatul
4,4,4,4,4,4,PH1005,Kamal Uddin,26.0,26.0,95.0,...,2024-03-05,Mr. Karim,Chattogram,Bangladesh,CSTU,26.0,A,Pass,Fail,Kamal
5,5,5,5,5,5,PH1006,Laila Begum,75.0,75.0,78.0,...,2024-03-08,Ms. Salma,Rajshahi,Bangladesh,CSTU,228.0,A,Pass,Pass,Laila
6,6,6,6,6,6,PH1007,Mahmudul Hasan,80.0,80.0,26.0,...,2024-04-01,Mr. Karim,Dhaka,Bangladesh,CSTU,26.0,A,Pass,Fail,Mahmudul
7,7,7,7,7,7,PH1008,Nadia Islam,81.0,81.0,85.0,...,2024-04-22,Ms. Salma,Chattogram,Bangladesh,CSTU,247.0,A,Pass,Fail,Nadia
8,8,8,8,8,8,PH1009,Omar Faruq,72.0,72.0,76.0,...,2024-05-16,Mr. David,Dhaka,Bangladesh,CSTU,220.0,A,Pass,Pass,Omar
9,9,9,9,9,9,PH1010,Priya Sharma,89.0,89.0,88.0,...,2024-05-20,Ms. Salma,Sylhet,Bangladesh,CSTU,266.0,A,Pass,Fail,Priya
10,10,10,10,10,10,PH1011,Rahim Sheikh,26.0,26.0,91.0,...,2024-06-11,Mr. Karim,Khulna,Bangladesh,CSTU,26.0,A,Pass,Fail,Rahim
11,11,11,11,11,11,PH1012,Sadia Chowdhury,85.0,85.0,87.0,...,2024-06-14,Ms. Salma,Chattogram,Bangladesh,CSTU,257.0,A,Pass,Fail,Sadia
12,12,12,12,12,12,PH1013,Tanvir Ahmed,75.0,75.0,79.0,...,2024-07-02,Mr. David,Dhaka,Bangladesh,CSTU,229.0,A,Pass,Pass,Tanvir
13,13,13,13,13,13,PH1014,Urmi Akter,26.0,26.0,26.0,...,2024-07-09,Ms. Salma,Rajshahi,Bangladesh,CSTU,26.0,A,Pass,Fail,Urmi
14,14,14,14,14,14,PH1015,Wahiduzzaman,86.0,86.0,84.0,...,2024-08-18,Mr. Karim,Dhaka,Bangladesh,CSTU,256.0,A,Pass,Fail,Wahiduzzaman
15,15,15,15,15,15,PH1016,Ziaur Rahman,94.0,94.0,26.0,...,2024-08-21,Ms. Salma,Chattogram,Bangladesh,CSTU,26.0,A+,Pass,Fail,Ziaur
16,16,16,16,16,16,PH1017,Afsana Mimi,90.0,90.0,93.0,...,2025-09-01,Mr. Karim,Dhaka,Bangladesh,CSTU,273.0,A,Pass,Fail,Afsana
17,17,17,17,17,17,PH1018,Babul Ahmed,88.0,88.0,85.0,...,2025-09-05,Ms. Salma,Sylhet,Bangladesh,CSTU,261.0,A,Pass,Fail,Babul
18,18,18,18,18,18,PH1019,Faria Rahman,26.0,26.0,26.0,...,2025-09-15,Mr. David,Chattogram,Bangladesh,CSTU,26.0,A,Pass,Fail,Faria
19,19,19,19,19,19,PH1020,Nasir Khan,86.0,86.0,89.0,...,2025-10-02,Ms. Salma,Dhaka,Bangladesh,CSTU,261.0,A,Pass,Fail,Nasir

In [45]:
df=pd.read_csv('student_data.csv')
df

,Unnamed: 0.4,Unnamed: 0.3,Unnamed: 0.2,Unnamed: 0.1,Unnamed: 0,StudentID,FullName,Data Structure Marks,Algorithm Marks,Python Marks,...,EnrollmentDate,Instructor,Location,Country,University,Total Mark,DSA GPA,DSA PASS,pass in Python,Last name
0,0,0,0,0,0,PH1001,Alif Rahman,85.0,85.0,88.0,...,2024-01-15,Mr. Karim,Dhaka,Bangladesh,CSTU,258.0,A,Pass,Fail,Alif
1,1,1,1,1,1,PH1002,Fatima Akhter,92.0,92.0,NaN,...,2024-01-20,Ms. Salma,Chattogram,Bangladesh,CSTU,NaN,A+,Pass,Fail,Fatima
2,2,2,2,2,2,PH1003,Imran Hossain,88.0,88.0,85.0,...,2024-02-10,Mr. Karim,Dhaka,Bangladesh,CSTU,261.0,A,Pass,Fail,Imran
3,3,3,3,3,3,PH1004,Jannatul Ferdous,78.0,78.0,82.0,...,2024-02-12,Ms. Salma,Sylhet,Bangladesh,CSTU,238.0,A,Pass,Fail,Jannatul
4,4,4,4,4,4,PH1005,Kamal Uddin,NaN,NaN,95.0,...,2024-03-05,Mr. Karim,Chattogram,Bangladesh,CSTU,NaN,A,Pass,Fail,Kamal
5,5,5,5,5,5,PH1006,Laila Begum,75.0,75.0,78.0,...,2024-03-08,Ms. Salma,Rajshahi,Bangladesh,CSTU,228.0,A,Pass,Pass,Laila
6,6,6,6,6,6,PH1007,Mahmudul Hasan,80.0,80.0,NaN,...,2024-04-01,Mr. Karim,Dhaka,Bangladesh,CSTU,NaN,A,Pass,Fail,Mahmudul
7,7,7,7,7,7,PH1008,Nadia Islam,81.0,81.0,85.0,...,2024-04-22,Ms. Salma,Chattogram,Bangladesh,CSTU,247.0,A,Pass,Fail,Nadia
8,8,8,8,8,8,PH1009,Omar Faruq,72.0,72.0,76.0,...,2024-05-16,Mr. David,Dhaka,Bangladesh,CSTU,220.0,A,Pass,Pass,Omar
9,9,9,9,9,9,PH1010,Priya Sharma,89.0,89.0,88.0,...,2024-05-20,Ms. Salma,Sylhet,Bangladesh,CSTU,266.0,A,Pass,Fail,Priya
10,10,10,10,10,10,PH1011,Rahim Sheikh,NaN,NaN,91.0,...,2024-06-11,Mr. Karim,Khulna,Bangladesh,CSTU,NaN,A,Pass,Fail,Rahim
11,11,11,11,11,11,PH1012,Sadia Chowdhury,85.0,85.0,87.0,...,2024-06-14,Ms. Salma,Chattogram,Bangladesh,CSTU,257.0,A,Pass,Fail,Sadia
12,12,12,12,12,12,PH1013,Tanvir Ahmed,75.0,75.0,79.0,...,2024-07-02,Mr. David,Dhaka,Bangladesh,CSTU,229.0,A,Pass,Pass,Tanvir
13,13,13,13,13,13,PH1014,Urmi Akter,NaN,NaN,NaN,...,2024-07-09,Ms. Salma,Rajshahi,Bangladesh,CSTU,NaN,A,Pass,Fail,Urmi
14,14,14,14,14,14,PH1015,Wahiduzzaman,86.0,86.0,84.0,...,2024-08-18,Mr. Karim,Dhaka,Bangladesh,CSTU,256.0,A,Pass,Fail,Wahiduzzaman
15,15,15,15,15,15,PH1016,Ziaur Rahman,94.0,94.0,NaN,...,2024-08-21,Ms. Salma,Chattogram,Bangladesh,CSTU,NaN,A+,Pass,Fail,Ziaur
16,16,16,16,16,16,PH1017,Afsana Mimi,90.0,90.0,93.0,...,2025-09-01,Mr. Karim,Dhaka,Bangladesh,CSTU,273.0,A,Pass,Fail,Afsana
17,17,17,17,17,17,PH1018,Babul Ahmed,88.0,88.0,85.0,...,2025-09-05,Ms. Salma,Sylhet,Bangladesh,CSTU,261.0,A,Pass,Fail,Babul
18,18,18,18,18,18,PH1019,Faria Rahman,NaN,NaN,NaN,...,2025-09-15,Mr. David,Chattogram,Bangladesh,CSTU,NaN,A,Pass,Fail,Faria
19,19,19,19,19,19,PH1020,Nasir Khan,86.0,86.0,89.0,...,2025-10-02,Ms. Salma,Dhaka,Bangladesh,CSTU,261.0,A,Pass,Fail,Nasir

In [46]:
import pandas as pd
import numpy as np

# This adds a new row at the next available index with all null values
df.loc[len(df)] = np.nan
df

,Unnamed: 0.4,Unnamed: 0.3,Unnamed: 0.2,Unnamed: 0.1,Unnamed: 0,StudentID,FullName,Data Structure Marks,Algorithm Marks,Python Marks,...,EnrollmentDate,Instructor,Location,Country,University,Total Mark,DSA GPA,DSA PASS,pass in Python,Last name
0,0.0,0.0,0.0,0.0,0.0,PH1001,Alif Rahman,85.0,85.0,88.0,...,2024-01-15,Mr. Karim,Dhaka,Bangladesh,CSTU,258.0,A,Pass,Fail,Alif
1,1.0,1.0,1.0,1.0,1.0,PH1002,Fatima Akhter,92.0,92.0,NaN,...,2024-01-20,Ms. Salma,Chattogram,Bangladesh,CSTU,NaN,A+,Pass,Fail,Fatima
2,2.0,2.0,2.0,2.0,2.0,PH1003,Imran Hossain,88.0,88.0,85.0,...,2024-02-10,Mr. Karim,Dhaka,Bangladesh,CSTU,261.0,A,Pass,Fail,Imran
3,3.0,3.0,3.0,3.0,3.0,PH1004,Jannatul Ferdous,78.0,78.0,82.0,...,2024-02-12,Ms. Salma,Sylhet,Bangladesh,CSTU,238.0,A,Pass,Fail,Jannatul
4,4.0,4.0,4.0,4.0,4.0,PH1005,Kamal Uddin,NaN,NaN,95.0,...,2024-03-05,Mr. Karim,Chattogram,Bangladesh,CSTU,NaN,A,Pass,Fail,Kamal
5,5.0,5.0,5.0,5.0,5.0,PH1006,Laila Begum,75.0,75.0,78.0,...,2024-03-08,Ms. Salma,Rajshahi,Bangladesh,CSTU,228.0,A,Pass,Pass,Laila
6,6.0,6.0,6.0,6.0,6.0,PH1007,Mahmudul Hasan,80.0,80.0,NaN,...,2024-04-01,Mr. Karim,Dhaka,Bangladesh,CSTU,NaN,A,Pass,Fail,Mahmudul
7,7.0,7.0,7.0,7.0,7.0,PH1008,Nadia Islam,81.0,81.0,85.0,...,2024-04-22,Ms. Salma,Chattogram,Bangladesh,CSTU,247.0,A,Pass,Fail,Nadia
8,8.0,8.0,8.0,8.0,8.0,PH1009,Omar Faruq,72.0,72.0,76.0,...,2024-05-16,Mr. David,Dhaka,Bangladesh,CSTU,220.0,A,Pass,Pass,Omar
9,9.0,9.0,9.0,9.0,9.0,PH1010,Priya Sharma,89.0,89.0,88.0,...,2024-05-20,Ms. Salma,Sylhet,Bangladesh,CSTU,266.0,A,Pass,Fail,Priya
10,10.0,10.0,10.0,10.0,10.0,PH1011,Rahim Sheikh,NaN,NaN,91.0,...,2024-06-11,Mr. Karim,Khulna,Bangladesh,CSTU,NaN,A,Pass,Fail,Rahim
11,11.0,11.0,11.0,11.0,11.0,PH1012,Sadia Chowdhury,85.0,85.0,87.0,...,2024-06-14,Ms. Salma,Chattogram,Bangladesh,CSTU,257.0,A,Pass,Fail,Sadia
12,12.0,12.0,12.0,12.0,12.0,PH1013,Tanvir Ahmed,75.0,75.0,79.0,...,2024-07-02,Mr. David,Dhaka,Bangladesh,CSTU,229.0,A,Pass,Pass,Tanvir
13,13.0,13.0,13.0,13.0,13.0,PH1014,Urmi Akter,NaN,NaN,NaN,...,2024-07-09,Ms. Salma,Rajshahi,Bangladesh,CSTU,NaN,A,Pass,Fail,Urmi
14,14.0,14.0,14.0,14.0,14.0,PH1015,Wahiduzzaman,86.0,86.0,84.0,...,2024-08-18,Mr. Karim,Dhaka,Bangladesh,CSTU,256.0,A,Pass,Fail,Wahiduzzaman
15,15.0,15.0,15.0,15.0,15.0,PH1016,Ziaur Rahman,94.0,94.0,NaN,...,2024-08-21,Ms. Salma,Chattogram,Bangladesh,CSTU,NaN,A+,Pass,Fail,Ziaur
16,16.0,16.0,16.0,16.0,16.0,PH1017,Afsana Mimi,90.0,90.0,93.0,...,2025-09-01,Mr. Karim,Dhaka,Bangladesh,CSTU,273.0,A,Pass,Fail,Afsana
17,17.0,17.0,17.0,17.0,17.0,PH1018,Babul Ahmed,88.0,88.0,85.0,...,2025-09-05,Ms. Salma,Sylhet,Bangladesh,CSTU,261.0,A,Pass,Fail,Babul
18,18.0,18.0,18.0,18.0,18.0,PH1019,Faria Rahman,NaN,NaN,NaN,...,2025-09-15,Mr. David,Chattogram,Bangladesh,CSTU,NaN,A,Pass,Fail,Faria
19,19.0,19.0,19.0,19.0,19.0,PH1020,Nasir Khan,86.0,86.0,89.0,...,2025-10-02,Ms. Salma,Dhaka,Bangladesh,CSTU,261.0,A,Pass,Fail,Nasir
20,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [47]:
df["FullName"].fillna("Uknown")

0          Alif Rahman
1        Fatima Akhter
2        Imran Hossain
3     Jannatul Ferdous
4          Kamal Uddin
5          Laila Begum
6       Mahmudul Hasan
7          Nadia Islam
8           Omar Faruq
9         Priya Sharma
10        Rahim Sheikh
11     Sadia Chowdhury
12        Tanvir Ahmed
13          Urmi Akter
14        Wahiduzzaman
15        Ziaur Rahman
16         Afsana Mimi
17         Babul Ahmed
18        Faria Rahman
19          Nasir Khan
20              Uknown
Name: FullName, dtype: object

In [48]:
df['Data Structure Marks'].fillna(df['Data Structure Marks'].mean(),inplace=True)
df

C:\Users\user\AppData\Local\Temp\ipykernel_19856\4175602188.py:1: FutureWarning: A value is trying to be set on a copy of a DataFrame or Series through chained assignment using an inplace method.
The behavior will change in pandas 3.0. This inplace method will never work because the intermediate object on which we are setting values always behaves as a copy.

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' or df[col] = df[col].method(value) instead, to perform the operation inplace on the original object.


  df['Data Structure Marks'].fillna(df['Data Structure Marks'].mean(),inplace=True)

,Unnamed: 0.4,Unnamed: 0.3,Unnamed: 0.2,Unnamed: 0.1,Unnamed: 0,StudentID,FullName,Data Structure Marks,Algorithm Marks,Python Marks,...,EnrollmentDate,Instructor,Location,Country,University,Total Mark,DSA GPA,DSA PASS,pass in Python,Last name
0,0.0,0.0,0.0,0.0,0.0,PH1001,Alif Rahman,85.0,85.0,88.0,...,2024-01-15,Mr. Karim,Dhaka,Bangladesh,CSTU,258.0,A,Pass,Fail,Alif
1,1.0,1.0,1.0,1.0,1.0,PH1002,Fatima Akhter,92.0,92.0,NaN,...,2024-01-20,Ms. Salma,Chattogram,Bangladesh,CSTU,NaN,A+,Pass,Fail,Fatima
2,2.0,2.0,2.0,2.0,2.0,PH1003,Imran Hossain,88.0,88.0,85.0,...,2024-02-10,Mr. Karim,Dhaka,Bangladesh,CSTU,261.0,A,Pass,Fail,Imran
3,3.0,3.0,3.0,3.0,3.0,PH1004,Jannatul Ferdous,78.0,78.0,82.0,...,2024-02-12,Ms. Salma,Sylhet,Bangladesh,CSTU,238.0,A,Pass,Fail,Jannatul
4,4.0,4.0,4.0,4.0,4.0,PH1005,Kamal Uddin,84.0,NaN,95.0,...,2024-03-05,Mr. Karim,Chattogram,Bangladesh,CSTU,NaN,A,Pass,Fail,Kamal
5,5.0,5.0,5.0,5.0,5.0,PH1006,Laila Begum,75.0,75.0,78.0,...,2024-03-08,Ms. Salma,Rajshahi,Bangladesh,CSTU,228.0,A,Pass,Pass,Laila
6,6.0,6.0,6.0,6.0,6.0,PH1007,Mahmudul Hasan,80.0,80.0,NaN,...,2024-04-01,Mr. Karim,Dhaka,Bangladesh,CSTU,NaN,A,Pass,Fail,Mahmudul
7,7.0,7.0,7.0,7.0,7.0,PH1008,Nadia Islam,81.0,81.0,85.0,...,2024-04-22,Ms. Salma,Chattogram,Bangladesh,CSTU,247.0,A,Pass,Fail,Nadia
8,8.0,8.0,8.0,8.0,8.0,PH1009,Omar Faruq,72.0,72.0,76.0,...,2024-05-16,Mr. David,Dhaka,Bangladesh,CSTU,220.0,A,Pass,Pass,Omar
9,9.0,9.0,9.0,9.0,9.0,PH1010,Priya Sharma,89.0,89.0,88.0,...,2024-05-20,Ms. Salma,Sylhet,Bangladesh,CSTU,266.0,A,Pass,Fail,Priya
10,10.0,10.0,10.0,10.0,10.0,PH1011,Rahim Sheikh,84.0,NaN,91.0,...,2024-06-11,Mr. Karim,Khulna,Bangladesh,CSTU,NaN,A,Pass,Fail,Rahim
11,11.0,11.0,11.0,11.0,11.0,PH1012,Sadia Chowdhury,85.0,85.0,87.0,...,2024-06-14,Ms. Salma,Chattogram,Bangladesh,CSTU,257.0,A,Pass,Fail,Sadia
12,12.0,12.0,12.0,12.0,12.0,PH1013,Tanvir Ahmed,75.0,75.0,79.0,...,2024-07-02,Mr. David,Dhaka,Bangladesh,CSTU,229.0,A,Pass,Pass,Tanvir
13,13.0,13.0,13.0,13.0,13.0,PH1014,Urmi Akter,84.0,NaN,NaN,...,2024-07-09,Ms. Salma,Rajshahi,Bangladesh,CSTU,NaN,A,Pass,Fail,Urmi
14,14.0,14.0,14.0,14.0,14.0,PH1015,Wahiduzzaman,86.0,86.0,84.0,...,2024-08-18,Mr. Karim,Dhaka,Bangladesh,CSTU,256.0,A,Pass,Fail,Wahiduzzaman
15,15.0,15.0,15.0,15.0,15.0,PH1016,Ziaur Rahman,94.0,94.0,NaN,...,2024-08-21,Ms. Salma,Chattogram,Bangladesh,CSTU,NaN,A+,Pass,Fail,Ziaur
16,16.0,16.0,16.0,16.0,16.0,PH1017,Afsana Mimi,90.0,90.0,93.0,...,2025-09-01,Mr. Karim,Dhaka,Bangladesh,CSTU,273.0,A,Pass,Fail,Afsana
17,17.0,17.0,17.0,17.0,17.0,PH1018,Babul Ahmed,88.0,88.0,85.0,...,2025-09-05,Ms. Salma,Sylhet,Bangladesh,CSTU,261.0,A,Pass,Fail,Babul
18,18.0,18.0,18.0,18.0,18.0,PH1019,Faria Rahman,84.0,NaN,NaN,...,2025-09-15,Mr. David,Chattogram,Bangladesh,CSTU,NaN,A,Pass,Fail,Faria
19,19.0,19.0,19.0,19.0,19.0,PH1020,Nasir Khan,86.0,86.0,89.0,...,2025-10-02,Ms. Salma,Dhaka,Bangladesh,CSTU,261.0,A,Pass,Fail,Nasir
20,NaN,NaN,NaN,NaN,NaN,NaN,NaN,84.0,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [49]:
df['Algorithm Marks'].fillna(df['Algorithm Marks'].median(),inplace=True)
df

C:\Users\user\AppData\Local\Temp\ipykernel_19856\2905995484.py:1: FutureWarning: A value is trying to be set on a copy of a DataFrame or Series through chained assignment using an inplace method.
The behavior will change in pandas 3.0. This inplace method will never work because the intermediate object on which we are setting values always behaves as a copy.

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' or df[col] = df[col].method(value) instead, to perform the operation inplace on the original object.


  df['Algorithm Marks'].fillna(df['Algorithm Marks'].median(),inplace=True)

,Unnamed: 0.4,Unnamed: 0.3,Unnamed: 0.2,Unnamed: 0.1,Unnamed: 0,StudentID,FullName,Data Structure Marks,Algorithm Marks,Python Marks,...,EnrollmentDate,Instructor,Location,Country,University,Total Mark,DSA GPA,DSA PASS,pass in Python,Last name
0,0.0,0.0,0.0,0.0,0.0,PH1001,Alif Rahman,85.0,85.0,88.0,...,2024-01-15,Mr. Karim,Dhaka,Bangladesh,CSTU,258.0,A,Pass,Fail,Alif
1,1.0,1.0,1.0,1.0,1.0,PH1002,Fatima Akhter,92.0,92.0,NaN,...,2024-01-20,Ms. Salma,Chattogram,Bangladesh,CSTU,NaN,A+,Pass,Fail,Fatima
2,2.0,2.0,2.0,2.0,2.0,PH1003,Imran Hossain,88.0,88.0,85.0,...,2024-02-10,Mr. Karim,Dhaka,Bangladesh,CSTU,261.0,A,Pass,Fail,Imran
3,3.0,3.0,3.0,3.0,3.0,PH1004,Jannatul Ferdous,78.0,78.0,82.0,...,2024-02-12,Ms. Salma,Sylhet,Bangladesh,CSTU,238.0,A,Pass,Fail,Jannatul
4,4.0,4.0,4.0,4.0,4.0,PH1005,Kamal Uddin,84.0,85.5,95.0,...,2024-03-05,Mr. Karim,Chattogram,Bangladesh,CSTU,NaN,A,Pass,Fail,Kamal
5,5.0,5.0,5.0,5.0,5.0,PH1006,Laila Begum,75.0,75.0,78.0,...,2024-03-08,Ms. Salma,Rajshahi,Bangladesh,CSTU,228.0,A,Pass,Pass,Laila
6,6.0,6.0,6.0,6.0,6.0,PH1007,Mahmudul Hasan,80.0,80.0,NaN,...,2024-04-01,Mr. Karim,Dhaka,Bangladesh,CSTU,NaN,A,Pass,Fail,Mahmudul
7,7.0,7.0,7.0,7.0,7.0,PH1008,Nadia Islam,81.0,81.0,85.0,...,2024-04-22,Ms. Salma,Chattogram,Bangladesh,CSTU,247.0,A,Pass,Fail,Nadia
8,8.0,8.0,8.0,8.0,8.0,PH1009,Omar Faruq,72.0,72.0,76.0,...,2024-05-16,Mr. David,Dhaka,Bangladesh,CSTU,220.0,A,Pass,Pass,Omar
9,9.0,9.0,9.0,9.0,9.0,PH1010,Priya Sharma,89.0,89.0,88.0,...,2024-05-20,Ms. Salma,Sylhet,Bangladesh,CSTU,266.0,A,Pass,Fail,Priya
10,10.0,10.0,10.0,10.0,10.0,PH1011,Rahim Sheikh,84.0,85.5,91.0,...,2024-06-11,Mr. Karim,Khulna,Bangladesh,CSTU,NaN,A,Pass,Fail,Rahim
11,11.0,11.0,11.0,11.0,11.0,PH1012,Sadia Chowdhury,85.0,85.0,87.0,...,2024-06-14,Ms. Salma,Chattogram,Bangladesh,CSTU,257.0,A,Pass,Fail,Sadia
12,12.0,12.0,12.0,12.0,12.0,PH1013,Tanvir Ahmed,75.0,75.0,79.0,...,2024-07-02,Mr. David,Dhaka,Bangladesh,CSTU,229.0,A,Pass,Pass,Tanvir
13,13.0,13.0,13.0,13.0,13.0,PH1014,Urmi Akter,84.0,85.5,NaN,...,2024-07-09,Ms. Salma,Rajshahi,Bangladesh,CSTU,NaN,A,Pass,Fail,Urmi
14,14.0,14.0,14.0,14.0,14.0,PH1015,Wahiduzzaman,86.0,86.0,84.0,...,2024-08-18,Mr. Karim,Dhaka,Bangladesh,CSTU,256.0,A,Pass,Fail,Wahiduzzaman
15,15.0,15.0,15.0,15.0,15.0,PH1016,Ziaur Rahman,94.0,94.0,NaN,...,2024-08-21,Ms. Salma,Chattogram,Bangladesh,CSTU,NaN,A+,Pass,Fail,Ziaur
16,16.0,16.0,16.0,16.0,16.0,PH1017,Afsana Mimi,90.0,90.0,93.0,...,2025-09-01,Mr. Karim,Dhaka,Bangladesh,CSTU,273.0,A,Pass,Fail,Afsana
17,17.0,17.0,17.0,17.0,17.0,PH1018,Babul Ahmed,88.0,88.0,85.0,...,2025-09-05,Ms. Salma,Sylhet,Bangladesh,CSTU,261.0,A,Pass,Fail,Babul
18,18.0,18.0,18.0,18.0,18.0,PH1019,Faria Rahman,84.0,85.5,NaN,...,2025-09-15,Mr. David,Chattogram,Bangladesh,CSTU,NaN,A,Pass,Fail,Faria
19,19.0,19.0,19.0,19.0,19.0,PH1020,Nasir Khan,86.0,86.0,89.0,...,2025-10-02,Ms. Salma,Dhaka,Bangladesh,CSTU,261.0,A,Pass,Fail,Nasir
20,NaN,NaN,NaN,NaN,NaN,NaN,NaN,84.0,85.5,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

# Statistical Functions

In [50]:
df

,Unnamed: 0.4,Unnamed: 0.3,Unnamed: 0.2,Unnamed: 0.1,Unnamed: 0,StudentID,FullName,Data Structure Marks,Algorithm Marks,Python Marks,...,EnrollmentDate,Instructor,Location,Country,University,Total Mark,DSA GPA,DSA PASS,pass in Python,Last name
0,0.0,0.0,0.0,0.0,0.0,PH1001,Alif Rahman,85.0,85.0,88.0,...,2024-01-15,Mr. Karim,Dhaka,Bangladesh,CSTU,258.0,A,Pass,Fail,Alif
1,1.0,1.0,1.0,1.0,1.0,PH1002,Fatima Akhter,92.0,92.0,NaN,...,2024-01-20,Ms. Salma,Chattogram,Bangladesh,CSTU,NaN,A+,Pass,Fail,Fatima
2,2.0,2.0,2.0,2.0,2.0,PH1003,Imran Hossain,88.0,88.0,85.0,...,2024-02-10,Mr. Karim,Dhaka,Bangladesh,CSTU,261.0,A,Pass,Fail,Imran
3,3.0,3.0,3.0,3.0,3.0,PH1004,Jannatul Ferdous,78.0,78.0,82.0,...,2024-02-12,Ms. Salma,Sylhet,Bangladesh,CSTU,238.0,A,Pass,Fail,Jannatul
4,4.0,4.0,4.0,4.0,4.0,PH1005,Kamal Uddin,84.0,85.5,95.0,...,2024-03-05,Mr. Karim,Chattogram,Bangladesh,CSTU,NaN,A,Pass,Fail,Kamal
5,5.0,5.0,5.0,5.0,5.0,PH1006,Laila Begum,75.0,75.0,78.0,...,2024-03-08,Ms. Salma,Rajshahi,Bangladesh,CSTU,228.0,A,Pass,Pass,Laila
6,6.0,6.0,6.0,6.0,6.0,PH1007,Mahmudul Hasan,80.0,80.0,NaN,...,2024-04-01,Mr. Karim,Dhaka,Bangladesh,CSTU,NaN,A,Pass,Fail,Mahmudul
7,7.0,7.0,7.0,7.0,7.0,PH1008,Nadia Islam,81.0,81.0,85.0,...,2024-04-22,Ms. Salma,Chattogram,Bangladesh,CSTU,247.0,A,Pass,Fail,Nadia
8,8.0,8.0,8.0,8.0,8.0,PH1009,Omar Faruq,72.0,72.0,76.0,...,2024-05-16,Mr. David,Dhaka,Bangladesh,CSTU,220.0,A,Pass,Pass,Omar
9,9.0,9.0,9.0,9.0,9.0,PH1010,Priya Sharma,89.0,89.0,88.0,...,2024-05-20,Ms. Salma,Sylhet,Bangladesh,CSTU,266.0,A,Pass,Fail,Priya
10,10.0,10.0,10.0,10.0,10.0,PH1011,Rahim Sheikh,84.0,85.5,91.0,...,2024-06-11,Mr. Karim,Khulna,Bangladesh,CSTU,NaN,A,Pass,Fail,Rahim
11,11.0,11.0,11.0,11.0,11.0,PH1012,Sadia Chowdhury,85.0,85.0,87.0,...,2024-06-14,Ms. Salma,Chattogram,Bangladesh,CSTU,257.0,A,Pass,Fail,Sadia
12,12.0,12.0,12.0,12.0,12.0,PH1013,Tanvir Ahmed,75.0,75.0,79.0,...,2024-07-02,Mr. David,Dhaka,Bangladesh,CSTU,229.0,A,Pass,Pass,Tanvir
13,13.0,13.0,13.0,13.0,13.0,PH1014,Urmi Akter,84.0,85.5,NaN,...,2024-07-09,Ms. Salma,Rajshahi,Bangladesh,CSTU,NaN,A,Pass,Fail,Urmi
14,14.0,14.0,14.0,14.0,14.0,PH1015,Wahiduzzaman,86.0,86.0,84.0,...,2024-08-18,Mr. Karim,Dhaka,Bangladesh,CSTU,256.0,A,Pass,Fail,Wahiduzzaman
15,15.0,15.0,15.0,15.0,15.0,PH1016,Ziaur Rahman,94.0,94.0,NaN,...,2024-08-21,Ms. Salma,Chattogram,Bangladesh,CSTU,NaN,A+,Pass,Fail,Ziaur
16,16.0,16.0,16.0,16.0,16.0,PH1017,Afsana Mimi,90.0,90.0,93.0,...,2025-09-01,Mr. Karim,Dhaka,Bangladesh,CSTU,273.0,A,Pass,Fail,Afsana
17,17.0,17.0,17.0,17.0,17.0,PH1018,Babul Ahmed,88.0,88.0,85.0,...,2025-09-05,Ms. Salma,Sylhet,Bangladesh,CSTU,261.0,A,Pass,Fail,Babul
18,18.0,18.0,18.0,18.0,18.0,PH1019,Faria Rahman,84.0,85.5,NaN,...,2025-09-15,Mr. David,Chattogram,Bangladesh,CSTU,NaN,A,Pass,Fail,Faria
19,19.0,19.0,19.0,19.0,19.0,PH1020,Nasir Khan,86.0,86.0,89.0,...,2025-10-02,Ms. Salma,Dhaka,Bangladesh,CSTU,261.0,A,Pass,Fail,Nasir
20,NaN,NaN,NaN,NaN,NaN,NaN,NaN,84.0,85.5,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [51]:
df.dropna()

,Unnamed: 0.4,Unnamed: 0.3,Unnamed: 0.2,Unnamed: 0.1,Unnamed: 0,StudentID,FullName,Data Structure Marks,Algorithm Marks,Python Marks,...,EnrollmentDate,Instructor,Location,Country,University,Total Mark,DSA GPA,DSA PASS,pass in Python,Last name
0,0.0,0.0,0.0,0.0,0.0,PH1001,Alif Rahman,85.0,85.0,88.0,...,2024-01-15,Mr. Karim,Dhaka,Bangladesh,CSTU,258.0,A,Pass,Fail,Alif
2,2.0,2.0,2.0,2.0,2.0,PH1003,Imran Hossain,88.0,88.0,85.0,...,2024-02-10,Mr. Karim,Dhaka,Bangladesh,CSTU,261.0,A,Pass,Fail,Imran
3,3.0,3.0,3.0,3.0,3.0,PH1004,Jannatul Ferdous,78.0,78.0,82.0,...,2024-02-12,Ms. Salma,Sylhet,Bangladesh,CSTU,238.0,A,Pass,Fail,Jannatul
5,5.0,5.0,5.0,5.0,5.0,PH1006,Laila Begum,75.0,75.0,78.0,...,2024-03-08,Ms. Salma,Rajshahi,Bangladesh,CSTU,228.0,A,Pass,Pass,Laila
7,7.0,7.0,7.0,7.0,7.0,PH1008,Nadia Islam,81.0,81.0,85.0,...,2024-04-22,Ms. Salma,Chattogram,Bangladesh,CSTU,247.0,A,Pass,Fail,Nadia
8,8.0,8.0,8.0,8.0,8.0,PH1009,Omar Faruq,72.0,72.0,76.0,...,2024-05-16,Mr. David,Dhaka,Bangladesh,CSTU,220.0,A,Pass,Pass,Omar
9,9.0,9.0,9.0,9.0,9.0,PH1010,Priya Sharma,89.0,89.0,88.0,...,2024-05-20,Ms. Salma,Sylhet,Bangladesh,CSTU,266.0,A,Pass,Fail,Priya
11,11.0,11.0,11.0,11.0,11.0,PH1012,Sadia Chowdhury,85.0,85.0,87.0,...,2024-06-14,Ms. Salma,Chattogram,Bangladesh,CSTU,257.0,A,Pass,Fail,Sadia
12,12.0,12.0,12.0,12.0,12.0,PH1013,Tanvir Ahmed,75.0,75.0,79.0,...,2024-07-02,Mr. David,Dhaka,Bangladesh,CSTU,229.0,A,Pass,Pass,Tanvir
14,14.0,14.0,14.0,14.0,14.0,PH1015,Wahiduzzaman,86.0,86.0,84.0,...,2024-08-18,Mr. Karim,Dhaka,Bangladesh,CSTU,256.0,A,Pass,Fail,Wahiduzzaman
16,16.0,16.0,16.0,16.0,16.0,PH1017,Afsana Mimi,90.0,90.0,93.0,...,2025-09-01,Mr. Karim,Dhaka,Bangladesh,CSTU,273.0,A,Pass,Fail,Afsana
17,17.0,17.0,17.0,17.0,17.0,PH1018,Babul Ahmed,88.0,88.0,85.0,...,2025-09-05,Ms. Salma,Sylhet,Bangladesh,CSTU,261.0,A,Pass,Fail,Babul
19,19.0,19.0,19.0,19.0,19.0,PH1020,Nasir Khan,86.0,86.0,89.0,...,2025-10-02,Ms. Salma,Dhaka,Bangladesh,CSTU,261.0,A,Pass,Fail,Nasir

In [52]:
#sum
df['Data Structure Marks'].sum()

np.float64(1764.0)

In [53]:
df['Data Structure Marks'].min()

72.0

In [54]:
df['Data Structure Marks'].max()

94.0

In [55]:
df['Data Structure Marks'].median()

84.0

In [56]:
df['Data Structure Marks'].mode()

0    84.0
Name: Data Structure Marks, dtype: float64

In [57]:
df['Data Structure Marks'].std()

5.630275304103699

In [58]:
df[['Data Structure Marks','Python Marks']].corr()

                      Data Structure Marks  Python Marks
Data Structure Marks              1.000000      0.770016
Python Marks                      0.770016      1.000000

In [59]:
# Row-wise Sum
df[['Data Structure Marks','Python Marks']].sum(axis=1)

0     173.0
1      92.0
2     173.0
3     160.0
4     179.0
5     153.0
6      80.0
7     166.0
8     148.0
9     177.0
10    175.0
11    172.0
12    154.0
13     84.0
14    170.0
15     94.0
16    183.0
17    173.0
18     84.0
19    175.0
20     84.0
dtype: float64

In [60]:
#column wise sum
df[['Data Structure Marks','Python Marks']].sum()

Data Structure Marks    1764.0
Python Marks            1285.0
dtype: float64

In [61]:
df['Total Marks']=df.iloc[::,6:8].sum(axis=1)
df

TypeError: can only concatenate str (not "float") to str

In [ ]:
df.describe()

,Unnamed: 0.3,Unnamed: 0.2,Unnamed: 0.1,Unnamed: 0,Data Structure Marks,Algorithm Marks,Python Marks,Total Mark,Total Marks
count,20.00000,20.00000,20.00000,20.00000,21.000000,21.000000,15.000000,0.0,21.000000
mean,9.50000,9.50000,9.50000,9.50000,84.000000,84.357143,85.666667,NaN,168.357143
std,5.91608,5.91608,5.91608,5.91608,5.630275,5.668207,5.394000,NaN,11.279564
min,0.00000,0.00000,0.00000,0.00000,72.000000,72.000000,76.000000,NaN,144.000000
25%,4.75000,4.75000,4.75000,4.75000,81.000000,81.000000,83.000000,NaN,162.000000
50%,9.50000,9.50000,9.50000,9.50000,84.000000,85.500000,85.000000,NaN,169.500000
75%,14.25000,14.25000,14.25000,14.25000,88.000000,88.000000,88.500000,NaN,176.000000
max,19.00000,19.00000,19.00000,19.00000,94.000000,94.000000,95.000000,NaN,188.000000

In [63]:
import pandas as np
df=pd.read_csv('student_data.csv')
df

,Unnamed: 0.4,Unnamed: 0.3,Unnamed: 0.2,Unnamed: 0.1,Unnamed: 0,StudentID,FullName,Data Structure Marks,Algorithm Marks,Python Marks,...,EnrollmentDate,Instructor,Location,Country,University,Total Mark,DSA GPA,DSA PASS,pass in Python,Last name
0,0,0,0,0,0,PH1001,Alif Rahman,85.0,85.0,88.0,...,2024-01-15,Mr. Karim,Dhaka,Bangladesh,CSTU,258.0,A,Pass,Fail,Alif
1,1,1,1,1,1,PH1002,Fatima Akhter,92.0,92.0,NaN,...,2024-01-20,Ms. Salma,Chattogram,Bangladesh,CSTU,NaN,A+,Pass,Fail,Fatima
2,2,2,2,2,2,PH1003,Imran Hossain,88.0,88.0,85.0,...,2024-02-10,Mr. Karim,Dhaka,Bangladesh,CSTU,261.0,A,Pass,Fail,Imran
3,3,3,3,3,3,PH1004,Jannatul Ferdous,78.0,78.0,82.0,...,2024-02-12,Ms. Salma,Sylhet,Bangladesh,CSTU,238.0,A,Pass,Fail,Jannatul
4,4,4,4,4,4,PH1005,Kamal Uddin,NaN,NaN,95.0,...,2024-03-05,Mr. Karim,Chattogram,Bangladesh,CSTU,NaN,A,Pass,Fail,Kamal
5,5,5,5,5,5,PH1006,Laila Begum,75.0,75.0,78.0,...,2024-03-08,Ms. Salma,Rajshahi,Bangladesh,CSTU,228.0,A,Pass,Pass,Laila
6,6,6,6,6,6,PH1007,Mahmudul Hasan,80.0,80.0,NaN,...,2024-04-01,Mr. Karim,Dhaka,Bangladesh,CSTU,NaN,A,Pass,Fail,Mahmudul
7,7,7,7,7,7,PH1008,Nadia Islam,81.0,81.0,85.0,...,2024-04-22,Ms. Salma,Chattogram,Bangladesh,CSTU,247.0,A,Pass,Fail,Nadia
8,8,8,8,8,8,PH1009,Omar Faruq,72.0,72.0,76.0,...,2024-05-16,Mr. David,Dhaka,Bangladesh,CSTU,220.0,A,Pass,Pass,Omar
9,9,9,9,9,9,PH1010,Priya Sharma,89.0,89.0,88.0,...,2024-05-20,Ms. Salma,Sylhet,Bangladesh,CSTU,266.0,A,Pass,Fail,Priya
10,10,10,10,10,10,PH1011,Rahim Sheikh,NaN,NaN,91.0,...,2024-06-11,Mr. Karim,Khulna,Bangladesh,CSTU,NaN,A,Pass,Fail,Rahim
11,11,11,11,11,11,PH1012,Sadia Chowdhury,85.0,85.0,87.0,...,2024-06-14,Ms. Salma,Chattogram,Bangladesh,CSTU,257.0,A,Pass,Fail,Sadia
12,12,12,12,12,12,PH1013,Tanvir Ahmed,75.0,75.0,79.0,...,2024-07-02,Mr. David,Dhaka,Bangladesh,CSTU,229.0,A,Pass,Pass,Tanvir
13,13,13,13,13,13,PH1014,Urmi Akter,NaN,NaN,NaN,...,2024-07-09,Ms. Salma,Rajshahi,Bangladesh,CSTU,NaN,A,Pass,Fail,Urmi
14,14,14,14,14,14,PH1015,Wahiduzzaman,86.0,86.0,84.0,...,2024-08-18,Mr. Karim,Dhaka,Bangladesh,CSTU,256.0,A,Pass,Fail,Wahiduzzaman
15,15,15,15,15,15,PH1016,Ziaur Rahman,94.0,94.0,NaN,...,2024-08-21,Ms. Salma,Chattogram,Bangladesh,CSTU,NaN,A+,Pass,Fail,Ziaur
16,16,16,16,16,16,PH1017,Afsana Mimi,90.0,90.0,93.0,...,2025-09-01,Mr. Karim,Dhaka,Bangladesh,CSTU,273.0,A,Pass,Fail,Afsana
17,17,17,17,17,17,PH1018,Babul Ahmed,88.0,88.0,85.0,...,2025-09-05,Ms. Salma,Sylhet,Bangladesh,CSTU,261.0,A,Pass,Fail,Babul
18,18,18,18,18,18,PH1019,Faria Rahman,NaN,NaN,NaN,...,2025-09-15,Mr. David,Chattogram,Bangladesh,CSTU,NaN,A,Pass,Fail,Faria
19,19,19,19,19,19,PH1020,Nasir Khan,86.0,86.0,89.0,...,2025-10-02,Ms. Salma,Dhaka,Bangladesh,CSTU,261.0,A,Pass,Fail,Nasir

In [70]:
df.dropna(inplace=True)

In [71]:
#min max scaling
mn=df['Total Mark'].min()
mx=df['Total Mark'].max()

df['scalel_Marks']=df['Total Mark'].apply(lambda x: (x-mn)/(mx-mn))
df

,Unnamed: 0.4,Unnamed: 0.3,Unnamed: 0.2,Unnamed: 0.1,Unnamed: 0,StudentID,FullName,Data Structure Marks,Algorithm Marks,Python Marks,...,Instructor,Location,Country,University,Total Mark,DSA GPA,DSA PASS,pass in Python,Last name,scalel_Marks
0,0,0,0,0,0,PH1001,Alif Rahman,85.0,85.0,88.0,...,Mr. Karim,Dhaka,Bangladesh,CSTU,258.0,A,Pass,Fail,Alif,0.716981
2,2,2,2,2,2,PH1003,Imran Hossain,88.0,88.0,85.0,...,Mr. Karim,Dhaka,Bangladesh,CSTU,261.0,A,Pass,Fail,Imran,0.773585
3,3,3,3,3,3,PH1004,Jannatul Ferdous,78.0,78.0,82.0,...,Ms. Salma,Sylhet,Bangladesh,CSTU,238.0,A,Pass,Fail,Jannatul,0.339623
5,5,5,5,5,5,PH1006,Laila Begum,75.0,75.0,78.0,...,Ms. Salma,Rajshahi,Bangladesh,CSTU,228.0,A,Pass,Pass,Laila,0.150943
7,7,7,7,7,7,PH1008,Nadia Islam,81.0,81.0,85.0,...,Ms. Salma,Chattogram,Bangladesh,CSTU,247.0,A,Pass,Fail,Nadia,0.509434
8,8,8,8,8,8,PH1009,Omar Faruq,72.0,72.0,76.0,...,Mr. David,Dhaka,Bangladesh,CSTU,220.0,A,Pass,Pass,Omar,0.000000
9,9,9,9,9,9,PH1010,Priya Sharma,89.0,89.0,88.0,...,Ms. Salma,Sylhet,Bangladesh,CSTU,266.0,A,Pass,Fail,Priya,0.867925
11,11,11,11,11,11,PH1012,Sadia Chowdhury,85.0,85.0,87.0,...,Ms. Salma,Chattogram,Bangladesh,CSTU,257.0,A,Pass,Fail,Sadia,0.698113
12,12,12,12,12,12,PH1013,Tanvir Ahmed,75.0,75.0,79.0,...,Mr. David,Dhaka,Bangladesh,CSTU,229.0,A,Pass,Pass,Tanvir,0.169811
14,14,14,14,14,14,PH1015,Wahiduzzaman,86.0,86.0,84.0,...,Mr. Karim,Dhaka,Bangladesh,CSTU,256.0,A,Pass,Fail,Wahiduzzaman,0.679245
16,16,16,16,16,16,PH1017,Afsana Mimi,90.0,90.0,93.0,...,Mr. Karim,Dhaka,Bangladesh,CSTU,273.0,A,Pass,Fail,Afsana,1.000000
17,17,17,17,17,17,PH1018,Babul Ahmed,88.0,88.0,85.0,...,Ms. Salma,Sylhet,Bangladesh,CSTU,261.0,A,Pass,Fail,Babul,0.773585
19,19,19,19,19,19,PH1020,Nasir Khan,86.0,86.0,89.0,...,Ms. Salma,Dhaka,Bangladesh,CSTU,261.0,A,Pass,Fail,Nasir,0.773585

In [79]:
def grading_systems(marks):
    if marks>=260:
        return 'A+'
    elif marks>=250:
        return 'A'
    else :
        return 'C'
    
    df['Grade']=df['Total Mark'].apply(grading_systems)
    df

In [80]:
df

,Unnamed: 0.4,Unnamed: 0.3,Unnamed: 0.2,Unnamed: 0.1,Unnamed: 0,StudentID,FullName,Data Structure Marks,Algorithm Marks,Python Marks,...,Location,Country,University,Total Mark,DSA GPA,DSA PASS,pass in Python,Last name,scalel_Marks,Grade
0,0,0,0,0,0,PH1001,Alif Rahman,85.0,85.0,88.0,...,Dhaka,Bangladesh,CSTU,258.0,A,Pass,Fail,Alif,0.716981,A
2,2,2,2,2,2,PH1003,Imran Hossain,88.0,88.0,85.0,...,Dhaka,Bangladesh,CSTU,261.0,A,Pass,Fail,Imran,0.773585,A+
3,3,3,3,3,3,PH1004,Jannatul Ferdous,78.0,78.0,82.0,...,Sylhet,Bangladesh,CSTU,238.0,A,Pass,Fail,Jannatul,0.339623,A-
5,5,5,5,5,5,PH1006,Laila Begum,75.0,75.0,78.0,...,Rajshahi,Bangladesh,CSTU,228.0,A,Pass,Pass,Laila,0.150943,A-
7,7,7,7,7,7,PH1008,Nadia Islam,81.0,81.0,85.0,...,Chattogram,Bangladesh,CSTU,247.0,A,Pass,Fail,Nadia,0.509434,A-
8,8,8,8,8,8,PH1009,Omar Faruq,72.0,72.0,76.0,...,Dhaka,Bangladesh,CSTU,220.0,A,Pass,Pass,Omar,0.000000,A-
9,9,9,9,9,9,PH1010,Priya Sharma,89.0,89.0,88.0,...,Sylhet,Bangladesh,CSTU,266.0,A,Pass,Fail,Priya,0.867925,A+
11,11,11,11,11,11,PH1012,Sadia Chowdhury,85.0,85.0,87.0,...,Chattogram,Bangladesh,CSTU,257.0,A,Pass,Fail,Sadia,0.698113,A
12,12,12,12,12,12,PH1013,Tanvir Ahmed,75.0,75.0,79.0,...,Dhaka,Bangladesh,CSTU,229.0,A,Pass,Pass,Tanvir,0.169811,A-
14,14,14,14,14,14,PH1015,Wahiduzzaman,86.0,86.0,84.0,...,Dhaka,Bangladesh,CSTU,256.0,A,Pass,Fail,Wahiduzzaman,0.679245,A
16,16,16,16,16,16,PH1017,Afsana Mimi,90.0,90.0,93.0,...,Dhaka,Bangladesh,CSTU,273.0,A,Pass,Fail,Afsana,1.000000,A+
17,17,17,17,17,17,PH1018,Babul Ahmed,88.0,88.0,85.0,...,Sylhet,Bangladesh,CSTU,261.0,A,Pass,Fail,Babul,0.773585,A+
19,19,19,19,19,19,PH1020,Nasir Khan,86.0,86.0,89.0,...,Dhaka,Bangladesh,CSTU,261.0,A,Pass,Fail,Nasir,0.773585,A+

In [82]:
def making_system(df):
    a=df['Data Structure Marks']*2
    b=df['Python Marks']*3
    c=df['Algorithm Marks']*4
    
    return a+b+c

df['Exceptional_marks']=df.apply(making_system,axis=1)
df

,Unnamed: 0.4,Unnamed: 0.3,Unnamed: 0.2,Unnamed: 0.1,Unnamed: 0,StudentID,FullName,Data Structure Marks,Algorithm Marks,Python Marks,...,Country,University,Total Mark,DSA GPA,DSA PASS,pass in Python,Last name,scalel_Marks,Grade,Exceptional_marks
0,0,0,0,0,0,PH1001,Alif Rahman,85.0,85.0,88.0,...,Bangladesh,CSTU,258.0,A,Pass,Fail,Alif,0.716981,A,774.0
2,2,2,2,2,2,PH1003,Imran Hossain,88.0,88.0,85.0,...,Bangladesh,CSTU,261.0,A,Pass,Fail,Imran,0.773585,A+,783.0
3,3,3,3,3,3,PH1004,Jannatul Ferdous,78.0,78.0,82.0,...,Bangladesh,CSTU,238.0,A,Pass,Fail,Jannatul,0.339623,A-,714.0
5,5,5,5,5,5,PH1006,Laila Begum,75.0,75.0,78.0,...,Bangladesh,CSTU,228.0,A,Pass,Pass,Laila,0.150943,A-,684.0
7,7,7,7,7,7,PH1008,Nadia Islam,81.0,81.0,85.0,...,Bangladesh,CSTU,247.0,A,Pass,Fail,Nadia,0.509434,A-,741.0
8,8,8,8,8,8,PH1009,Omar Faruq,72.0,72.0,76.0,...,Bangladesh,CSTU,220.0,A,Pass,Pass,Omar,0.000000,A-,660.0
9,9,9,9,9,9,PH1010,Priya Sharma,89.0,89.0,88.0,...,Bangladesh,CSTU,266.0,A,Pass,Fail,Priya,0.867925,A+,798.0
11,11,11,11,11,11,PH1012,Sadia Chowdhury,85.0,85.0,87.0,...,Bangladesh,CSTU,257.0,A,Pass,Fail,Sadia,0.698113,A,771.0
12,12,12,12,12,12,PH1013,Tanvir Ahmed,75.0,75.0,79.0,...,Bangladesh,CSTU,229.0,A,Pass,Pass,Tanvir,0.169811,A-,687.0
14,14,14,14,14,14,PH1015,Wahiduzzaman,86.0,86.0,84.0,...,Bangladesh,CSTU,256.0,A,Pass,Fail,Wahiduzzaman,0.679245,A,768.0
16,16,16,16,16,16,PH1017,Afsana Mimi,90.0,90.0,93.0,...,Bangladesh,CSTU,273.0,A,Pass,Fail,Afsana,1.000000,A+,819.0
17,17,17,17,17,17,PH1018,Babul Ahmed,88.0,88.0,85.0,...,Bangladesh,CSTU,261.0,A,Pass,Fail,Babul,0.773585,A+,783.0
19,19,19,19,19,19,PH1020,Nasir Khan,86.0,86.0,89.0,...,Bangladesh,CSTU,261.0,A,Pass,Fail,Nasir,0.773585,A+,783.0

# datetime and time delta

In [83]:
df = pd.read_csv('student_completed_data.csv')
df

,StudentID,FullName,CompletionStatus,EnrollmentDate,FinishedDate,Instructor,Location,Total Marks
0,PH0001,Alif Rahman,Completed,2024-09-01,2024-12-23,Ms. Salma,Khulna,300
1,PH0002,Fatima Akhter,Completed,2024-08-11,2024-11-07,Mr. Karim,Dhaka,271
2,PH0003,Imran Hossain,Completed,2024-05-08,2024-08-08,Ms. Salma,Dhaka,269
3,PH0004,Jannatul Ferdous,Completed,2024-07-05,2024-09-23,Mr. Karim,Khulna,270
4,PH0005,Kamal Uddin,Completed,2024-02-01,2024-04-17,Mr. David,Sylhet,254
5,PH0006,Laila Begum,Completed,2024-09-07,2024-12-31,Mr. David,Khulna,272
6,PH0007,Mahmudul Hasan,Completed,2024-06-07,2024-07-20,Mr. David,Chattogram,249
7,PH0008,Nadia Islam,Completed,2024-03-22,2024-05-01,Ms. Salma,Khulna,246
8,PH0009,Omar Faruq,Completed,2024-02-12,2024-06-08,Mr. Karim,Dhaka,291
9,PH0010,Priya Sharma,Completed,2024-06-19,2024-08-19,Mr. David,Dhaka,286
10,PH0011,Rahim Sheikh,Completed,2024-03-14,2024-06-11,Mr. Karim,Sylhet,283
11,PH0012,Sadia Chowdhury,Completed,2024-08-04,2024-10-25,Mr. Karim,Sylhet,266
12,PH0013,Tanvir Ahmed,Completed,2024-06-07,2024-08-03,Mr. David,Dhaka,248
13,PH0014,Urmi Akter,Completed,2024-01-04,2024-03-23,Mr. David,Sylhet,285
14,PH0015,Wahiduzzaman,Completed,2024-02-22,2024-05-16,Mr. David,Rajshahi,291
15,PH0016,Ziaur Rahman,Completed,2024-03-23,2024-06-21,Ms. Salma,Rajshahi,234
16,PH0017,Afsana Mimi,Completed,2024-01-18,2024-03-16,Mr. David,Khulna,236
17,PH0018,Babul Ahmed,Completed,2024-06-23,2024-09-20,Mr. David,Dhaka,278
18,PH0019,Faria Rahman,Completed,2024-04-19,2024-08-17,Mr. Karim,Sylhet,277
19,PH0020,Tariq Hasan,Completed,2024-07-21,2024-10-11,Mr. Karim,Khulna,253

In [84]:
df['EnrollmentDate']

0     2024-09-01
1     2024-08-11
2     2024-05-08
3     2024-07-05
4     2024-02-01
5     2024-09-07
6     2024-06-07
7     2024-03-22
8     2024-02-12
9     2024-06-19
10    2024-03-14
11    2024-08-04
12    2024-06-07
13    2024-01-04
14    2024-02-22
15    2024-03-23
16    2024-01-18
17    2024-06-23
18    2024-04-19
19    2024-07-21
Name: EnrollmentDate, dtype: object

In [86]:
df['EnrollmentDate']=pd.to_datetime(df['EnrollmentDate'])
df['EnrollmentDate']

0    2024-09-01
1    2024-08-11
2    2024-05-08
3    2024-07-05
4    2024-02-01
5    2024-09-07
6    2024-06-07
7    2024-03-22
8    2024-02-12
9    2024-06-19
10   2024-03-14
11   2024-08-04
12   2024-06-07
13   2024-01-04
14   2024-02-22
15   2024-03-23
16   2024-01-18
17   2024-06-23
18   2024-04-19
19   2024-07-21
Name: EnrollmentDate, dtype: datetime64[ns]

In [87]:
df['EnrollmentDate']

0    2024-09-01
1    2024-08-11
2    2024-05-08
3    2024-07-05
4    2024-02-01
5    2024-09-07
6    2024-06-07
7    2024-03-22
8    2024-02-12
9    2024-06-19
10   2024-03-14
11   2024-08-04
12   2024-06-07
13   2024-01-04
14   2024-02-22
15   2024-03-23
16   2024-01-18
17   2024-06-23
18   2024-04-19
19   2024-07-21
Name: EnrollmentDate, dtype: datetime64[ns]

In [94]:
df['Enrollment year']=df['EnrollmentDate'].dt.year

In [95]:
df['Enrollment Date']=df['EnrollmentDate'].dt.day

In [96]:
df

,StudentID,FullName,CompletionStatus,EnrollmentDate,FinishedDate,Instructor,Location,Total Marks,Enrollment year,Enrollment Date
0,PH0001,Alif Rahman,Completed,1970-01-01 00:00:00.000002024,2024-12-23,Ms. Salma,Khulna,300,1970,1
1,PH0002,Fatima Akhter,Completed,1970-01-01 00:00:00.000002024,2024-11-07,Mr. Karim,Dhaka,271,1970,1
2,PH0003,Imran Hossain,Completed,1970-01-01 00:00:00.000002024,2024-08-08,Ms. Salma,Dhaka,269,1970,1
3,PH0004,Jannatul Ferdous,Completed,1970-01-01 00:00:00.000002024,2024-09-23,Mr. Karim,Khulna,270,1970,1
4,PH0005,Kamal Uddin,Completed,1970-01-01 00:00:00.000002024,2024-04-17,Mr. David,Sylhet,254,1970,1
5,PH0006,Laila Begum,Completed,1970-01-01 00:00:00.000002024,2024-12-31,Mr. David,Khulna,272,1970,1
6,PH0007,Mahmudul Hasan,Completed,1970-01-01 00:00:00.000002024,2024-07-20,Mr. David,Chattogram,249,1970,1
7,PH0008,Nadia Islam,Completed,1970-01-01 00:00:00.000002024,2024-05-01,Ms. Salma,Khulna,246,1970,1
8,PH0009,Omar Faruq,Completed,1970-01-01 00:00:00.000002024,2024-06-08,Mr. Karim,Dhaka,291,1970,1
9,PH0010,Priya Sharma,Completed,1970-01-01 00:00:00.000002024,2024-08-19,Mr. David,Dhaka,286,1970,1
10,PH0011,Rahim Sheikh,Completed,1970-01-01 00:00:00.000002024,2024-06-11,Mr. Karim,Sylhet,283,1970,1
11,PH0012,Sadia Chowdhury,Completed,1970-01-01 00:00:00.000002024,2024-10-25,Mr. Karim,Sylhet,266,1970,1
12,PH0013,Tanvir Ahmed,Completed,1970-01-01 00:00:00.000002024,2024-08-03,Mr. David,Dhaka,248,1970,1
13,PH0014,Urmi Akter,Completed,1970-01-01 00:00:00.000002024,2024-03-23,Mr. David,Sylhet,285,1970,1
14,PH0015,Wahiduzzaman,Completed,1970-01-01 00:00:00.000002024,2024-05-16,Mr. David,Rajshahi,291,1970,1
15,PH0016,Ziaur Rahman,Completed,1970-01-01 00:00:00.000002024,2024-06-21,Ms. Salma,Rajshahi,234,1970,1
16,PH0017,Afsana Mimi,Completed,1970-01-01 00:00:00.000002024,2024-03-16,Mr. David,Khulna,236,1970,1
17,PH0018,Babul Ahmed,Completed,1970-01-01 00:00:00.000002024,2024-09-20,Mr. David,Dhaka,278,1970,1
18,PH0019,Faria Rahman,Completed,1970-01-01 00:00:00.000002024,2024-08-17,Mr. Karim,Sylhet,277,1970,1
19,PH0020,Tariq Hasan,Completed,1970-01-01 00:00:00.000002024,2024-10-11,Mr. Karim,Khulna,253,1970,1

In [97]:
df['FinishedDate']=pd.to_datetime(df['FinishedDate'])

In [99]:
df['Total time taken to finish']=df['FinishedDate']-df['EnrollmentDate']

In [100]:
df

,StudentID,FullName,CompletionStatus,EnrollmentDate,FinishedDate,Instructor,Location,Total Marks,Enrollment year,Enrollment Date,Total time taken to finish
0,PH0001,Alif Rahman,Completed,1970-01-01 00:00:00.000002024,2024-12-23,Ms. Salma,Khulna,300,1970,1,20079 days 23:59:59.999997976
1,PH0002,Fatima Akhter,Completed,1970-01-01 00:00:00.000002024,2024-11-07,Mr. Karim,Dhaka,271,1970,1,20033 days 23:59:59.999997976
2,PH0003,Imran Hossain,Completed,1970-01-01 00:00:00.000002024,2024-08-08,Ms. Salma,Dhaka,269,1970,1,19942 days 23:59:59.999997976
3,PH0004,Jannatul Ferdous,Completed,1970-01-01 00:00:00.000002024,2024-09-23,Mr. Karim,Khulna,270,1970,1,19988 days 23:59:59.999997976
4,PH0005,Kamal Uddin,Completed,1970-01-01 00:00:00.000002024,2024-04-17,Mr. David,Sylhet,254,1970,1,19829 days 23:59:59.999997976
5,PH0006,Laila Begum,Completed,1970-01-01 00:00:00.000002024,2024-12-31,Mr. David,Khulna,272,1970,1,20087 days 23:59:59.999997976
6,PH0007,Mahmudul Hasan,Completed,1970-01-01 00:00:00.000002024,2024-07-20,Mr. David,Chattogram,249,1970,1,19923 days 23:59:59.999997976
7,PH0008,Nadia Islam,Completed,1970-01-01 00:00:00.000002024,2024-05-01,Ms. Salma,Khulna,246,1970,1,19843 days 23:59:59.999997976
8,PH0009,Omar Faruq,Completed,1970-01-01 00:00:00.000002024,2024-06-08,Mr. Karim,Dhaka,291,1970,1,19881 days 23:59:59.999997976
9,PH0010,Priya Sharma,Completed,1970-01-01 00:00:00.000002024,2024-08-19,Mr. David,Dhaka,286,1970,1,19953 days 23:59:59.999997976
10,PH0011,Rahim Sheikh,Completed,1970-01-01 00:00:00.000002024,2024-06-11,Mr. Karim,Sylhet,283,1970,1,19884 days 23:59:59.999997976
11,PH0012,Sadia Chowdhury,Completed,1970-01-01 00:00:00.000002024,2024-10-25,Mr. Karim,Sylhet,266,1970,1,20020 days 23:59:59.999997976
12,PH0013,Tanvir Ahmed,Completed,1970-01-01 00:00:00.000002024,2024-08-03,Mr. David,Dhaka,248,1970,1,19937 days 23:59:59.999997976
13,PH0014,Urmi Akter,Completed,1970-01-01 00:00:00.000002024,2024-03-23,Mr. David,Sylhet,285,1970,1,19804 days 23:59:59.999997976
14,PH0015,Wahiduzzaman,Completed,1970-01-01 00:00:00.000002024,2024-05-16,Mr. David,Rajshahi,291,1970,1,19858 days 23:59:59.999997976
15,PH0016,Ziaur Rahman,Completed,1970-01-01 00:00:00.000002024,2024-06-21,Ms. Salma,Rajshahi,234,1970,1,19894 days 23:59:59.999997976
16,PH0017,Afsana Mimi,Completed,1970-01-01 00:00:00.000002024,2024-03-16,Mr. David,Khulna,236,1970,1,19797 days 23:59:59.999997976
17,PH0018,Babul Ahmed,Completed,1970-01-01 00:00:00.000002024,2024-09-20,Mr. David,Dhaka,278,1970,1,19985 days 23:59:59.999997976
18,PH0019,Faria Rahman,Completed,1970-01-01 00:00:00.000002024,2024-08-17,Mr. Karim,Sylhet,277,1970,1,19951 days 23:59:59.999997976
19,PH0020,Tariq Hasan,Completed,1970-01-01 00:00:00.000002024,2024-10-11,Mr. Karim,Khulna,253,1970,1,20006 days 23:59:59.999997976

# GroupBy

In [110]:
import numpy as np
df.loc[df['FullName']=='Afsana Mimi','Total Marks']=np.nan
df.loc[df['FullName']=='Jannatul Ferdous','Total Marks']=np.nan
df.loc[df['FullName']=='Mahmudul Hasan','Total Marks']=np.nan

In [111]:
df

,StudentID,FullName,CompletionStatus,EnrollmentDate,FinishedDate,Instructor,Location,Total Marks,Enrollment year,Enrollment Date,Total time taken to finish
0,PH0001,Alif Rahman,Completed,1970-01-01 00:00:00.000002024,2024-12-23,Ms. Salma,Khulna,300.0,1970,1,20079 days 23:59:59.999997976
1,PH0002,Fatima Akhter,Completed,1970-01-01 00:00:00.000002024,2024-11-07,Mr. Karim,Dhaka,271.0,1970,1,20033 days 23:59:59.999997976
2,PH0003,Imran Hossain,Completed,1970-01-01 00:00:00.000002024,2024-08-08,Ms. Salma,Dhaka,269.0,1970,1,19942 days 23:59:59.999997976
3,PH0004,Jannatul Ferdous,Completed,1970-01-01 00:00:00.000002024,2024-09-23,Mr. Karim,Khulna,NaN,1970,1,19988 days 23:59:59.999997976
4,PH0005,Kamal Uddin,Completed,1970-01-01 00:00:00.000002024,2024-04-17,Mr. David,Sylhet,254.0,1970,1,19829 days 23:59:59.999997976
5,PH0006,Laila Begum,Completed,1970-01-01 00:00:00.000002024,2024-12-31,Mr. David,Khulna,272.0,1970,1,20087 days 23:59:59.999997976
6,PH0007,Mahmudul Hasan,Completed,1970-01-01 00:00:00.000002024,2024-07-20,Mr. David,Chattogram,NaN,1970,1,19923 days 23:59:59.999997976
7,PH0008,Nadia Islam,Completed,1970-01-01 00:00:00.000002024,2024-05-01,Ms. Salma,Khulna,246.0,1970,1,19843 days 23:59:59.999997976
8,PH0009,Omar Faruq,Completed,1970-01-01 00:00:00.000002024,2024-06-08,Mr. Karim,Dhaka,291.0,1970,1,19881 days 23:59:59.999997976
9,PH0010,Priya Sharma,Completed,1970-01-01 00:00:00.000002024,2024-08-19,Mr. David,Dhaka,286.0,1970,1,19953 days 23:59:59.999997976
10,PH0011,Rahim Sheikh,Completed,1970-01-01 00:00:00.000002024,2024-06-11,Mr. Karim,Sylhet,283.0,1970,1,19884 days 23:59:59.999997976
11,PH0012,Sadia Chowdhury,Completed,1970-01-01 00:00:00.000002024,2024-10-25,Mr. Karim,Sylhet,266.0,1970,1,20020 days 23:59:59.999997976
12,PH0013,Tanvir Ahmed,Completed,1970-01-01 00:00:00.000002024,2024-08-03,Mr. David,Dhaka,248.0,1970,1,19937 days 23:59:59.999997976
13,PH0014,Urmi Akter,Completed,1970-01-01 00:00:00.000002024,2024-03-23,Mr. David,Sylhet,285.0,1970,1,19804 days 23:59:59.999997976
14,PH0015,Wahiduzzaman,Completed,1970-01-01 00:00:00.000002024,2024-05-16,Mr. David,Rajshahi,291.0,1970,1,19858 days 23:59:59.999997976
15,PH0016,Ziaur Rahman,Completed,1970-01-01 00:00:00.000002024,2024-06-21,Ms. Salma,Rajshahi,234.0,1970,1,19894 days 23:59:59.999997976
16,PH0017,Afsana Mimi,Completed,1970-01-01 00:00:00.000002024,2024-03-16,Mr. David,Khulna,NaN,1970,1,19797 days 23:59:59.999997976
17,PH0018,Babul Ahmed,Completed,1970-01-01 00:00:00.000002024,2024-09-20,Mr. David,Dhaka,278.0,1970,1,19985 days 23:59:59.999997976
18,PH0019,Faria Rahman,Completed,1970-01-01 00:00:00.000002024,2024-08-17,Mr. Karim,Sylhet,277.0,1970,1,19951 days 23:59:59.999997976
19,PH0020,Tariq Hasan,Completed,1970-01-01 00:00:00.000002024,2024-10-11,Mr. Karim,Khulna,253.0,1970,1,20006 days 23:59:59.999997976

In [112]:
Instructor_group=df.groupby('Instructor')
Instructor_group

In [117]:
for instructor,df_ins in Instructor_group:
    print(instructor)
    display(df_ins)

Mr. David

,StudentID,FullName,CompletionStatus,EnrollmentDate,FinishedDate,Instructor,Location,Total Marks,Enrollment year,Enrollment Date,Total time taken to finish
4,PH0005,Kamal Uddin,Completed,1970-01-01 00:00:00.000002024,2024-04-17,Mr. David,Sylhet,254.0,1970,1,19829 days 23:59:59.999997976
5,PH0006,Laila Begum,Completed,1970-01-01 00:00:00.000002024,2024-12-31,Mr. David,Khulna,272.0,1970,1,20087 days 23:59:59.999997976
6,PH0007,Mahmudul Hasan,Completed,1970-01-01 00:00:00.000002024,2024-07-20,Mr. David,Chattogram,NaN,1970,1,19923 days 23:59:59.999997976
9,PH0010,Priya Sharma,Completed,1970-01-01 00:00:00.000002024,2024-08-19,Mr. David,Dhaka,286.0,1970,1,19953 days 23:59:59.999997976
12,PH0013,Tanvir Ahmed,Completed,1970-01-01 00:00:00.000002024,2024-08-03,Mr. David,Dhaka,248.0,1970,1,19937 days 23:59:59.999997976
13,PH0014,Urmi Akter,Completed,1970-01-01 00:00:00.000002024,2024-03-23,Mr. David,Sylhet,285.0,1970,1,19804 days 23:59:59.999997976
14,PH0015,Wahiduzzaman,Completed,1970-01-01 00:00:00.000002024,2024-05-16,Mr. David,Rajshahi,291.0,1970,1,19858 days 23:59:59.999997976
16,PH0017,Afsana Mimi,Completed,1970-01-01 00:00:00.000002024,2024-03-16,Mr. David,Khulna,NaN,1970,1,19797 days 23:59:59.999997976
17,PH0018,Babul Ahmed,Completed,1970-01-01 00:00:00.000002024,2024-09-20,Mr. David,Dhaka,278.0,1970,1,19985 days 23:59:59.999997976

Mr. Karim

,StudentID,FullName,CompletionStatus,EnrollmentDate,FinishedDate,Instructor,Location,Total Marks,Enrollment year,Enrollment Date,Total time taken to finish
1,PH0002,Fatima Akhter,Completed,1970-01-01 00:00:00.000002024,2024-11-07,Mr. Karim,Dhaka,271.0,1970,1,20033 days 23:59:59.999997976
3,PH0004,Jannatul Ferdous,Completed,1970-01-01 00:00:00.000002024,2024-09-23,Mr. Karim,Khulna,NaN,1970,1,19988 days 23:59:59.999997976
8,PH0009,Omar Faruq,Completed,1970-01-01 00:00:00.000002024,2024-06-08,Mr. Karim,Dhaka,291.0,1970,1,19881 days 23:59:59.999997976
10,PH0011,Rahim Sheikh,Completed,1970-01-01 00:00:00.000002024,2024-06-11,Mr. Karim,Sylhet,283.0,1970,1,19884 days 23:59:59.999997976
11,PH0012,Sadia Chowdhury,Completed,1970-01-01 00:00:00.000002024,2024-10-25,Mr. Karim,Sylhet,266.0,1970,1,20020 days 23:59:59.999997976
18,PH0019,Faria Rahman,Completed,1970-01-01 00:00:00.000002024,2024-08-17,Mr. Karim,Sylhet,277.0,1970,1,19951 days 23:59:59.999997976
19,PH0020,Tariq Hasan,Completed,1970-01-01 00:00:00.000002024,2024-10-11,Mr. Karim,Khulna,253.0,1970,1,20006 days 23:59:59.999997976

Ms. Salma

,StudentID,FullName,CompletionStatus,EnrollmentDate,FinishedDate,Instructor,Location,Total Marks,Enrollment year,Enrollment Date,Total time taken to finish
0,PH0001,Alif Rahman,Completed,1970-01-01 00:00:00.000002024,2024-12-23,Ms. Salma,Khulna,300.0,1970,1,20079 days 23:59:59.999997976
2,PH0003,Imran Hossain,Completed,1970-01-01 00:00:00.000002024,2024-08-08,Ms. Salma,Dhaka,269.0,1970,1,19942 days 23:59:59.999997976
7,PH0008,Nadia Islam,Completed,1970-01-01 00:00:00.000002024,2024-05-01,Ms. Salma,Khulna,246.0,1970,1,19843 days 23:59:59.999997976
15,PH0016,Ziaur Rahman,Completed,1970-01-01 00:00:00.000002024,2024-06-21,Ms. Salma,Rajshahi,234.0,1970,1,19894 days 23:59:59.999997976

In [118]:
#df.min()
Instructor_group.min()

,StudentID,FullName,CompletionStatus,EnrollmentDate,FinishedDate,Location,Total Marks,Enrollment year,Enrollment Date,Total time taken to finish
Instructor,,,,,,,,,,
Mr. David,PH0005,Afsana Mimi,Completed,1970-01-01 00:00:00.000002024,2024-03-16,Chattogram,248.0,1970,1,19797 days 23:59:59.999997976
Mr. Karim,PH0002,Faria Rahman,Completed,1970-01-01 00:00:00.000002024,2024-06-08,Dhaka,253.0,1970,1,19881 days 23:59:59.999997976
Ms. Salma,PH0001,Alif Rahman,Completed,1970-01-01 00:00:00.000002024,2024-05-01,Dhaka,234.0,1970,1,19843 days 23:59:59.999997976

In [120]:
mean_marks=Instructor_group['Total Marks'].mean()
mean_marks

Instructor
Mr. David    273.428571
Mr. Karim    273.500000
Ms. Salma    262.250000
Name: Total Marks, dtype: float64

In [122]:
df['Total Marks']=df['Total Marks'].fillna(df['Instructor'].map(mean_marks))
df

,StudentID,FullName,CompletionStatus,EnrollmentDate,FinishedDate,Instructor,Location,Total Marks,Enrollment year,Enrollment Date,Total time taken to finish
0,PH0001,Alif Rahman,Completed,1970-01-01 00:00:00.000002024,2024-12-23,Ms. Salma,Khulna,300.000000,1970,1,20079 days 23:59:59.999997976
1,PH0002,Fatima Akhter,Completed,1970-01-01 00:00:00.000002024,2024-11-07,Mr. Karim,Dhaka,271.000000,1970,1,20033 days 23:59:59.999997976
2,PH0003,Imran Hossain,Completed,1970-01-01 00:00:00.000002024,2024-08-08,Ms. Salma,Dhaka,269.000000,1970,1,19942 days 23:59:59.999997976
3,PH0004,Jannatul Ferdous,Completed,1970-01-01 00:00:00.000002024,2024-09-23,Mr. Karim,Khulna,273.500000,1970,1,19988 days 23:59:59.999997976
4,PH0005,Kamal Uddin,Completed,1970-01-01 00:00:00.000002024,2024-04-17,Mr. David,Sylhet,254.000000,1970,1,19829 days 23:59:59.999997976
5,PH0006,Laila Begum,Completed,1970-01-01 00:00:00.000002024,2024-12-31,Mr. David,Khulna,272.000000,1970,1,20087 days 23:59:59.999997976
6,PH0007,Mahmudul Hasan,Completed,1970-01-01 00:00:00.000002024,2024-07-20,Mr. David,Chattogram,273.428571,1970,1,19923 days 23:59:59.999997976
7,PH0008,Nadia Islam,Completed,1970-01-01 00:00:00.000002024,2024-05-01,Ms. Salma,Khulna,246.000000,1970,1,19843 days 23:59:59.999997976
8,PH0009,Omar Faruq,Completed,1970-01-01 00:00:00.000002024,2024-06-08,Mr. Karim,Dhaka,291.000000,1970,1,19881 days 23:59:59.999997976
9,PH0010,Priya Sharma,Completed,1970-01-01 00:00:00.000002024,2024-08-19,Mr. David,Dhaka,286.000000,1970,1,19953 days 23:59:59.999997976
10,PH0011,Rahim Sheikh,Completed,1970-01-01 00:00:00.000002024,2024-06-11,Mr. Karim,Sylhet,283.000000,1970,1,19884 days 23:59:59.999997976
11,PH0012,Sadia Chowdhury,Completed,1970-01-01 00:00:00.000002024,2024-10-25,Mr. Karim,Sylhet,266.000000,1970,1,20020 days 23:59:59.999997976
12,PH0013,Tanvir Ahmed,Completed,1970-01-01 00:00:00.000002024,2024-08-03,Mr. David,Dhaka,248.000000,1970,1,19937 days 23:59:59.999997976
13,PH0014,Urmi Akter,Completed,1970-01-01 00:00:00.000002024,2024-03-23,Mr. David,Sylhet,285.000000,1970,1,19804 days 23:59:59.999997976
14,PH0015,Wahiduzzaman,Completed,1970-01-01 00:00:00.000002024,2024-05-16,Mr. David,Rajshahi,291.000000,1970,1,19858 days 23:59:59.999997976
15,PH0016,Ziaur Rahman,Completed,1970-01-01 00:00:00.000002024,2024-06-21,Ms. Salma,Rajshahi,234.000000,1970,1,19894 days 23:59:59.999997976
16,PH0017,Afsana Mimi,Completed,1970-01-01 00:00:00.000002024,2024-03-16,Mr. David,Khulna,273.428571,1970,1,19797 days 23:59:59.999997976
17,PH0018,Babul Ahmed,Completed,1970-01-01 00:00:00.000002024,2024-09-20,Mr. David,Dhaka,278.000000,1970,1,19985 days 23:59:59.999997976
18,PH0019,Faria Rahman,Completed,1970-01-01 00:00:00.000002024,2024-08-17,Mr. Karim,Sylhet,277.000000,1970,1,19951 days 23:59:59.999997976
19,PH0020,Tariq Hasan,Completed,1970-01-01 00:00:00.000002024,2024-10-11,Mr. Karim,Khulna,253.000000,1970,1,20006 days 23:59:59.999997976